### ISSUE TITLE
FocusComponents.common.input.checkbox.component is deprecated

### ISSUE THREAD

**Issue by Ephrame** [KleeGroup/focus-components#1000]
# Current behaviour

The component ` FocusComponents.common.input.checkbox.component` is deprecated

The new component is `focus-components/components/input/checkbox`

# Expected behaviour

remove the component

## Versions

Focus-core: latest
Focus-components: latest

**Comment by durandx** [comment]
+1

**Comment by Bernardstanislas** [comment]
@Ephrame thanks !

**Comment by pierr** [comment]
This component will be removed in the next version such as the old date component ?
