### ISSUE TITLE
[selection-list] secondary buttons are displayed behind the next line

### ISSUE THREAD

**Issue by gideruette** [KleeGroup/focus-components#1006]
# Current behaviour

On selection list, secondary buttons are displayed behind next line.

![image](https://cloud.githubusercontent.com/assets/15626856/13433178/013f1d1e-dfd1-11e5-8581-3fda190abc42.png)

# Expected behaviour
Secondary buttons should be ahead the next line

## Versions

Focus-core: 0.12.4
Focus-components: 0.8.6

**Comment by Bernardstanislas** [comment]
Hello @gideruette !
Could you please provide a better screenshot (global one of your screen) ? we don't see the issue correctly.
Thanks

**Comment by gideruette** [comment]
Actual behaviour :
 
![image](https://cloud.githubusercontent.com/assets/15626856/13570370/39740dba-e46e-11e5-9f3c-136019571851.png)

Expected behaviour : 

![image](https://cloud.githubusercontent.com/assets/15626856/13570342/16ea3ba2-e46e-11e5-9af3-0e1ea390b503.png)

**Comment by pierr** [comment]
@gideruette Do you have a custom css on your lines ?
Can you check the `z-index` difference between the two on your component?
Thanks

**Comment by gideruette** [comment]
I don't have any specific css on my lines.
It seems that both z-index are set to 0, and the reason why we are able see the first line of the actions is the following : the content of the actions have a z-index: 999. Adding z-index: 1 to the class sl-actions does the job.

.sl-actions {
  z-index: 1;
}
