### ISSUE TITLE
[Advanced search] show more does not behave well

### ISSUE THREAD

**Issue by Tommass** [KleeGroup/focus-components#1011]
# Current behaviour

When clicking on show more, it simply show the 3 next lines.

# Expected behaviour

It should launch a new request to server to get the next results.

## Versions

Focus-core: 0.13.0
Focus-components: 0.13.0

**Comment by pierr** [comment]
@Tommass Is it fixed ?

**Comment by pierr** [comment]
This needs to be discussed
-> Show More -> Works in memory and show only the next three result (it is a display concerns). After the user clicks show all if he needs to see all
-> Show all

cc @Bernardstanislas

**Comment by pierr** [comment]
@Tommass Reopen it if you disagree
