### ISSUE TITLE
[AdvancedSearch] crash when typing a too restrictive criterion while a facet is selected

### ISSUE THREAD

**Issue by Tsj-** [KleeGroup/focus-components#1039]
# Current behaviour

In the advanced search screen, I modify the search criteria while a facet is selected. If the result doesn't correspond with the selected facet, a error occured in the 'facet.js' saying the it can't find the property label of undefined.

![before](https://cloud.githubusercontent.com/assets/6391835/13605523/3466b806-e548-11e5-9744-8d816250fbfb.PNG)

Here I select the facet __Personnal Items__.

![after](https://cloud.githubusercontent.com/assets/6391835/13605957/39b04d0c-e54a-11e5-91d9-0607dbfb5d30.PNG)

Then I modify my criteria, searching for the name __cacahuete__, and the error occures.

Here's the JSON returned by the server.
```Javascript
{
   "list":[

   ],
   "facets":{
      "activitySector":{

      },
      "country":{

      },
      "groupBrandName":{

      }
   },
   "totalCount":0,
   "query":{
      "facets":[
         {
            "key":"activitySector",
            "value":"PERSONAL ITEMS"
         }
      ],
      "criteria":{
         "query":"cacahuete",
         "filterQuery":"+(currencyCode:EUR _missing_:currencyCode)",
         "scope":"Shop"
      },
      "group":"",
      "sortDescending":true,
      "skip":0
   }
}
```

# Expected behaviour
Two behaviour can be expected. 
Either we consider facets like filters and then the result should show no result, but the selected facet is still active.
Either the facet is considered as a restriction of the result, and depend on the criteria, and should be erased after the modification of the criteria.

## Versions

Focus-core: [0.12.4-rc2]
Focus-components: [0.8.6-rc0]

## N.B.

This problem have already been reported by @sgoretti

**Comment by jordanbenzacken** [comment]
+1

**Comment by Ephrame** [comment]
+1

**Comment by sgoretti** [comment]
:+1: 

I always +1 problems I reported before.

**Comment by JabX** [comment]
Wow this is indeed way more problematic than I initially thought.
Couldn't the server always return the queried facet value in the `facets` section of the results instead ? (making this a non-Focus issue), or are we directly interfering with how ElasticSearch works ?

**Comment by pierr** [comment]
As discussed with @Tsj- when the criteria is changed the search shoul be considered as reset, Facets are obsolete. 
The search process is (like many merchant sites) I search for something then I select facets to have filtered results depending on my initial search.

**Comment by pierr** [comment]
If we don't do so we would have to maintain a sort of facet context which is not guaranteed to be consistent after the new query.
