### ISSUE TITLE
[Field] Stateless component in a <Field /> raises a warning.

### ISSUE THREAD

**Issue by JabX** [KleeGroup/focus-components#1043]
I am using an inline stateless component for the `DisplayComponent` prop of `fieldFor` and I am prompted with this warning : 
`Warning: Stateless function components cannot be given refs (See ref "display" in DisplayComponent created by null). Attempts to access this ref will fail.`
The message is pretty much self-explanatory.

**Comment by pierr** [comment]
Indeed, we have seen this also, on `Lists`, we just need to find a function which can know if a component is a pure function or a statefull component.

Todo: identify which function to call

**Comment by pierr** [comment]
Maybe this:
```javascript

function hasRender(Class) {
 const prototype = Class.prototype;
  if (!prototype) {
    return false;
  }

  return typeof prototype.render === 'function';
}
```
