### ISSUE TITLE
[Column] React is not defined (Hidden : Global Variable deletion)

### ISSUE THREAD

**Issue by Pandakls** [KleeGroup/focus-components#1053]
### Context
New project, trying to import some old components

```javascript
import {column as Column, grid as Grid} from 'focus-components/common';
//[...]
    render(){
        return (
            <Grid>
                <Column size={3}><FakeMenu selected={false}/></Column>
                <Column size={9}><EmptySelection/></Column>
            </Grid>
        );
    }
```

### Current behaviour
The error "React is not defined" shows up in a file that is supposed to have it : 
![image](https://cloud.githubusercontent.com/assets/7700690/13785841/5c88ca76-ead5-11e5-8151-7a21c3449cbb.png)

The only way i found to correct this is to set : 
```javascript
window.React = require('react');
```
in my index.js
A behaviour that is now highly discouraged (Global variable i mean).

### Expected behaviour
Or we are allowed to defined gloal attributes like 'React' that is used in 100% of the component of the application (economy of 1 line per file).

Or the focus-component lib should be up to date to confirm the new 'no-global-stuff' policy.

### Versions
    "focus-components": "^0.13.0",
    "focus-core": "^0.13.0",

### Note : 
Why global vaiables are bad ? 

> Non-locality -- Source code is easiest to understand when the scope of its individual elements are limited. Global variables can be read or modified by any part of the program, making it difficult to remember or reason about every possible use.

**The variables that we want to set here won't be changed and will be strongly explicit (React, mixinTranslation, ...)**

> No Access Control or Constraint Checking -- A global variable can be get or set by any part of the program, and any rules regarding its use can be easily broken or forgotten. (In other words, get/set accessors are generally preferable over direct data access, and this is even more so for global data.) By extension, the lack of access control greatly hinders achieving security in situations where you may wish to run untrusted code (such as working with 3rd party plugins).

**Again, theses variables won't be modified and will keep their rules**

> Implicit coupling -- A program with many global variables often has tight couplings between some of those variables, and couplings between variables and functions. Grouping coupled items into cohesive units usually leads to better programs.

**There won't be many global variables, and will only be set global those highly used through the application**

> Concurrency issues -- if globals can be accessed by multiple threads of execution, synchronization is necessary (and too-often neglected). When dynamically linking modules with globals, the composed system might not be thread-safe even if the two independent modules tested in dozens of different contexts were safe.

**Because the global variable wont be modified, there won't be concurrency issues**

> Namespace pollution -- Global names are available everywhere. You may unknowingly end up using a global when you think you are using a local (by misspelling or forgetting to declare the local) or vice versa. Also, if you ever have to link together modules that have the same global variable names, if you are lucky, you will get linking errors. If you are unlucky, the linker will simply treat all uses of the same name as the same object.

**Javascript is not C, there won't be namespaces**

> Memory allocation issues -- Some environments have memory allocation schemes that make allocation of globals tricky. This is especially true in languages where "constructors" have side-effects other than allocation (because, in that case, you can express unsafe situations where two globals mutually depend on one another). Also, when dynamically linking modules, it can be unclear whether different libraries have their own instances of globals or whether the globals are shared.
Testing and Confinement - source that utilizes globals is somewhat more difficult to test because one cannot readily set up a 'clean' environment between runs. More generally, source that utilizes global services of any sort (e.g. reading and writing files or databases) that aren't explicitly provided to that source is difficult to test for the same reason. For communicating systems, the ability to test system invariants may require running more than one 'copy' of a system simultaneously, which is greatly hindered by any use of shared services - including global memory - that are not provided for sharing as part of the test.

**Javascript is not concerned on memory allocation issues**

To conclude, I don't see any reason not to set some variables in the window object. Moreover, the argument "that's not a good practice" is irrelevent because we have to consider what's the reasons behind this bad practices. And here they are! (above) Global constant variables can be used without troubles if they have explicit names not to occult the code lisibility. And in our situation we are talking about 1 economy of line for EACH variable for EACH file.

Sorry for the long post.

**Comment by Pandakls** [comment]
Found another Component that doesn't work without global variable : common.title
![image](https://cloud.githubusercontent.com/assets/7700690/13822602/9438a226-eba6-11e5-9127-498c5ac07fe5.png)

**Comment by pierr** [comment]
@Pandakls I think the problem is on your side because https://github.com/KleeGroup/focus-components/blob/d2c242d4553fade91a6e04add426f06bf47e2b6b/src/common/grid/index.js#L3 `React` is required.

**Comment by pierr** [comment]
@Pandakls We need to find some time do explain the Webpack config with @Jerom138

**Comment by Pandakls** [comment]
@pierr 
Yes but the composant title does not include react.
