### ISSUE TITLE
[Confirmation popin] Buttons with type=submit

### ISSUE THREAD

**Issue by durandx** [KleeGroup/focus-components#1054]
# Current behaviour
Putting a confirmation popin in a formMixin submit the underlying form if we use Confirm or Cancel button, whereas we should expect to only have the callback called.

# Expected behaviour
Please use the type='button' for the 2 buttons inside the Confirmation Popin.

https://github.com/KleeGroup/focus-components/blob/d5cbdf08ef50d9d0fc8c7c5b5d454d6fbf209e35/src/application/confirmation-popin/index.js#L84

## Versions
Focus-core: 0.13.0
Focus-components: 0.13.0

**Comment by pierr** [comment]
@durandx I think the problem is that the popin should not be in a parent form

**Comment by pierr** [comment]
You shoud have a callback

**Comment by pierr** [comment]
See #https://github.com/KleeGroup/focus-components/issues/940

**Comment by pierr** [comment]
Regarding the confirmation propin you can use https://github.com/KleeGroup/focus-core/blob/develop/src/application/confirm.js

**Comment by pierr** [comment]
The container is in the `Layout` so you won't have any problem.

**Comment by pierr** [comment]
@durandx ?

**Comment by pierr** [comment]
@durandx ?

**Comment by durandx** [comment]
I thought the idea of this component (Confirmation popin) was to use it in a "lightweight mode". I mean you can use it wherever you want in a form or not, without changing the hierarchy of my componenents. This behaviour can be like the MessageBox in the WIN32 API for example: it's very basic and you can use it everywhere.
