### ISSUE TITLE
[AdvancedSearch] Sort menu is not rendered (props: orderableColumnList)

### ISSUE THREAD

**Issue by durandx** [KleeGroup/focus-components#1055]
# Current behaviour
With the version 0.13.0, the property orderableColumnList is not working anymore.

```javascript
props = assign(
    {},
    require('./config/facet-config'),
    orderableColumnList: [
        {key: 'NOM', order: false, label: i18n.t('result.sort.nomDesc')},
        {key: 'NOM', order: true, label: i18n.t('result.sort.nomAsc')},
        {key: 'PRENOM', order: false, label: i18n.t('result.sort.prenomDesc')},
        {key: 'PRENOM', order: true, label: i18n.t('result.sort.prenomAsc')}
    ],
    require('./config/line-config'),
    {scopesConfig: require('../../../config/scopes')},
    {criteria: {scope: 'ALL'}}
);
[...]
 <AdvancedSearch
                cartridgeConfiguration={cartridgeConfiguration}
                groupComponent={Group}
                lineComponentMapper={lineComponentMapper}
                service={service}
                isSelection={false}
                {...props}
                />
```
I don't have the Sort menu:

![image](https://cloud.githubusercontent.com/assets/9220437/13809162/aaf2aa8a-eb69-11e5-9b85-e39d8f814a5b.png)

# Expected behaviour.
The sort Menu should be displayed
![image](https://cloud.githubusercontent.com/assets/9220437/13809102/793d2510-eb69-11e5-86ca-599da71f3296.png)

## Versions

Focus-core: 0.13.0
Focus-components: 0.13.0

**Comment by Bernardstanislas** [comment]
@durandx can you please double check this issue ? I tried to reproduce but I can't. I tested in the showcase, with your code, and I have the sort button correctly displayed.
Maybe it is a CSS issue ? Feel free to reopen if it's not the case.

**Comment by durandx** [comment]
We were in 0.12.4 in TFS at the time you tested. The 0.13.0 was only on my desktop, and I just pushed the new version in TFS 1 hour ago. (I wanted to test the new focus version (and with webpack) before commit)
