### ISSUE TITLE
[Scroll] Cartridge in summary mode when scrolled to the top

### ISSUE THREAD

**Issue by durandx** [KleeGroup/focus-components#1060]
# Current behaviour
With the createDetail wrapper, the cartridge is never in deployed state but keep staying in summary mode.

It's a regression: we have just updated to the 0.13.0 from the 0.12.4 version. Our page was working fine in 0.12.4 and now the bug is present in 0.13.0 whereas we don't made any change to the whole application...

# Expected behaviour
Please fix this regression.

## Versions

Focus-core: 0.13.0
Focus-components: 0.13.0

**Comment by pierr** [comment]
But this mixin does not do anything reagrding the action, it calls `this.cartridgeConfiguration` method on the page component.
Maybe in this method you have to add the  `isDeployed` as value. I think it is documented in a previous Release Note.

**Comment by pierr** [comment]
It calls https://github.com/KleeGroup/focus-components/blob/6a7f706a5613ce78fc0d9168aaa55772f815908a/src/page/mixin/cartridge-behaviour.js#L29

**Comment by pierr** [comment]
See https://github.com/KleeGroup/focus-components/pull/826#issue-123525224

**Comment by pierr** [comment]
Please @durandx let me know if you diagree

**Comment by durandx** [comment]
@pierr I've found the bug and pushed a pull request

**Comment by pierr** [comment]
@durandx  Thanks
