### ISSUE TITLE
[Result-list] "search.empty" label is not translated

### ISSUE THREAD

**Issue by Tommass** [KleeGroup/focus-components#1109]
# Current behaviour

In result list component, when rendered data list don't have data, "search.empty" label is displayed. This label should be translated but it isn't.

![image](https://cloud.githubusercontent.com/assets/5349745/14488341/0bfffe40-0168-11e6-854f-142d4d16cfc6.png)

# Expected behaviour

The label should be translated.

## Versions

Focus-core: 0.14.0
Focus-components: 0.14.1

**Comment by pierr** [comment]
Fix in #1115
