### ISSUE TITLE
[AdvancedSearch][Facets][Scope] Show all not working properly

### ISSUE THREAD

**Issue by skerdudou** [KleeGroup/focus-components#1124]
# Current behaviour

When we search with facet "ALL", the webservice returns the list of facets ("FCT_SCOPE") with their labels (not code).
The facet box translates it in the action (with \app\config\scopes\index.js) so that proper scope is selected.
The "show all" button instead is stick with label and doesn't resolve properly the scope.

When Label = Code, all work correctly but the user sees the code instead of the label.

# Expected behaviour

Same behaviour than when selecting from facet box.

## Versions

Focus-core: 0.14.0
Focus-components: 0.14.1

**Comment by pierr** [comment]
@Bernardstanislas Can you check this with @Ephrame

**Comment by pierr** [comment]
It seems to have been fixed by @JoanaDalmeida  in #1139
