### ISSUE TITLE
[AdvancedSearch] Set isSelection to false do not disable the "select all checkbox" in the action bar

### ISSUE THREAD

**Issue by hnomichi** [KleeGroup/focus-components#1131]
# Current behaviour

Set isSelection to false do not disable the "select all checkbox" in the action bar.

# Expected behaviour

It should disable the checkbox.

## Versions

Focus-core: [0.14.0]
Focus-components: [0.14.0]

**Comment by pierr** [comment]
Do you have a capture?

**Comment by pierr** [comment]
@hnomichi

**Comment by hnomichi** [comment]
[image: Images intégrées 1]

Elements from the list are not selectables, but we still have the "select
all" checkbox.


2016-05-09 10:14 GMT+02:00 Pierre Besson <notifications@github.com>:

**Comment by pierr** [comment]
@hnomichi I think the capture is not well displayed in the issue.

**Comment by pierr** [comment]
@hnomichi Can you also add a link to the github page of the component you want us to fix something.
Thanks.

**Comment by hnomichi** [comment]
![image](https://cloud.githubusercontent.com/assets/15378154/15316530/bb9c5586-1c1d-11e6-9d32-c8a3b620e601.png)

https://github.com/KleeGroup/focus-components/tree/develop/src/page/search/advanced-search
