### ISSUE TITLE
Close Date Picker on IE10 by a click on the page

### ISSUE THREAD

**Issue by mpsalvi** [KleeGroup/focus-components#1136]
# Current behaviour

With Internet Explorer 10 it is not possible to close the date pickers when clicking on the page (outside the datepicker).
The dataset field is not compatible with IE10.
https://github.com/KleeGroup/focus-components/blob/develop/src/components/input/date/index.js#L132

# Expected behaviour

The date picker should be closed by a click on the page not only while choosing a date on the date picker, but also by a click outside the datepicker. It is the currently working like that on other browsers like Chrome, Firefox or IE11. 

## Versions

Focus-core: [0.13.0]
Focus-components: [0.13.0]

**Comment by pierr** [comment]
On this issue it is also time to get rid of the data-react-id elements in order to be able to move to React 0.15

**Comment by pierr** [comment]
@GuenoleK Can you look at this issue.

**Comment by pierr** [comment]
@JoanaDalmeida any update on this
