### ISSUE TITLE
[AdvancedSearch] Select all prevent list to update in view

### ISSUE THREAD

**Issue by skerdudou** [KleeGroup/focus-components#1142]
# Current behaviour
1. Go to http://kleegroup.github.io/focus-showcase/#component/advanced-search/detail
2. Use the select all button (issue happening on select all or deselect all)
3. Chose the "Germany" filter
4. The list of city isn't updated

You can have the list updated by either touching again the select all button (but it will be stuck with the new list) or by touching a regular selection (update will works again normally)
# Expected behaviour

List always been updated
## Versions

Focus-core: 0.14.0
Focus-components: 0.14.1

**Comment by pierr** [comment]
@skerdudou Thanks, it seems as a bug indeed.

**Comment by pierr** [comment]
I will be in 0.16

**Comment by pierr** [comment]
@Ephrame I'd rather have @GuenoleK working on this. It seems related to another bug he has to treat.
