### ISSUE TITLE
[Secondary Actions Header] ReactDom is undefined

### ISSUE THREAD

**Issue by JohnnP** [KleeGroup/focus-components#1143]
# Current behaviour

When we click on the button generated by the secondary actions header, the error : `Uncaught ReferenceError: ReactDOM is not defined` appear.

![image](https://cloud.githubusercontent.com/assets/6448628/15188560/a9f8a454-17a6-11e6-9958-76579ec7af30.png)

We need to import ReactDom in our view to solve this issue.

# Expected behaviour

The import is done in the class which manage the header.

## Versions

Focus-core: 0.14.0
Focus-components: 0.14.1

**Comment by pierr** [comment]
Are you sure?
See https://github.com/KleeGroup/focus-components/blob/2a9e39d1ed08cdb103abbd0fc013a29858d10d0f/src/components/icon-dropdown/index.js#L2
The `import` is already done.

**Comment by JohnnP** [comment]
Yes, I tried again and the error is still here when i click on the secondary action button.

![image](https://cloud.githubusercontent.com/assets/6448628/15351716/eef181e0-1ce0-11e6-8716-39130f4994e3.png)

**Comment by Ephrame** [comment]
You can update to the next version, the problem is solved.

**Comment by pierr** [comment]
@JohnnP Upgrade and reopen the issue if there is a problem.
