### ISSUE TITLE
[selection-list-line] the lines selected shoud be checked and disabled

### ISSUE THREAD

**Issue by achermen** [KleeGroup/focus-components#1154]
# Current behaviour

[ If the line is (not isSelectionnable) and it is isSelected
you shoud disabled the ligne
     

# Expected behaviour

 
![renderselectionbox](https://cloud.githubusercontent.com/assets/9117792/15362964/4c9c2e22-1d17-11e6-8208-10e6ecb05475.PNG)

The lines selected  of the list shoud be checked and disabled]

## Versions

Focus-core: [0.14.0]
Focus-components: [^4.3.0]

**Comment by GuenoleK** [comment]
@achermen Hello ! Can i have more details on the bug, because i tested on an advance search which renders lists. I put the isSelection props to false. There is no more checkbox displayed, which is the normal behaviour.

**Comment by Ephrame** [comment]
Please have a look at https://github.com/KleeGroup/focus-components/blob/9de43fc817d80ecf26078be8b2d5d84531b433f7/src/list/selection/line.js#L75

You can set a function on your line component to decide wether your line is selectable or not.

```jsx
if(this.selectionnableInitializer) {
            this._isSelectionnable = this.selectionnableInitializer(data);
        }
```
