### ISSUE TITLE
Deprecated components are imported by other focus components

### ISSUE THREAD

**Issue by LentnerStefan** [KleeGroup/focus-components#1174]
# Current behaviour

The deprecated Buttton component is imported by non-deprecated components resulting in alot of warnings.
Below the "focus-component/message/index.js" imports the deprecated Button component:

![current](https://cloud.githubusercontent.com/assets/18282455/15613832/c32baf48-2435-11e6-9f11-310ca09ea34b.gif)

Also, the deprecated "Label" component is imported by "focus-component/common/field/mixin/built-in-components", resulting in a warning each time a fieldFor is used.

I'll update the issue if I find any other deprecated import.

# Expected behaviour

Focus components should import the non-deprecated component.

![expected](https://cloud.githubusercontent.com/assets/18282455/15613862/e81ccfd0-2435-11e6-9f12-3571150c006c.gif)

## Versions

Focus-core: 0.15.1-beta0
Focus-components: 0.15.4

**Comment by pierr** [comment]
That's because this message component is also deprecated. 
See https://github.com/KleeGroup/focus-components/blob/develop/src/components/message-center/index.js

It was mentioned in an earlier release note. 
But your demand is ok. If you want propose a PR.

**Comment by TomGallon** [comment]
fixed in PR #1175

**Comment by TomGallon** [comment]
Fixed by #1187
