### ISSUE TITLE
[TableMixin] Unable to render a table with at least 1 line

### ISSUE THREAD

**Issue by durandx** [KleeGroup/focus-components#1177]
# Current behaviour

The table Mixin is not working when I want to render at least one line.

![image](https://cloud.githubusercontent.com/assets/9220437/15705217/9ca28ed4-27ee-11e6-9192-abdb78161049.png)

My console display the folowing message in loop : 
![image](https://cloud.githubusercontent.com/assets/9220437/15705419/9972df56-27ef-11e6-9214-b9595f6ec84c.png)

My quad core use 100% on one core (25% cpu in total) :
![image](https://cloud.githubusercontent.com/assets/9220437/15705414/92b2d0d6-27ef-11e6-9b6c-9ac51b9a7cb9.png)

# Expected behaviour

Please declare the variable 'index' with the correct name : Please replace 'index' with 'idx'

```javascript
 _renderTableBody() {
        const {data, LineComponent: TableLineComponent, idField} = this.props;
        const reference = this._getReference();
        return (
            <tbody>
                {data.map((line, index) => {
                    const {data, ...otherLineProps} = this.props;
                    const tableBodyFinalProps = addRefToPropsIfNotPure(
                        TableLineComponent, {
                        className: TABLE_CELL_CLASS,
                        data: line,
                        key: line[idField],
                        reference,
                        ...otherLineProps
                    }, `${LINE}${idx}`);
                    return <TableLineComponent {...tableBodyFinalProps}/>;
                })}
            </tbody>
        );
    },
```
https://github.com/KleeGroup/focus-components/blob/a477a725dc4d7c58beccda5329b29a5a353d844f/src/list/table/list.js#L107

## Versions

Focus-core: 0.14.0
Focus-components: 0.14.0

**Comment by pierr** [comment]
@durandx You were on the wrong version.
