### ISSUE TITLE
[ListComponent] A line can don't appear because of key generation

### ISSUE THREAD

**Issue by JohnnP** [KleeGroup/focus-components#1179]
# Current behaviour

'focus-components/list/selection/list' : The composant generate a key with, if he exists, the data line's id or with the data' lines index. 

But if the id is equal to 0, he gonna take the index. So, if this index is equal to an other data line's id, the second line doesn't appear .

# Expected behaviour

The component should take the index in all cases.

## Versions
Focus-components: 0.15.0 (but the current 0.15.4 have still the issue)

**Comment by TomGallon** [comment]
The solution : use the idFIeld props.
