### ISSUE TITLE
[Autocomplete] Requests and results are not correlated

### ISSUE THREAD

**Issue by durandx** [KleeGroup/focus-components#1189]
# Current behaviour

Request and results are not always correlated. Consider the following events, in that order :

Request 1
Request 2
Response 2
Response 1

The response 1 is used to display the results, whereas the correct response to use should be Response 2. I think the last response received is always considered as the response to use even if does not match the last sent request.

Example:

I've entered "92340" in the autocomplete input, but I got the results for "92" :
![20160613-102618-001](https://cloud.githubusercontent.com/assets/9220437/16012292/1772f858-3189-11e6-945e-b9041e765b89.png)

# Expected behaviour

Please add a way to correlate the request/response in order to ignore all the reponses if it's not the one correponding to the last request.

## Versions

Focus-core: 0.15.0
Focus-components: 0.15.6

**Comment by TomGallon** [comment]
will be done in v3 http://github.com/get-focus/focus-components
