### ISSUE TITLE
Infinite-scroll with page list and table list components returns duplicates

### ISSUE THREAD

**Issue by mpsalvi** [KleeGroup/focus-components#1196]
# Current behaviour

The scroll pagination bring duplicates in the results : 
after sending the last request for the last chunk of data, another request is made which is equal to the first request (skip 0, top 50). 

![image](https://cloud.githubusercontent.com/assets/18739515/16151271/59db90ea-349c-11e6-8520-5246e9c98655.png)

------
https://github.com/KleeGroup/focus-components/blob/develop/src/page/list/index.js#L99 
There seems to be a problem with the data given to _buildListProps(). See the details below : 

Example with a request which have 56 results.

First request : top 50, skip 0
_buildListProps : 
	- dataList.length : 50 
	- totalCount : 56
	- hasMoreData : true
-> displays first 50 results	

Scroll on page 
FetchNextPage(1)
second request : top 50, skip 50
_buildListProps : 
	- dataList.length : 50
	- totalCount : 56
	- hasMoreData : true
FetchNextPage(2) (because hasMoreData is true, because props contains the previous and not the actual results of the request)
third request : top 50, skip 0 (same data as the first request)
_buildListProps : 
	- dataList.length : 56
	- totalCount : 56
	- hasMoreData : false
-> displays 106 results with 50 duplicates	

-------

# Expected behaviour

There should be no duplicates in the result page. 

## Versions

Focus-core: [0.15.0]
Focus-components: [0.15.6]

**Comment by pierr** [comment]
It seems that you didn't use the `isScroll` option on your action builder

**Comment by mpsalvi** [comment]
Thank you for your answer. 
I don't see how/where to set isScroll option. 
Our components are only using a service (and not an action) given in the props of the list page component just like the example given on https://github.com/KleeGroup/focus-components/tree/develop/src/page/list 
We don't use the action builder here. Is it wrong ?
Can you give more details about the right way the use the component ? 
Thank you for your help.

**Comment by pierr** [comment]
Hello, can you have a look to this tutorial : http://kleegroup.github.io/focus-docs/tutorial/admin-list.html

**Comment by pierr** [comment]
@mpsalvi

**Comment by mpsalvi** [comment]
Hello, thank you for the tutorial. 
In fact, the only difference between our components and this tutorial was that we didn't have the **action** set in the **props** of **page list** component. 
I added it but still encounter the **same behaviour** with a **extra** **request** equals to the first one, returning 50 results already present in the list. 
The behaviour is still a **fetchNextPage(2)** occuring because **listProps** are set with the data of the previous request and not the current one. 

Have you any idea about where we should investigate more ? 
Did you see this problem anywhere else on another project ? 

Thank you for help.

**Comment by durandx** [comment]
The problem is that the InfiniteScrollMixin call the scrollListener whereas the props hasMoreData is not refreshed with the latest data retrieved:
https://github.com/KleeGroup/focus-components/blob/43ed4a403b525c5847dd923f9c3055db66a24d8f/src/list/mixin/infinite-scroll.js#L95

As a quick fix, i've added a flag parameter to specify if we need to call scrollListener in the attachScrollListener.

```javascript
   /**
     * Attach scroll listener on the component.
     */
    attachScrollListener: function attachScrollListener(callScroll = true) {
        if (!this.props.hasMoreData) {
            return;
        }
        this.parentNode.addEventListener('scroll', this.scrollListener);
        this.parentNode.addEventListener('resize', this.scrollListener);
        if (callScroll) {
            this.scrollListener();    
        }
    }
```

The scrollListener must be explicitely called on mount but not on update.

```javascript
   /**
     * After component Mount.
     */
    componentDidMount: function componentDidMount() {
        this.parentNode = this.props.parentSelector ? document.querySelector(this.props.parentSelector) : window;
        if (!this.props.isManualFetch) {
            this.attachScrollListener(true);
        }
    },

    /**
     * after component update.
     */
    componentDidUpdate: function componentDidUpdate() {
        if (!this.props.isLoading && !this.props.isManualFetch) {
            this.attachScrollListener(true);
        }
    },
```

I know this solution is dirty, but I can't find a clean way to compute the hasMoreData props correctly.

**Comment by durandx** [comment]
I've found that our pages are doing well when we use a list/timeline, but we got an extra call when we use a table.

The props ```hasMoreData``` seems to be correctly computed for the Results/SelectionList, the timeline (focus-components/src/list/timeline/list.js).

The same prop (```hasMoreData```) is not properly computed for the table (focus-components/src/list/table/list.js).
