### ISSUE TITLE
[Advancedsearch][FacetBox] Facets values are not properly sorted

### ISSUE THREAD

**Issue by durandx** [KleeGroup/focus-components#1207]
# Current behaviour

Facets values are not properly sorted whereas the values sent from the server are.

Maybe this is linked to : https://github.com/KleeGroup/focus-components/issues/410

# Expected behaviour

https://github.com/KleeGroup/focus-components/blob/develop/src/search/facet-box/facet.js#L89

```javascript
     /**
     * Render the list of data of the facet.
     * @returns {XML} Html component code.
     */
    _renderFacetDataList() {
        if (!this.props.isExpanded || this.props.selectedDataKey) {
            return '';
        }
        let keysList = this.state.isShowAll ? keys(this.props.facet) : keys(this.props.facet).slice(0, this.props.nbDefaultDataList);
        return (
            <div className='' data-focus='facet-data-list'>
                <ul>
                    {keysList.map((key) => {
                        return (
                            <li key={key}>
                                <FacetData dataKey={key} data={this.props.facet[key]} selectHandler={this._facetDataSelectionHandler}
                                    type={this.props.type}/>
                            </li>
                        );
                    })}
                </ul>
                <div data-focus="facet-data-show-all">
                    {this._renderShowAllDataList()}
                </div>
            </div>);
    },
``` 

As ```this.props.facet``` is an object, applying ```_.keys``` does not guaranteed the order (that's what we have observed, the list is almost sorted):

```javascript
function Foo() {
  this.a = 1;
  this.b = 2;
}

Foo.prototype.c = 3;

_.keys(new Foo);
// → ['a', 'b'] (iteration order is not guaranteed)
```
http://devdocs.io/lodash~3/index#keys

## Versions

Focus-core: 0.15.0
Focus-components: 0.15.6

**Comment by TomGallon** [comment]
@durandx what vertigo version do you use ?

**Comment by durandx** [comment]
@TomGallon I use the version 0.9.1. When I inspect the JSON, the values sent from the server are properly sorted. I've debugged in the JS code and found that the order is lost when we use keys(this.props.facet).
In fact I think the API should be changed : `this.props.facet` should not be an object.

**Comment by pierr** [comment]
```javascript
let keysList = this.state.isShowAll ? keys(this.props.facet) : keys(this.props.facet).slice(0, this.props.nbDefaultDataList);
```
If this.props.facet is an array this should works

**Comment by pierr** [comment]
@durandx It seems the facets already are an array https://github.com/KleeGroup/focus-core/blob/develop/src/search/search-action/parser.js#L10

**Comment by durandx** [comment]
@pierr @TomGallon The focus-components 0.15.7 and focus-core 0.15.1 solved this issue. You can close it. Thanks you all.
