### ISSUE TITLE
[AdvancedSearch] custom groupableColumnList for advanced search ?

### ISSUE THREAD

**Issue by giopn** [KleeGroup/focus-components#1216]
# Current behaviour

Currently, it seems that the list of groups is based on the facets list. Is there a way to give a custom list of groups for the component ? I only need two grouping keys that are not part of the facets; and the groupableColumnList properties is not taken into account by the component.

## Versions

Focus-core: 0.15.0
Focus-components:  0.15.6

**Comment by TomGallon** [comment]
PR https://github.com/KleeGroup/focus-components/pull/1214

**Comment by GuenoleK** [comment]
Hello @giopn . Is your PR https://github.com/KleeGroup/focus-components/pull/1269 answer to this isssue ?

**Comment by giopn** [comment]
Yes @GuenoleK, exactly
