### ISSUE TITLE
Date used in form are dependent of the browser timezone

### ISSUE THREAD

**Issue by durandx** [KleeGroup/focus-components#1230]
# Current behaviour

Currently all the date are timezone dependant : If you change the timezone of your browser (via a global change in your Operating System) all the date will change.

I mean, for example that the birth date of a person will change (+/- 1 day) if you use a different timezone in the client OS.

Expected behavior defined for Focus : 
- all the date must use UTC-0 and should not be converted into a specific timezone

Forcing the utcOffset of moment to 0 in a initializer (```moment().utcOffset(0);```) do not properly override the timezone. The timezone is reverted back to the browser timezone when used in a form.

I've even tried to remove the locale defined in my domain definition and the result is the same.

# Expected behaviour

Please provide a timezone independant date system, as it was conceptually defined for Focus.

## Versions

Focus-core: 0.15.1
Focus-components: 0.15.7

**Comment by durandx** [comment]
The utcOffset was workgin. So I've spent a little time, finding another way to fix this problem.
Here is the solution :

Add and donwlod the npm dependency "moment-timezone" (in package.json)
Add an 'moment-initializer' in the project containing : 

```javascript
import moment from 'moment-timezone';

// Forcing timezone to UTC-0
moment.tz.setDefault('UTC');
```
Then all the date will be considered as UTC : all the date managed by focus will be timezone independent...

**Comment by durandx** [comment]
This issue can be close, but maybe you should add this in focus-component as a default behavior (because the contract was to use UTC as the timezone to send receive date from the server)...

I'm pretty sure ours overseas departments and territories' user will appreciate.

**Comment by pierr** [comment]
We use to provide moment time zone by default but it was not used by all projects. 
Only projects with timezone specific project can have benfefits from this.

**Comment by pierr** [comment]
But thanks for all the information located in this issue.

**Comment by durandx** [comment]
For information, we were not workking on a timezone specific project and we had this bug (on IE for example). The timezone choosen/configured by default can be different on old browser, mobile, tablet ...
IMO, it's clearly a compatibility bug as the application can work only on certain browser, OS and device...
