### ISSUE TITLE
[SelectAction] Style is not customizable

### ISSUE THREAD

**Issue by sanfinsm** [KleeGroup/focus-components#1231]
# Current behaviour

When using FocusComponents.common.selectAction.component, the menu container and outline have inline styles that can only be overriden using !important.

# Expected behaviour

The style of the dropdown should be customizable.

## Versions

Focus-core: 0.13.0
Focus-components: 0.15.6

**Comment by TomGallon** [comment]
hello @sanfinsm 

i don't see style given by focus that is not possible to override. Can you precise me where is your issue ?

Thx

**Comment by sanfinsm** [comment]
The style does indeed not come from Focus, I'm closing this issue.
