### ISSUE TITLE
[AdvancedSearch] The count is always 0

### ISSUE THREAD

**Issue by JohnnP** [KleeGroup/focus-components#1233]
# Current behaviour

The count is always 0

# Expected behaviour

The count should give the number of element.

## Versions

Focus-core: 0.16.2
Focus-components: 0.16.2

**Comment by TomGallon** [comment]
@JohnnP can you add a screen capture please ?

**Comment by JohnnP** [comment]
![image](https://cloud.githubusercontent.com/assets/6448628/17775287/d12fdd5e-6557-11e6-87c8-983019269c8e.png)

**Comment by TomGallon** [comment]
@JohnnP what is the version of vertigo ?

**Comment by JohnnP** [comment]
The issue is already fixed

**Comment by GuenoleK** [comment]
Thanks @JohnnP . So we are closing this issue.
