### ISSUE TITLE
[DatePicker] have min-max dates props to limit user range.

### ISSUE THREAD

**Issue by sgoretti** [KleeGroup/focus-components#1241]
# Current behaviour

User can select any date he wants.
Example:
In Linkit there are jobs with a start and end date. Inside these jobs a user can create a service, whose dates must be within the job. At the moment, the user can select any date he wants and when saving an error will display.

# Expected behaviour

I want to be able to prevent dates from being selectes outside a range  / afrter / before a given date.
Just as in captaintrain, when you select a departure date, your return date can't be before (and the departure date can't be before today).

## Versions

Focus-core: 0.15.0
Focus-components: 0.15.0

**Comment by sgoretti** [comment]
Ultimately, ti would be even better if we could add a label explaining the limits.
For example, the maximum date that can be picked would have a different color and the hover would display the text explaining the reason of this limit.
In my Linkit example, when creating a service, the max date would have "The job ends on DD/MM/YYYY. Services can't end beyond the job end." as an explanation in hover.

**Comment by TomGallon** [comment]
This issue was moved to get-focus/focus-components#4
