### ISSUE TITLE
[InputDate] INPUT_CHANGE triggered at every click on the page

### ISSUE THREAD

**Issue by tadamK** [KleeGroup/focus-components#1248]
# Current behaviour

When I have an input date component on my form, every time I click anywhere on the page, an INPUT_CHANGE is triggered. In particular it ruins the autocomplete when I click on it.

![input_change_date](https://cloud.githubusercontent.com/assets/14274196/18272091/28581276-7436-11e6-8e90-2a906793f637.gif)

# Expected behaviour

I'd like it not to be so mean.

## Versions

Focus-graph: 0.2.4-beta0
Focus-components: 0.17.0-beta2

**Comment by TomGallon** [comment]
This issue was moved to get-focus/focus-graph#117
