### ISSUE TITLE
[table] onLineClick not implemented

### ISSUE THREAD

**Issue by anisgh** [KleeGroup/focus-components#125]
The "onLineClick" is not implemented for table. 
Could you add this event ?

**Comment by pierr** [comment]
The result of this issue is : https://github.com/KleeGroup/focus-components/pull/145

**Comment by pierr** [comment]
As seen on https://github.com/KleeGroup/focus-components/pull/145/files#diff-49094a3c2b13ab111bb8b40cb14e4f21R65
The `onLineClick` handler should be implemented on the line and not automatically set by the parent.
The automatic parent registering was both too complex and too automatic.
