### ISSUE TITLE
[SELECT INPUT] Validator not working on undefined value;

### ISSUE THREAD

**Issue by LentnerStefan** [KleeGroup/focus-components#1277]
# Current behaviour

On a selectFor input (with "hasUndefined" and "isRequired" set as True), if you first select a value, then select the undefined value, the validator does not detect an error.

![validate_bad](https://cloud.githubusercontent.com/assets/18282455/19444901/a4241158-9492-11e6-9b79-b4dfad008640.gif)
# Expected behaviour

The validator should not allow the undefined value, since isRequired is set to True.
## Versions

Focus-core:  0.16.0
Focus-components: 0.16.1-beta4

**Comment by fconstantin** [comment]
@LentnerStefan could you check with your current version ?

**Comment by LentnerStefan** [comment]
The issue is fixed in focus-components v.2.1.2.
Thank you
