### ISSUE TITLE
[Menu] Let the possibility to choose icon library of buttons

### ISSUE THREAD

**Issue by rodolpheV** [KleeGroup/focus-components#1280]
# Current behaviour
Only material icon works.

# Expected behaviour
Authorize the props iconLibrary: 'font-custom'.

## Versions
Focus-components@3.0.0-rc18

**Comment by TomGallon** [comment]
This issue was moved to get-focus/focus-components#7

**Comment by TomGallon** [comment]
This issue was moved to get-focus/focus-components#8
