### ISSUE TITLE
[Menu/Panel] Make the subMenu in front of panels by default.

### ISSUE THREAD

**Issue by rodolpheV** [KleeGroup/focus-components#1281]
# Current behaviour
![layout_css_submenu_in_back](https://cloud.githubusercontent.com/assets/15649023/19481289/ae4f8f5c-954d-11e6-91eb-e5490cd41671.PNG)

# Expected behaviour
![layout_css_submenu_in_front](https://cloud.githubusercontent.com/assets/15649023/19481298/b44ad696-954d-11e6-8533-2dcede179eb0.PNG)

## Versions
focus-components@3.0.0-rc18

**Comment by TomGallon** [comment]
This issue was moved to get-focus/focus-components#6
