### ISSUE TITLE
Why do the state of my form is changed after my save call ?

### ISSUE THREAD

**Issue by EmilienSanterre** [KleeGroup/focus-components#1296]
# Current behaviour
I use the form with a list 'anomalies' whose default value is set from a prop 'anomaliesRef'

const DecisionControleFormView = React.createClass({
    displayName: 'DecisionControleFormView',
    mixins: [formMixin],
    definitionPath: 'instructionCtrl',
    action: {
        save: ctrlDecisionActions.save
    },
    stores: [{store: ctrlDecisionStore, properties: ['ctrlNewControle']}],
    propTypes: propTypes,
    defaultProps: defaultProps,

    getInitialState() {
        const {anomaliesRef, insId} = this.props;
        let anomalies = [];
        if(anomaliesRef) {
            anomaliesRef.forEach((tano) => {
                tano.siSelect = false;
                anomalies.push(tano);
            });
        }
        return {
            anomalies: anomalies
        };
    },
//anomaliesRef is loaded asynchronously
    componentWillReceiveProps(nextProps) {
        if((nextProps.anomaliesRef && this.state.anomalies.length === 0) {
            this.setState({
                ...this.getInitialState()
            });
        }
   },

    onChangeAnomalies(tanoId, siSelect) {
        const {anomalies} = this.state;
        anomalies.find((tano) => {
            return +tanoId === +tano.tanoId
        }).siSelect = siSelect;
        this.setState({anomalies});
    },

renderContent() {
        return (
                <Panel actions={this._renderActions} title={title}>
                    {this.listFor('anomalies',
                                {LineComponent: CheckBox, isEdit: isEdit,
                                labelKey: 'libelle', idKey: 'tanoId', valueKey: 'siSelect',
                                onChange: this.onChangeAnomalies, dataComponent: 'listCheckbox'}
                            )}
                   />
    );

Before clicking save i have a good state, for exemple : 
{
 anomalies : [ {tanoId:1, siSelect: false, libelle: "Habilitation"}, {tanoId:2, siSelect: false, libelle: "Codification"} }
}
After my webservice return : 
{
  "globalErrors": [
    "SI le contrôle est non conforme, il faut renseigner les types d\u0027anomalies correspondants."
  ]
}

And my state is {
anomalies : []
}

# Expected behaviour

I do not understand why a setState is done and why it empties my list...

## Versions

Focus-core: 0.16.0-cavimac-3.0
Focus-components: 0.16.3-cav

**Comment by Hartorn** [comment]
Don't think this is relevant anymore
