### ISSUE TITLE
[store Behaviour] data not stored in correct object

### ISSUE THREAD

**Issue by anisgh** [KleeGroup/focus-components#130]
In our example, we are waiting for an array of "bases" from store using storeBehaviour mixin. But when store is updated after server response, the returned objects are saved as separated objects : 
![image](https://cloud.githubusercontent.com/assets/5940196/8380824/36153cde-1c28-11e5-9469-73521005d08a.png)

and the actual "bases" array remain empty:
![image](https://cloud.githubusercontent.com/assets/5940196/8380973/2df0371a-1c29-11e5-9d55-6483dda68efa.png)

**Comment by pierr** [comment]
Can you check the following function:
```
_computeEntityFromStoresData: function(data) {
    if(this.computeEntityFromStoresData){
      return this.computeEntityFromStoresData(data);
    }
    var entity = {reference: {}};
    for(var key in data){
      if(this.referenceNames && this.referenceNames.indexOf(key) !== -1 ){
        entity.reference[key] = data[key];
      }else {
        var d = data[key];
        if(!isObject(d)){
          d = {[key] : d};
        }
        assign(entity, d);
      }
    }
    return entity;
  },
```

And tell me if where you en up in your case
