### ISSUE TITLE
A tabbed component is highly appreciable

### ISSUE THREAD

**Issue by mo-ben** [KleeGroup/focus-components#1302]
Is it possible to have a component that allows to create tabs in a page in order to be able to load the contents asynchronously (each tab only loads what it needs).

Focus-core: 2.0.0
Focus-components: 2.0.1

Thank you in advance for your answer.

**Comment by Hartorn** [comment]
Hi,

I think we are doing something like this in our project, using material design component :
https://getmdl.io/components/index.html#layout-section/tabs
```
<div className="mdl-tabs mdl-js-tabs">
  <div className="mdl-tabs__tab-bar">
{ this.props.tabs.map((item, idx) => {
      <Link className="mdl-tabs__tab" to={'route/to/currpage/' + item.name} />
     })
}
</div>
  <div class="mdl-tabs__panel is-active">
    {this.props.children}
  </div>
</div>
```
or something like that.

Then just add the child routes in your react router.
Ask me tomorrow if you need more details.

**Comment by JohnnP** [comment]
I think we can share the lazy decorator. It can be useful for the other projects

**Comment by mo-ben** [comment]
Thanks for you JohnnP.

:)
