### ISSUE TITLE
Error in updating

### ISSUE THREAD

**Issue by JohnnP** [KleeGroup/focus-components#1328]
@Hartorn 

* The datePicker's style changed and it's impossible to select a date

Before:

![image](https://cloud.githubusercontent.com/assets/6448628/21892296/6613f85a-d8d6-11e6-9bb6-767cba1c7653.png)

* InputText doesn't work. It's impossible to write text.

**Comment by JohnnP** [comment]
In fact, yesterday it was impossible to select a date, but now it's possible. However, the style has also changed (it's the second time) and it's not really user friendly

![image](https://cloud.githubusercontent.com/assets/6448628/21892750/8fcd1ee0-d8d8-11e6-8746-bc9891ec2bf1.png)

**Comment by Hartorn** [comment]
input date : Change on react-date-picker api => onChange, or onDateActiveChange (to test)
to change in handleDropDownChange => the moment date is in date.dateMoment

**Comment by JohnnP** [comment]
I wanted to add the result but you are too fast

**Comment by JohnnP** [comment]
There is this issue with the render of field in edit mode. Fields are moved downward

![image](https://cloud.githubusercontent.com/assets/6448628/21925623/960fe282-d97e-11e6-9678-a51a3535c9a1.png)

**Comment by Hartorn** [comment]
TODO 

Rollback deleting common components, move them to legacy
Rollback Error handlling
Rebase on develop
