### ISSUE TITLE
[Field] State errors are overidden by props's errors when form rerender

### ISSUE THREAD

**Issue by gideruette** [KleeGroup/focus-components#1347]
# Current behaviour

After validation, my form rerender and empty error pros is given to the field. 

- This rerender override the set state({error: error}), it doesn't finish the action
- The props error override state error, then the field doesn't display it's error

# Expected behaviour

The component should give the choice to override or not the state error, or it  should'nt override state error when it's already set.

componentWillReceiveProps: function componentWillReceiveProps(newProps) {
        var self = this;
        setTimeout(function(){
            var nextState = {
                value: newProps.value,
                values: newProps.values
            };
            if(!self.state.error && newProps.error){
                nextState.error = newProps.error;
            }
            self.setState(nextState);
        }, 0);
    },

## Versions

Focus-core: 2.1.1
Focus-components: 2.1.4

**Comment by JohnnP** [comment]
I had the same issue. I did a correction which fix this. I gonna do the PR

**Comment by fconstantin** [comment]
Hotfix available with 2.1.4-hotFix2

**Comment by fconstantin** [comment]
To test with #1348

**Comment by Hartorn** [comment]
Fixed in 2.1.7
