### ISSUE TITLE
[Advancedsearch][FacetBox] missing assignement in Initial state 

### ISSUE THREAD

**Issue by rodolpheV** [KleeGroup/focus-components#1353]
The line: https://github.com/KleeGroup/focus-components/blob/master/src/search/facet-box/index.js#L53
should be:
`openedFacetList = this._generateOpenedFacetList(this.props.facetList);`
like in `componentWillReceiveProps`.

Consequence of this omission is that the component doesn't work if it is rendered only once.

**Comment by Hartorn** [comment]
Delivered in 2.2.0
