### ISSUE TITLE
[InputDate] onChange is not called when you empty the value

### ISSUE THREAD

**Issue by EmilienSanterre** [KleeGroup/focus-components#1357]
`<InputDate       onChange={this._onChangeDateRatt}
                            value={dateRattForm}
                            error={errorRatt}
                            format={format}
                            label={translate('contrat.dateRattachement')}
/>`
# Current behaviour
if I chose a value, _onChangeDateRatt is called but not when i empty the value.

# Expected behaviour
_onChangeDateRatt should be called whenever the value changes

## Versions

Focus-core: 2.1.1
Focus-components: 2.1.4

**Comment by Hartorn** [comment]
Fixed in 2.1.7
