### ISSUE TITLE
[FocusComponents.components.Panel] Panel should not display title space when there is no title or action defined

### ISSUE THREAD

**Issue by gideruette** [KleeGroup/focus-components#1370]
# Current behaviour

An empty space appears on the top of the panel even if there is no title and no action defined

![image](https://cloud.githubusercontent.com/assets/15626856/25037842/b71a6d66-20fb-11e7-94ac-ed19f50eba4e.png)

# Expected behaviour
Add a condition to this block
![image](https://cloud.githubusercontent.com/assets/15626856/25037905/175f5f92-20fc-11e7-86ce-67927306aa4f.png)

## Versions

Focus-core: 2.1.1
Focus-components: 2.1.4-hotFix3

**Comment by Hartorn** [comment]
Fixed in 2.1.7
