### ISSUE TITLE
Read a subset of data from a store

### ISSUE THREAD

**Issue by mo-ben** [KleeGroup/focus-components#1374]
Sometimes we need to connect to a store to read only a portion of the recorded data.

Currently: the declaration of a store connection in a mixin form is done as follows:

`
stores: [{ store: storeName, properties: ['nodeStore1', 'nodeStore2'] }]
`

It would be very interesting to have the ability to read only a part of the data from th store. It will allow us to read  only what we need without polluting the current state of a component with unnecessary data.

Example of desired store definition:

`stores: [{store: storeName, properties: ['nodeStore1', 'nodeStore2'], includedData: ['propsName1', 'propsName2']}]
`

**Comment by Hartorn** [comment]
Seems like a good idead.
Will have a look at it, when I have some time.

**Comment by AdrienViala** [comment]
utiliser un store-behaviour plutôt qu'un mixin.
