### ISSUE TITLE
[actionContextual] OnClick is undefined

### ISSUE THREAD

**Issue by gideruette** [KleeGroup/focus-components#1387]
# Current behaviour

Clicking on action contextual rise an exception.

![image](https://cloud.githubusercontent.com/assets/15626856/26625365/28ed1688-45f4-11e7-85fc-33563734341b.png)

![image](https://cloud.githubusercontent.com/assets/15626856/26625408/466707be-45f4-11e7-8a91-aa7d1929a76b.png)

Then, actions are correctly displayed.

# Expected behaviour

No exception should be risen

## Versions

Focus-core: 2.1.1
Focus-components: 2.1.7

**Comment by Hartorn** [comment]
Fixed in 2.1.7-1
