### ISSUE TITLE
[SelectionList] ShouldComponentUpdate throws exception

### ISSUE THREAD

**Issue by gideruette** [KleeGroup/focus-components#1397]
# Current behaviour

1. Select an item
2. Click on 'Display more'

An exception is thrown, and all elements are displayed

"Uncaught TypeError: Cannot read property 'size' of null"

![image](https://user-images.githubusercontent.com/15626856/27131724-349b66e2-510c-11e7-9f97-67b90e918206.png)

# Expected behaviour

No exception should be thrown

## Versions

Focus-core: 2.1.7-1
Focus-components: 2.1.1

**Comment by Hartorn** [comment]
Can you give me the path of the component please @gideruette  ?

**Comment by gideruette** [comment]
FocusComponents.page.list.component

**Comment by Hartorn** [comment]
Not in focus.
