### ISSUE TITLE
Keyresolver called even when undefined

### ISSUE THREAD

**Issue by eheslouisKlee** [KleeGroup/focus-components#1398]
# Current behaviour

The keyresolver is called even if the input is undefined.

# Expected behaviour

If the input is undefined, the keyresolver should do nothing

## Versions

Focus-core: 2.1.1
Focus-components: git://github.com/KleeGroup/focus-components.git#add-rgaa-updated

**Comment by Hartorn** [comment]
Delivered in 2.2.0
