### ISSUE TITLE
Tooltip doesn't take className well

### ISSUE THREAD

**Issue by eheslouisKlee** [KleeGroup/focus-components#1399]
# Current behaviour

When passing a className to Tooltip, the className is not well construted. A space is missing between the props.ClassName and the rest of the className.

![capturetooltip2](https://user-images.githubusercontent.com/29572315/27331973-3c02653a-55c0-11e7-930c-607fb84746e8.JPG)

![capturetooltip1](https://user-images.githubusercontent.com/29572315/27332143-fa055ba0-55c0-11e7-90fe-98fd95c89539.JPG)

# Expected behaviour

The className should be as following:

![capturetooltipgood1](https://user-images.githubusercontent.com/29572315/27332101-c698097a-55c0-11e7-9d9c-b0f6b4b0d361.JPG)

## Versions

Focus-core: 2.1.1
Focus-components: git://github.com/KleeGroup/focus-components.git#add-rgaa-updated

**Comment by JohnnP** [comment]
Fix with PR #1400

**Comment by Hartorn** [comment]
Delivered in 2.2.0
