### ISSUE TITLE
[focus-component/common\form\mixin\action-behaviour.js] _getEntity() methode

### ISSUE THREAD

**Issue by redlapin** [KleeGroup/focus-components#140]
In the file focus.components//common\form\mixin\action-behaviour.js, the method `_getEntity()` doesn't return the right values of data.
the problem is in this method, `this.refs[r].getValue()` will change the type of data. for example: A is a number, but the type of A which is returned by `this.refs[A].getValue()` will change to string.

`this.refs[r].state.value` seems to return the right type of data.

**Comment by pierr** [comment]
Are you sure the domain is configure?

**Comment by pierr** [comment]
As seen together, this is not a bug.
The domain has to be configured : see https://github.com/KleeGroup/focus/tree/master/definition
