### ISSUE TITLE
[Form] Unexpected interaction between storeMixin and referenceMixin

### ISSUE THREAD

**Issue by rodolpheV** [KleeGroup/focus-components#1404]
## Unexpected behaviour
I have a main form which need the reference list 'countryList'.
If the 'countryList' reference is reloaded, this form does a `this.setState(this._getStateFromStores())`.
Problem: If I am editing an item with this main form, and if another view reload the 'countryList' reference, I lose my current modifications in the main form because it reload its state from the store.

## Expected behaviour
I would expect the store behaviour to do a getStateFromStore only for the updated nodes of the store, not for all my listening nodes.

## Versions
Focus-core: 2.1.1
Focus-components: 2.1.7-1

**Comment by Hartorn** [comment]
@rodolpheV Indeed it is problematic. The handlers are not as precised as needed.
To avoid this problem, you can override this by using onChange on your form :
https://github.com/KleeGroup/focus-components/blob/5af5f0e8244fadee88cb733c737a7cd25d855d18/src/common/mixin/store-change-behaviour.js#L60
That way, you can decide to trigger or not the ` this.setState(this._getStateFromStores(), () => this._afterChange(changeInfos));`

If I have time, I will come and see you today.

**Comment by Hartorn** [comment]
Delivered in 2.2.0
