### ISSUE TITLE
wrong behavior with the selectcheckbox

### ISSUE THREAD

**Issue by eheslouis** [KleeGroup/focus-components#1412]
# Current behaviour

While using a fieldFor, the onChange of the selectCheckBox returns the key of the element that was changed.

# Expected behaviour

The onChange should return an object containing the key and the newStatus of the key. Even better, if it returned a table of the selected keys.

## Versions

Focus-core: 2.1.1
Focus-components: #add-rgaa-updated

**Comment by Hartorn** [comment]
Indeed. Behaviour should be : value is an array of key/id, onChange return the new array

Option should be added to keep old behaviour, but the default behaviour should be the new one

**Comment by c3dr0x** [comment]
@Hartorn 
I agree with the new default behaviour.

For legacy, do you already have something in mind ? 
If I keep both parameters `(key, newStatus)` the `field-component-behaviour._wrappedOnChange` will still truncate the `newStatus`.

I propose for legacy to pass to `onChange` an object with both keys `{ key, newStatus }`. What do you think ?

**Comment by Hartorn** [comment]
Done in #1414

**Comment by Hartorn** [comment]
Delivered in 2.2.0
