### ISSUE TITLE
[Dropdown] Add a type="button" on the button.

### ISSUE THREAD

**Issue by rodolpheV** [KleeGroup/focus-components#1416]
# Current behaviour
A button type is `submit` by default, and the dropdown doesn't define a type for its button. 
So if the dropdown is used in a formMixin, it will trigger the save action when trying to expand the dropdown.

# Expected behaviour
The dropdown button should have type `button` to not trigger a save.

## Versions
Focus-core: 2.1.1
Focus-components: 2.1.7-1

**Comment by LentnerStefan** [comment]
![complexity](https://user-images.githubusercontent.com/18282455/28173784-bfd188fa-67ef-11e7-8b8f-78c34efb007c.jpg)

**Comment by Hartorn** [comment]
Delivered in 2.2.0
