### ISSUE TITLE
Code for Multi-Autocomplete

### ISSUE THREAD

**Issue by eheslouisKlee** [KleeGroup/focus-components#1418]
Attached is the code for a component of multi-autocomplete.

[multi-autocomplete.zip](https://github.com/KleeGroup/focus-components/files/1158705/multi-autocomplete.zip)

**Comment by Hartorn** [comment]
@eheslouisKlee Thanks :-)

@JohnnP @LentnerStefan @c3dr0x Anyone want to do this ? The component is finished, the only thing needed is to rename the data-aee into data-focus, and test the component a bit more.

**Comment by Hartorn** [comment]
Done in #1420

**Comment by Hartorn** [comment]
Delivered in 2.2.0
