### ISSUE TITLE
Error message on the select component

### ISSUE THREAD

**Issue by Bronxbk** [KleeGroup/focus-components#1427]
![select](https://user-images.githubusercontent.com/25983048/28709866-4a197d9a-7382-11e7-9156-fe4b4b03a39d.png)
# Current behaviour

[Description of the current behaviour and what the problem / issue is for you]
Le message d'erreur dans le composant select n'est pas fixe 

[Screenshots : if possible, use animated gifs for a better representation]

# Expected behaviour

[Description of the exprected behaviour]

[If you judge it necessary, add a screenshot]

## Versions

Focus-core: [version]
Focus-components: [version]

**Comment by Hartorn** [comment]
I need to reproduce it, seems like it is only on this project :(

**Comment by Bronxbk** [comment]
Yes indeed its only on the sagess project 
Thak you
