### ISSUE TITLE
Turn off autoComplete in the AutoComplete component

### ISSUE THREAD

**Issue by eheslouisKlee** [KleeGroup/focus-components#1429]
# Current behaviour

The Autocomplete allows the navigator's autocomplete which doesn't return the code and is confusing for the user.

# Expected behaviour

The attribute 'autoComplete="off"' should be added by default to the composent so that the only clickable options come from the focus composent.

## Versions

Focus-core: lastest
Focus-components: lastest

**Comment by Hartorn** [comment]
@bnau Small issue to begin with.
Basically, it is adding a props on the input, so web navigator do not output an autocomplete.
See https://developer.mozilla.org/fr/docs/Web/HTML/Element/Input#attr-autocomplete for detail.

Be wary of React "camelcasing" attribute on html element.

**Comment by bnau** [comment]
Pull request #1461

**Comment by Hartorn** [comment]
Delivered in 2.2.0
