### ISSUE TITLE
SelectRadio doesn' show the current value on Firefox

### ISSUE THREAD

**Issue by eheslouisKlee** [KleeGroup/focus-components#1439]
# Current behaviour
The component SelectRadio doesn't work properly on Mozilla.
When using the SelectRadio as SelectComponent, in edit mode, the Radio button is not initialized correctly.

![giphy 1](https://user-images.githubusercontent.com/29572315/29921959-faf0f436-8e53-11e7-8644-be1a3ced6397.gif)

# Expected behaviour

The Radio Button should be correctly initialized.

## Versions

Focus-core: [version]
Focus-components: [version]

**Comment by Hartorn** [comment]
Delivered in 2.2.0
