### ISSUE TITLE
[StoreBehavior] Default data does not work

### ISSUE THREAD

**Issue by c3dr0x** [KleeGroup/focus-components#1477]
Default data aren't destructured and theredore does not work when node is an object.

**Comment by Hartorn** [comment]
@c3dr0x I don't understand the bug. Could you give me an example ?

Normalley, with this line, default data should work 
https://github.com/KleeGroup/focus-components/blob/develop/src/common/mixin/store-behaviour.js#L77

**Comment by c3dr0x** [comment]
What's wrong is that the `defaultData` should be merged with `newState` before going through `_computeEntityFromStoresData`
I think that it worked previously but considering the `pick` with `filterNodes`: defaultData must contain default values grouped inside a node key

**Comment by Hartorn** [comment]
Okay I see now. 
Don't see how to fix this however : defaultData is built from definition, and we have no information from which node this data should come. 
Ideally, defaultData should be { node: {... //current default data }

Maybe we can do something like handle reference store by testing it, and using default value if there is only one other store/node ?
At the moment, the filtering is removing everything.

**Comment by Hartorn** [comment]
@c3dr0x Might have an idea : see  #1479

**Comment by Hartorn** [comment]
Delivered in 2.2.0
