### ISSUE TITLE
Select component does not translate error

### ISSUE THREAD

**Issue by Hartorn** [KleeGroup/focus-components#1488]
Select component does not translate error.

**Comment by bnau** [comment]
Do you have an example code? Should we use fieldFor or directly the select component?

**Comment by Hartorn** [comment]
See this [file](https://github.com/KleeGroup/focus-components/blob/develop/src/components/input/select/index.js) line 123.

You can use it directly, or with fieldFor, result should be the same. Use setError of fieldFor, or give error props

**Comment by bnau** [comment]
PR #1510

**Comment by Hartorn** [comment]
Fixed in 2.2.2
