### ISSUE TITLE
Form save action incompatible with vertigo

### ISSUE THREAD

**Issue by sanfinsm** [KleeGroup/focus-components#1508]
# Current behaviour
When saving an object, all its fields are set to null if they have not been filled.
This leads Vertigo to check for notNull fields, including the ID.
This behaviour prevents us from creating new instances.

# Expected behaviour
Not setting the property at all would prevent the check on the java side.

Suggested fix in common/mixin/store-behaviour.js :

```
_buildEmptyFromDefinition() {
        if (this.buildEmptyFromDefinition) {
            return this.buildEmptyFromDefinition();
        }
        return Object.keys(this.definition)
            .reduce((acc, key) => ((__IS_VERTIGO__ || this.partialObject) && !this.refs[`${this.definitionPath}.${key}`] ? acc : { ...acc, [key]: null }), {});
}
```

Define __IS_VERTIGO__ variable in webpack.config.js if necessary.
`myConfig.addDefinedVariable('__IS_VERTIGO__',' true');`

**Comment by Hartorn** [comment]
Fixed in 2.2.2
