### ISSUE TITLE
[scroll] zigwiwi

### ISSUE THREAD

**Issue by pierr** [KleeGroup/focus-components#164]
When window's vertical overflow is a few pixel the header height switch between two mode.

**Comment by pierr** [comment]
This will be fixed when we will use tween state component

**Comment by pierr** [comment]
@Tommass  is it still an issue?

**Comment by Tommass** [comment]
to test...

**Comment by pierbrisson** [comment]
:+1:

**Comment by pierr** [comment]
![zigwigwi](https://cloud.githubusercontent.com/assets/9960528/10643263/37eb795a-7822-11e5-8d8c-7ba728388ef5.gif)

**Comment by pierr** [comment]
@pierbrisson this issue is now concidered critical

**Comment by Bernardstanislas** [comment]
@pierbrisson the current quick fix is to put
```css
[data-focus='layout'] {
	min-height: calc(100vh + 6px);
}
```
in your stylesheets.

**Comment by pierbrisson** [comment]
can we get a more stable fix to this issue please.
Cheers
