### ISSUE TITLE
The "left menu" doesn't work fine

### ISSUE THREAD

**Issue by julienKlee** [KleeGroup/focus-components#170]
1- On Firefox le left menu doesn't show
2- On chrome, it is shown, but if i click the "Fonctions" item, the page go down and automaticlaly up again 
![sans titre](https://cloud.githubusercontent.com/assets/13589034/9108421/3adc295a-3c2e-11e5-8173-58ed59d9ea20.png)

**Comment by pierr** [comment]
After the update to v0.4.0, if it has been deployed to your project the 1 has been fixed #163

**Comment by pierr** [comment]
Could you please provide some context, is it the case on all the menu elememnts ? Or just on the function one ?

**Comment by julienKlee** [comment]
It's all the item wich doesn't work.
And sometimes, when i scroll, the menu doesn't change the selected item.

**Comment by pierr** [comment]
@Tommass Can you see if you reproduce this behaviour ?

**Comment by pierr** [comment]
I thought this issue https://github.com/KleeGroup/focus-components/issues/153 fixes the bug

**Comment by durandx** [comment]
A click on the left menu (from the detail component) doesn't work on
- IE 11 
- Firefox 39 

It is working only on chrome based browser :
- Chrome 44
- Safari 5.1.7 (chrome based)
- Opera 31 (chrome based)
- Vivaldi 1.0.83 (chrome based)

You can easily test it on the focus-demo (ex : <server>/focus/#movie/1384886 )
