### ISSUE TITLE
[component][changeBehaviourMixin] lack of translation for detail.saved

### ISSUE THREAD

**Issue by durandx** [KleeGroup/focus-components#175]
Please add a i18n support in the mixin changeBehaviourMixin (
common\mixin\store-change-behaviour.js) for key ```detail.saved```

https://github.com/KleeGroup/focus-components/blob/cd119d6b0bdf833e79ccd1e8fb8c7bc4f7d68160/common/mixin/store-change-behaviour.js#L25

**Comment by pierr** [comment]
Indeed. Will be fixed in next release
