### ISSUE TITLE
DatePicker - Incorrect rendering

### ISSUE THREAD

**Issue by remigrange** [KleeGroup/focus-components#176]
The Month and Year select dropdown are too large. Maybe a missing css file

![image](https://cloud.githubusercontent.com/assets/11174016/9138585/0e8fa9a6-3d25-11e5-91c8-16ac1c85a8e7.png)

**Comment by pierr** [comment]
Strange behaviour, seems a regression.

**Comment by durandx** [comment]
We had the same issue : the problem is on the css, in particular the following selector override the correct display of the daterangepicker component :
```
[data-focus="field"][data-mode="edit"][data-domain] input,
[data-focus="field"][data-mode="edit"][data-domain] select {
  width: 250px;
}
```

As a quick fix i had to overload with the following css:

```
[data-focus="field"][data-mode="edit"][data-domain] input,
[data-focus="field"][data-mode="edit"][data-domain] select {
  width: auto;
}

[data-focus="field"][data-mode="edit"][data-domain] > div > input,
[data-focus="field"][data-mode="edit"][data-domain] > div > select {
  width: 250px;
}


[data-focus="field"][data-mode="edit"][data-domain="DO_DATE"] > div > input {
  width: 90px;
  text-align: center;
}
```

**Comment by durandx** [comment]
/* global moment, Focus */

moment.locale("fr");

module.exports = {
  "type": "text",
  "style": "date right",
  'InputComponent': FocusComponents.common.input.date.component,
  options: {
      dateRangePicker: {
          locale: {
              //format: 'DD/MM/YYYY',
              format: moment.localeData().longDateFormat('L')
          },
          minDate: "01/01/1900",
          maxDate: moment().format('L')
      }
  },
  formatter: function dateFormatter(date){
      return moment(date).format('L');
  },
  unformatter: function dateUnformatter(data){
//      data = moment(data).add(2, 'hours');

      return moment(data, moment.localeData().longDateFormat('L')).toISOString();
  }
};

**Comment by pierr** [comment]
@Tommass @Bernardstanislas http://www.gpbl.org/react-day-picker/ ?

**Comment by Tommass** [comment]
Correction ok.
We stay on this of ui-component but in a react version.

**Comment by Bernardstanislas** [comment]
Camoulox
