### ISSUE TITLE
[component][popin] race condition on this.state.opened

### ISSUE THREAD

**Issue by durandx** [KleeGroup/focus-components#179]
When a popin open the folowing test is always true :  
```javascript
            if (this.refs['popin-overlay']) {
                this.state.opened ? this.refs['popin-overlay']._restoreBodyOverflow() : this.refs['popin-overlay']._storeAndHideBodyOverflow();
            }
```
https://github.com/KleeGroup/focus-components/blob/0a0fdf8e10fd3d0d8f2dab1e23d7ac1743d08b4c/src/application/popin/index.js#L141

This prevent to manage the hide/show of the body scrollbar.

<img src=http://ljdchost.com/IoLCKYY.gif></img>

**Comment by pierr** [comment]
@Bernardstanislas Can you check it today ?

**Comment by Bernardstanislas** [comment]
I will !

**Comment by Bernardstanislas** [comment]
Seems like a mistake. I'll fix it today.
