### ISSUE TITLE
[component][list/summary] Conditionnal display for the exportAction

### ISSUE THREAD

**Issue by durandx** [KleeGroup/focus-components#180]
In the list/summary component, please add a flag option (or test that this.props.exportAction != undefined or null) to show/hide the export button

https://github.com/KleeGroup/focus-components/blob/master/src/list/summary/index.js#L44

<img src="http://ljdchost.com/aVIplNn.gif"/>

**Comment by Tommass** [comment]
Ok for next release !

![giphy](https://cloud.githubusercontent.com/assets/5349745/9413207/d5bba514-4830-11e5-9197-29a9170cee9a.gif)
