### ISSUE TITLE
Dropdown : nul value not supported

### ISSUE THREAD

**Issue by remigrange** [KleeGroup/focus-components#183]
Hte drpdwons dispaly a null value with a label "select.Unselected". The problem is the key value is set to undefined in the `selectTextMixin` (method `renderOptions`, `_defineProperty(_ref, _this.props.valueKey, undefined);)`
React ignored the flag value when it renders the component, so the value "select.Unselected" is set to the field.

To fix this
 :
` 
_defineProperty(_ref, _this.props.valueKey, '');
`

**Comment by pierr** [comment]
Ok, i will check it on monday

**Comment by pierr** [comment]
@Bernardstanislas Can you check it, i didn't get the time, and it seems @remigrange 's fix is on babel's generated code.
