### ISSUE TITLE
[validator] Impossible to set a field to blank (undefined)

### ISSUE THREAD

**Issue by durandx** [KleeGroup/focus-components#185]
When a field of a form is set with value and then saved, it is impossible to set its value to blank (undefined). The value is then revert to its old value (before the edit of the field)

<img src="http://ljdchost.com/isThl3q.gif"/>

```
focusjs: 0.8.3
focusjs-components: 0.4.3
```

**Comment by pierr** [comment]
It seems to be a regression with the validation of blank fields...

**Comment by pierr** [comment]
https://github.com/KleeGroup/focus-components/blob/master/src/common/field/mixin/value-behaviour.js#L35

**Comment by pierr** [comment]
Maybe the field should be set to `null`

**Comment by pierr** [comment]
This bug is really easy to reproduce
