### ISSUE TITLE
[component] reference list not working with an integer

### ISSUE THREAD

**Issue by durandx** [KleeGroup/focus-components#186]
When i use the`fieldFor` with a `referenceName`, the component selects the correct option of the select in edit mode, but is blank in consult mode.
The bug is is only present when the code is an integer (when the code is a string the component is working fine).

<img src="http://ljdchost.com/9zjGcCD.gif"/>

```
focusjs: 0.8.3
focusjs-components: 0.4.3
```

**Comment by pierr** [comment]
Maybe the component's value check should cas all int into string.
@Bernardstanislas Any opinion on that ?

**Comment by durandx** [comment]
The component has not the same behavior in edit Mode and in consult mode.

Moreover this component was working fine in the previous version...
