### ISSUE TITLE
[submit button] Cannot change shown label

### ISSUE THREAD

**Issue by DimitriMockelyn** [KleeGroup/focus-components#211]
When a form is submitted, the label shown is always `detail.saved`

**Comment by pierr** [comment]
Can you detail your version of both `Focus` and `FocusComponents`

**Comment by pierr** [comment]
The label is set here : https://github.com/KleeGroup/focus-components/blob/master/src/common/mixin/store-change-behaviour.js#L25 but the message component should translate it: https://github.com/KleeGroup/focus-components/blob/master/src/message/index.js#L66

**Comment by pierr** [comment]
I think it was fixed in #175
