### ISSUE TITLE
[Popin & Cartridge action] cartridge action button above popin

### ISSUE THREAD

**Issue by DimitriMockelyn** [KleeGroup/focus-components#212]
When you scroll on a page that has cartridge actions, and then open a popin, the buttons are shown on top of the popin

![image](https://cloud.githubusercontent.com/assets/5071128/9463267/ddea67e6-4b1b-11e5-8d89-79c31a057da2.png)

**Comment by Tommass** [comment]
Duplicate #459

**Comment by Tommass** [comment]
@pierr why did you close this issue ? is it resolved ?
