### ISSUE TITLE
[List] change default style ?

### ISSUE THREAD

**Issue by DimitriMockelyn** [KleeGroup/focus-components#220]
Is it possible to change default style / data-focus for a selection list ?

**Comment by Bernardstanislas** [comment]
As of today, no. It misses the `stylableMixin`.
All style modification has to be done through CSS as it is right now.

**Comment by pierr** [comment]
You can have a look to this file https://github.com/KleeGroup/focus-components/blob/master/src/list/selection/style/list.scss if you need to customize your CSS.
Use the `[data-focus="selection-list" ]`

**Comment by pierr** [comment]
Why do youo need to change the style?

**Comment by DimitriMockelyn** [comment]
@pierr I wanted to change the top margin or the selection list ( shown before the first line). It's defined in focus-components.css : 

    [data-focus='block'] .block-content [data-focus="selection-list"] {
          margin: 40px 20px; 
    }

Seems like bad luck because only the margin is defined, and that's what I wanted to change ...

**Comment by Bernardstanislas** [comment]
What about writing your own `[data-focus='block'] .block-content [data-focus="selection-list"]` style in your app ? It will override the default component's one.

**Comment by DimitriMockelyn** [comment]
It would work, but I wanted to use it for just one list, and keep the default behaviour for the others. I can work around this problem, but I think the nicest way to do so would have been to specify a different data-focus for my selection list

**Comment by Bernardstanislas** [comment]
I was facing the exact same problem on another project.
What I did was to wrap the target component (`selection-list` in your case) into a parent `div` that would hold a `data-project='myCustomSelector`, then I wrote my SASS as follows :
```css
[data-project='myCustomSelector'] {
    [data-focus='block'] .block-content [data-focus="selection-list"] {
        ...
    }
}
```
