### ISSUE TITLE
Cannot use "referenceBehavior" without including the whole "formMixin"

### ISSUE THREAD

**Issue by JabX** [KleeGroup/focus-components#262]
I'd like to be able to use directly the `referenceBehavior` mixin in any component, without needing the full formMixin package which include a bunch of stuff I don't want (storeBehavior mainly).

In my case I want it in a List/ListPage component, but I suppose it could be used elsewhere.

At the moment the only way to require it is through the mixins array of the `formMixin`, and it's not self-sufficient (it's got at least its init method called in the `formMixin` index.js). I tried but failed to include it that way.

**Comment by pierr** [comment]
I agree on the fact that it shoud be easier to include in any component, and the `formMixin` should not be the only way to achieve it.
However keep in mind what follows;
- Reference mixin is associated with a store `ReferenceStore` and an action which load the reference.
- When the load action is called, the store is updated and the component interested by the references needs to be notified. However this component can be connected to other stores. And a component must update its state from all its connected stores.
- Il will be difficult to separate `referenceBehaviour` from `storeBehaviour`

**Comment by JabX** [comment]
I got a working solution earlier this evening by using both ```referenceBehaviour``` and ```storeBehaviour```, with adding a ```this._loadReference()``` call in my ```componentWillMount()```.

A simple solution could be to simply expose a mixin that does what I just did.

**Comment by pierr** [comment]
That was the purpose of my answer, you need to combine both mixins, they cannot be separated.

**Comment by pierr** [comment]
This will be simplified when we will refactor component's behaviour. I close this issue for now.
