### ISSUE TITLE
[comment/select/checkbox] this.getState will get other checkboxs' state in the same time

### ISSUE THREAD

**Issue by redlapin** [KleeGroup/focus-components#279]
In my programme, I created in a div element  several Checkbox as child elements with different ref values : 'Item', 'Equipment', 'Transfer'.....

When I try to get the selected value of one Checkbox using : this.refs['checkbox ref name'].getValue(), it returns a result that contains the selected values in other checkboxs.

Here is a screen capture for this issue.
![jscode](https://cloud.githubusercontent.com/assets/7668965/9737868/036f96d4-5649-11e5-9e48-9c0cddb7de7f.PNG)
my current context is this.refs['Item'], but this.refs['Item'].getValue() returns a result in which the element "R_EQU_CERTIFICATION_ADD"  shouldn't appear because this element belongs to the element : this.refs['Equipment']

**Comment by Tommass** [comment]
I don't understand this issue...
Please provide more detail.
