### ISSUE TITLE
[Quick search][results] invalid totalcount

### ISSUE THREAD

**Issue by JoanaDalmeida** [KleeGroup/focus-components#301]
The component RESULTS render invalid totalcount when the server returns  groups with no results and one group with results. 
```javascript
// Filter groups with no results
        let resultsMap = omit(this.props.resultsMap, (list) => {
            return 0 === list.length;
        });
        // Get the count for each group
        let groupCounts = this._getGroupCounts(this.props.resultsMap);
        // Check if there is only one group left
        if (1 === keys(resultsMap).length) {
            let key = keys(resultsMap)[0];
            let list = resultsMap[key];
            let count = groupCounts[key].count;
            return this._renderSingleGroup(list, key, count, true);
```

**Comment by pierbrisson** [comment]
:+1:

**Comment by Bernardstanislas** [comment]
In fact, this is a forbidden situation in terms of search pattern. As discussed with @NPi2Loup, if there is only one group with results, then the response shouldn't have the structure of a multiple groups response.
@JoanaDalmeida as you are merging multiple search requests, it is when you do the merging that you should prevent groups from being empty.
