### ISSUE TITLE
[File Upload] implement file upload v1

### ISSUE THREAD

**Issue by Tommass** [KleeGroup/focus-components#311]

**Comment by durandx** [comment]
For Info, we have asked Olivier to develop the File Upload v2

**Comment by pierr** [comment]
What do you mean by FileUploadV2 ? Is it drag and drop file, if so please have a look to https://github.com/KleeGroup/focus-file

**Comment by Tommass** [comment]
File upload done.
Will be delivered the 29th of September.

**Comment by Bernardstanislas** [comment]
Done, see [here](https://www.npmjs.com/package/focus-file)
