### ISSUE TITLE
[Icon] Icon are resolved as text on IE

### ISSUE THREAD

**Issue by durandx** [KleeGroup/focus-components#317]
Icon are resolved as text on IE:
#### Secondary action
![image](https://cloud.githubusercontent.com/assets/9220437/9816603/5265d724-589e-11e5-8144-5e72a732b1d4.png)
:red_circle: Fail
#### Scroll to top:
![image](https://cloud.githubusercontent.com/assets/9220437/9816629/7f2ab482-589e-11e5-8e88-8062555b5bd8.png)
:red_circle: Fail
#### Secondary action
![image](https://cloud.githubusercontent.com/assets/9220437/9816709/ed749f48-589e-11e5-853c-457510255620.png)
:large_orange_diamond: Still a z-index problem with Block component

#### Scroll to top: 
![image](https://cloud.githubusercontent.com/assets/9220437/9816662/ba0359ce-589e-11e5-926d-8310a48550bb.png)
:white_check_mark: Success

**Comment by pierr** [comment]
Maybe a specific font file is missing. IE uses other fonts

**Comment by pierr** [comment]
https://google.github.io/material-design-icons/#icon-images-for-the-web

**Comment by pierr** [comment]
![image](https://cloud.githubusercontent.com/assets/286966/9881279/8d97eb8c-5bcf-11e5-9be1-b4cee96bdaba.png)

**Comment by pierr** [comment]
@Bernardstanislas  @Tommass Any opinion on that?

**Comment by pierr** [comment]
Suggestion create a component Icon for ie9 with a mapping on components

**Comment by Bernardstanislas** [comment]
:+1:

**Comment by durandx** [comment]
For Info, I have the bug with the version 11 of IE

**Comment by pierr** [comment]
Maybe the probem is your server which does not know how to serve this specific font file...
Font awesome provide sevral fonts.

**Comment by pierr** [comment]
Maybe you can check https://github.com/google/material-design-icons/tree/master/iconfont which should be in the associated `package.json` file

**Comment by durandx** [comment]
https://github.com/google/material-design-icons/issues/205

**Comment by pierr** [comment]
`<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">`

**Comment by pierr** [comment]
This works on ie

**Comment by durandx** [comment]
Was working in our localhost and recette environment.
Still working in localhost but not in recette environement.

**Comment by pierr** [comment]
@Jerom138 maybe it is the same problem for old FF

**Comment by pierr** [comment]
@durandx Google has indeed published a new mdl lite version, we didn't upgrade in foocus components.

**Comment by pierr** [comment]
@pierbrisson

**Comment by Pandakls** [comment]
Got the issue on both IE and FF, what do i have to do to fix this ?

**Comment by xuaveneg** [comment]
Hi, I just updated focus-core and focus-components, and my icons are still not displayed on IE in recette environment (it works in localhost).

**Comment by Tommass** [comment]
did you add this line in the header of your index.html or JSP file  ?

```html
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
```

**Comment by xuaveneg** [comment]
Sorry, now it's resolved.
The problem was that I didn't add `material-design-icons-iconfont` for IE compatibility.

**Comment by durandx** [comment]
Please can you explain what did you do in detail ?

**Comment by xuaveneg** [comment]
I added the node.js module `material-design-icon-iconfont` to my project.
I imported the module in a js file with

```
import 'material-design-icons-iconfont/dist/material-design-icons.scss';
```

and then it worked.

**Comment by durandx** [comment]
We have switched to webpack (from brunch) 2 or 3 month ago, and the font is now correctly inlined in the css along with some localhost:3000/xx.eot url. With Chrome and Firefox, the inlined is taken, but with IE11 (and 10) the font use the localhost:3000 url.
@xuaveneg Does your solution is working with IE 11 ?

**Comment by pierr** [comment]
@durandx I helped @JRLK with a similar issue last week it was due to webpack config. 
Maybe @JRLK can comment the solution on this issue.

**Comment by JRLK** [comment]
@pierr We work only with Chrome not with IE.
The issue we looked together was about absolute and relative path to access to the fonts.
I don't think the issue @durandx is talking about is the same.

**Comment by durandx** [comment]
Linked to : https://github.com/KleeGroup/focus-components/issues/1125

**Comment by durandx** [comment]
Solution here : https://github.com/KleeGroup/webpack-focus/issues/9
