### ISSUE TITLE
Forms: checkboxes are not rendered well

### ISSUE THREAD

**Issue by fredmaistre** [KleeGroup/focus-components#324]
![image](https://cloud.githubusercontent.com/assets/14274128/9849159/855c7948-5ae8-11e5-98fb-e8e7f8fb2f61.png)

**Comment by Tommass** [comment]
please declare domain YES / NO like this :

'''javascript
    'DO_OUI_NON': {
        SelectComponent: FocusComponents.common.select.radio.component,
        refContainer: {yesNoList: [{code: true, label: "select.yes"}, {code: false, label: "select.no"}]},
        listName: 'yesNoList'
    }
'''
