### ISSUE TITLE
[dropdown] Wrong default icon for secondary actions

### ISSUE THREAD

**Issue by pierr** [KleeGroup/focus-components#326]
Replace https://github.com/KleeGroup/focus-components/blob/develop/src/common/select-action/index.js#L21 by `more_vert`
and type should be `button`

**Comment by pierr** [comment]
https://github.com/KleeGroup/focus-components/blob/develop/src/list/action-contextual/index.js#L69 It seems the component is not in the props

**Comment by pierr** [comment]
The this is not bined into the result.

**Comment by pierr** [comment]
Just add the this as fourth argument

**Comment by JRLK** [comment]
https://github.com/KleeGroup/focus-components/blob/develop/src/list/action-contextual/index.js#L74

there isn't icon for the primary actions

**Comment by pierr** [comment]
I think the previous pull request #327 also fix this issue
