### ISSUE TITLE
[ContextualAction][Icon][label] Label in contextual action with shape icon is not rendered well

### ISSUE THREAD

**Issue by JRLK** [KleeGroup/focus-components#328]
![image](https://cloud.githubusercontent.com/assets/13674778/9852255/94a708a4-5afd-11e5-8eae-2d8b5a7e294a.png)

This is a material design issue.
It can be good if the label is convert like a tooltip on mouse over.

**Comment by pierr** [comment]
The problem is in the button, it should not render any label when the type is icon or fab

**Comment by pierr** [comment]
Please create another issue for the tooltip
