### ISSUE TITLE
Click on "group by" on advanced search page

### ISSUE THREAD

**Issue by DimitriMockelyn** [KleeGroup/focus-components#331]
When grouping search results by facets, it's possible to click on "group by", and it raises an error

![image](https://cloud.githubusercontent.com/assets/5071128/9853748/9463980a-5b05-11e5-9bc3-fe872353826f.png)

**Comment by sgoretti** [comment]
:+1:

**Comment by Bernardstanislas** [comment]
That was silently fixed in a version prior to 0.7.2, sorry for the lack of communication on this one.

**Comment by Bernardstanislas** [comment]
Sorry this is not corrected yet, I need to investigate to find out where the correction was lost.

**Comment by Bernardstanislas** [comment]
@sgoretti, I have seen with @cbarnay on his app that this was solved, can you confirm it is solved for you ? I guess you have the same basecode

**Comment by sgoretti** [comment]
Yup, fixed for me as well

**Comment by Bernardstanislas** [comment]
Perfect !
