### ISSUE TITLE
[select][form][reference list] the value is not translated when the code is an id in the reference list

### ISSUE THREAD

**Issue by JRLK** [KleeGroup/focus-components#342]
![image](https://cloud.githubusercontent.com/assets/13674778/9875499/be413f8e-5bae-11e5-8cdc-7c03089bcc56.png)

The reference list looks like :
```json
[
  {"code":"3","label":"Autre type de vente","value":"Autre type de vente"},
  {"code":"2","label":"Biomasse","value":"Biomasse"},
  {"code":"1","label":"Vente de gaz","value":"Vente de gaz"}
]
```

**Comment by Tommass** [comment]
Can you provide us more precision ?
can you reformulate your issue ?

**Comment by Tommass** [comment]
Please try this way:

```json
[
  {"code":3,"label":"Autre type de vente","value":"Autre type de vente"},
  {"code":2,"label":"Biomasse","value":"Biomasse"},
  {"code":1,"label":"Vente de gaz","value":"Vente de gaz"}
]
```

**Comment by JRLK** [comment]
I tried with the list as you suggested and it works.
We modified the server service which provide the list to return `code` as `object` and not as a `string` anymore.
