### ISSUE TITLE
[search][operationList] icons are not displayed.

### ISSUE THREAD

**Issue by JoanaDalmeida** [KleeGroup/focus-components#343]
the operation.icon option is not used in action-contextual component 

        if (1 === operation.priority) {
                primaryActions.push(
                    <this.props.buttonComponent
                        handleOnClick={this._handleAction(key)}
                        key={key}
                        label={operation.label}
                        shape={operation.style.shape || 'icon'}
                        style={operation.style || {}}
                        type='button'
                        {...this.props}
                        />
                );

**Comment by pierr** [comment]
Rename your icons using https://www.google.com/design/icons/ in the operation List

**Comment by Bernardstanislas** [comment]
I think that the icons should be picked in the `operation` object instead of the `props`.
I take it
