### ISSUE TITLE
[select][form] selectFor is rendered as an input text

### ISSUE THREAD

**Issue by JRLK** [KleeGroup/focus-components#344]
![image](https://cloud.githubusercontent.com/assets/13674778/9875943/9ac5a0aa-5bb2-11e5-943c-1e8ad42f2ad1.png)

```javascript
    select: function select() {
        var value = this.state.value;

        var buildedSelectProps = assign({}, this.props, {
            value: value,
            style: this._buildStyle(),
            onChange: this.onInputChange,
            ref: 'input'
        });
        return React.createElement(this.props.InputComponent, buildedSelectProps);
    },
```
`this.props.InputComponent` has changed from `this.props.SelectComponent`, but If we use `SelectComponent` instead of `InputComponent`, Radio is rendered as a Select classic

**Comment by pierr** [comment]
@Tommass replace InputComponent with SelectComponent
