### ISSUE TITLE
[i18n] this.i18n does not take a property "style"

### ISSUE THREAD

**Issue by JRLK** [KleeGroup/focus-components#345]
![image](https://cloud.githubusercontent.com/assets/13674778/9877463/43a25fc4-5bbd-11e5-8173-ab483f0070f8.png)

**Comment by Bernardstanislas** [comment]
What do you mean by "style" ? Isn't it cleaner to wrap it in a container that would hold the style ?
```javascript
<span className='my-style-holder'>{this.i18n('your.key')}</span>
```

**Comment by pierr** [comment]
I close the issue, please reopen it if necessary

**Comment by JRLK** [comment]
Yes it's much better and cleaner.
Thanks :+1:
