### ISSUE TITLE
[form mixin] this.listfor and this.tableFor ont working

### ISSUE THREAD

**Issue by JoanaDalmeida** [KleeGroup/focus-components#346]
Errors while using this.listFor and this.tableFor 

Uncaught TypeError: data.map is not a function
Uncaught TypeError: Cannot read property '_currentElement' of null

**Comment by pierr** [comment]
Please provide some context

**Comment by JoanaDalmeida** [comment]
![image](https://cloud.githubusercontent.com/assets/3300779/9878947/7891eb34-5bc5-11e5-8cea-3efdc8a4cfc7.png)

**Comment by pierr** [comment]
As seen together it is related to the new version of focus https://github.com/KleeGroup/focus/releases/tag/v0.10.1 

All the actions which load data should add  the config param `shouldDumpStoreOnActionCall ` as an example
```javascript
actionBuilder({
    service: yourService, 
    status: 'loaded',
     shouldDumpStoreOnActionCall : true
})
```

**Comment by pierr** [comment]
@JoanaDalmeida can you add an action example, @remigrange  can you check in your project @durandx

**Comment by JoanaDalmeida** [comment]
```javascript
 {       load: actionBuilder({
            service: equipmentServices.getEquipmentById,
            node: 'equipment',
            status: 'loaded',
            shouldDumpStoreOnActionCall: true
        })
}
```
