### ISSUE TITLE
update navigator at the left side of one page

### ISSUE THREAD

**Issue by redlapin** [KleeGroup/focus-components#365]
Please refer to the attached screen capture.
![capture](https://cloud.githubusercontent.com/assets/7668965/9910812/525451fc-5c9f-11e5-89b1-9d4ea780cef0.PNG)

the Navigator of the page at the left side doesn't update once the data(Item) are loaded: there are 8 collections but the Navigator display (0).  the module block is in the right part but doesn't appear in the Navigator section.

**Comment by Tommass** [comment]
duplicated issue #309 & #316
