### ISSUE TITLE
[form mixin] [fieldFor] render wrong value.

### ISSUE THREAD

**Issue by JoanaDalmeida** [KleeGroup/focus-components#367]
the display text component translate the value before render it.

![image](https://cloud.githubusercontent.com/assets/3300779/9912480/20f96350-5ca8-11e5-99c2-e98d40e9a645.png)

```javascript
    /**
    * Render the value.
    * @return {string} The formated value.
    */
    renderValue(){
        const {formatter, value} = this.props;
        const translatedValue = value ? this.i18n(value) : value;
        return formatter(translatedValue);
    }
```

**Comment by pierr** [comment]
@Tommass it seems related to https://github.com/KleeGroup/focus-components/pull/357
