### ISSUE TITLE
[IE][search and detail] When going on detail after a research, and error is raised on IE

### ISSUE THREAD

**Issue by DimitriMockelyn** [KleeGroup/focus-components#368]
If you search for somehting, and then go on a detail screen, an error is raised on Internet Explorer (tested on lastest IE version)

It's happening when you search with an empty query

![image](https://cloud.githubusercontent.com/assets/5071128/9928902/94d34382-5d29-11e5-95c0-9235ac003a48.png)

![image](https://cloud.githubusercontent.com/assets/5071128/9928916/b9fdb6d8-5d29-11e5-9e2f-e36d0ab565bb.png)

**Comment by pierr** [comment]
Coud you provide a stack trace from IE devtools ?

**Comment by pierr** [comment]
IE11?

**Comment by pierr** [comment]
@DimitriMockelyn

**Comment by DimitriMockelyn** [comment]
Anonymous function [Ligne : 103656, col : 13], vendor.js
    Anonymous function [Ligne : 103038, col : 13], vendor.js
    Anonymous function [Ligne : 103037, col : 9], vendor.js
    _broadcastQueryChange [Ligne : 103655, col : 9], vendor.js
    _onInputChange [Ligne : 103664, col : 13], vendor.js
    _handleChange [Ligne : 8497, col : 7], vendor.js
    executeDispatch [Ligne : 3414, col : 3], vendor.js
    forEachEventDispatch [Ligne : 3402, col : 5], vendor.js
    executeDispatchesInOrder [Ligne : 3423, col : 3], vendor.js
    executeDispatchesAndRelease [Ligne : 2796, col : 5], vendor.js
    forEachAccumulated [Ligne : 17717, col : 5], vendor.js
    EventPluginHub.processEventQueue [Ligne : 3003, col : 5], vendor.js

This is IE11 and focus-components 0.5.1-5, I don't know if this is fixed in the current version

**Comment by Bernardstanislas** [comment]
Can you please try with [version 0.7.0](https://github.com/KleeGroup/focus-components/releases/tag/v0.7.0) ? If still an issue, please reopen it.
