### ISSUE TITLE
[list][selection] Broken getSelectedItems()

### ISSUE THREAD

**Issue by redlapin** [KleeGroup/focus-components#370]
the methode getSelectedItems() doesn't return the selected items in the list.

possible error:

 var lineValue = this.refs[lineName].getValue();
            if (lineValue.isSelected) {

To get the right selected status, use "this.refs[lineName].state.isSelected" will return the right selected status.

**Comment by Bernardstanislas** [comment]
As seen with you, you should hold the selection state in your caller component.
Closing this as it is solved.
