### ISSUE TITLE
Lists in form are not displayed as dropdown if there is no value in the list

### ISSUE THREAD

**Issue by s-ham** [KleeGroup/focus-components#376]
Type de poste has no entry but should be a dropdonw list
![image](https://cloud.githubusercontent.com/assets/14196527/9939230/8104fb58-5d69-11e5-90fe-255ea849eb22.png)

**Comment by pierr** [comment]
There is certainly a problem with this case but is it useful to have an empty dropdown ? This case should not happen or if it happens , it should display that there is a problem because the list is empty.

**Comment by pierr** [comment]
@Tommass what's your opinion?

**Comment by Tommass** [comment]
i think by default we should display an empty list.
I am ok with Sarah issue.

**Comment by Tommass** [comment]
@pierr to check together
