### ISSUE TITLE
When adding a new object, the info of the last consulted object are displayed instead having empty fields

### ISSUE THREAD

**Issue by s-ham** [KleeGroup/focus-components#377]
I consult an object, then go back to the list and click to create a new one. The fields contain the values of the previous consulted object.

**Comment by pierr** [comment]
That's because the component is not clean from the parent's view.
You certainly need a `{<Popin>{isCreate && <myDetail />}</Popin>}`

**Comment by JRLK** [comment]
You have to clean the store or at least a node of the store when you access the creation page.
To do so, you can use the dispatcher in the router to purge the store before being routed to the page.

In our case we do it like this :
```javascript
    routes: {
        'contrat/createFirstStep': 'contratCreateFirstStep',
    },
    contratCreateFirstStep() {
        storeHelper.purgeNode(['infosGenerales', 'infosComplementaires']);
        this._pageContent(ContratCreateFirstStepView);
     },
```
We define the method which purge nodes in an helper.

```javascript
function purgeNode(nodeToClean){
    let dispatchData = {};
    if(Array.isArray(nodeToClean)){
        nodeToClean.forEach(
            function populateData(name){
                dispatchData[name] = {};
            }
        );
    }else{
        dispatchData[nodeToClean] = {};
    }
    Focus.dispatcher.handleViewAction({
        data: dispatchData, type: 'update'
    });
}
```

**Comment by pierr** [comment]
The problem in your case is that you don't have a load action (which clear the store) when there is a detail.
Maybe we should add something to ease this.
@JRLK should work in most cases but it is not the best. (As the store clean is asynchronous)
