### ISSUE TITLE
[content-actions] iconLibrary not working 

### ISSUE THREAD

**Issue by JoanaDalmeida** [KleeGroup/focus-components#384]
```javascript
/** @inheriteddoc */
    render() {
        const {actions} = this.state;
        return (
            <div className={this._getStyleClassName()} data-focus='content-actions'>
                {actions.primary.map((primary)=>{
                    return (
                        <Button handleOnClick={primary.action} icon={primary.icon} label={primary.label} shape='fab' style={{className: primary.className}} type='button'/>
                    );
                })}
                <Dropdown iconProps={{name: 'more_vert'}} operationList={actions.secondary} shape='fab'/>
            </div>
        );
    }
```

**Comment by Tommass** [comment]
What is not working ?
Can you describe your issue ?
Can you add a screen shot ?

Thanks

**Comment by JoanaDalmeida** [comment]
the iconLibrary prop is not working for actions defined on the top bar (detail page, method cartridgeConfiguration).

![image](https://cloud.githubusercontent.com/assets/3300779/10160020/8557dd16-669b-11e5-848b-39dd8e9f0acf.png)

**Comment by pierr** [comment]
@JoanaDalmeida Can you provide your button's configuration from the cartridge ?

**Comment by pierr** [comment]
As it is a duplicate issue I close it, @JoanaDalmeida don't hesitate to reopen it if it is not solved.
