### ISSUE TITLE
regression selection List Focus components v0.6.1-3 

### ISSUE THREAD

**Issue by a-peyre** [KleeGroup/focus-components#392]
On linkit I had a screen using focus components selection list.

The list still displays, but the buttons that are supposed to appear on mouseover remain hidden.

I checked in the generated code, and saw the following:

```jsx
  <buttoncomponent label="start manually" shape="raised" style=" border-color:black; " data="[object Object]" offset="250" data-reactid=".1.1.0.0:$15.2.0.0.$0"></buttoncomponent>
```

while they should be created as buttons

**Comment by pierr** [comment]
I think this was fixed in version `0.6.1-5` could you try an update with `npm insatll focusjs-components@0.6.1-5`

**Comment by a-peyre** [comment]
I did so, but the problem persists

**Comment by sgoretti** [comment]
I guess it's normal, need to check with the Trackit team if we go full material on this or if we stick to our rectangular buttons (in which case either css overwrite ou button component overwrite)

**Comment by pierr** [comment]
I close the issues please reopen it if you need to.
