### ISSUE TITLE
[error] When the field is required the error is not displayed

### ISSUE THREAD

**Issue by pierr** [KleeGroup/focus-components#396]
MDL uses 
http://www.w3.org/TR/html5/forms.html#the-required-attribute as explains in their doc https://github.com/google/material-design-lite/tree/master/src/textfield maybe we should add a `required` attribute to the input `text`

**Comment by pierr** [comment]
@Tommass @durandx @JoanaDalmeida

**Comment by durandx** [comment]
jawohl
