### ISSUE TITLE
[search-bar] placeholder not translated even if translation available (v0.6.1-5)

### ISSUE THREAD

**Issue by sgoretti** [KleeGroup/focus-components#400]
The placeholder resource is never translated:
![image](https://cloud.githubusercontent.com/assets/14293391/10023195/12de40f8-6151-11e5-8924-871186851826.png)

As you can see, it's in the placeholder of the input tag
![image](https://cloud.githubusercontent.com/assets/14293391/10023219/3911bc32-6151-11e5-82c8-375f657d4c8c.png)

while it's not supposed to be, if we look at the source code
![image](https://cloud.githubusercontent.com/assets/14293391/10023262/79e83344-6151-11e5-84cd-c3ebb137ec12.png)
probably due to the fact that the placeholder is a prop of the Input, thus rendered in the input untranslated.

**Comment by Tommass** [comment]
duplicate #448
