### ISSUE TITLE
[search-bar-scope] Scopes not opening (v0.6.1-5)

### ISSUE THREAD

**Issue by sgoretti** [KleeGroup/focus-components#401]
Don't know if I did anything wrong, but scopes are in the source code of my page, but never appearing when I click on the icon.
![image](https://cloud.githubusercontent.com/assets/14293391/10023345/eeeb482a-6151-11e5-9dfb-43b631c628b0.png)

![image](https://cloud.githubusercontent.com/assets/14293391/10023365/0a47a08c-6152-11e5-8691-c682b1984ed8.png)

The arrow is turning upside-down but nothing ever appears under the box.

**Comment by pierr** [comment]
On other projects, there is a similiar issue but not on all pages.
Can you please add a context to this.
Maybe @JoanaDalmeida  can describe her problems.

**Comment by pierbrisson** [comment]
on TrackIt, scope dropdown doesn't work at first if used in homepage header search bar or quick search
However, after going on an object's detail page, then the quick search's scope dropdown works correctly.

**Comment by pierr** [comment]
Fixed in https://github.com/KleeGroup/focus-components/pull/482
