### ISSUE TITLE
[detail] Only 2 items are displayed on the Menu item (regression) 0.6.1-5 and 0.6.1-6

### ISSUE THREAD

**Issue by durandx** [KleeGroup/focus-components#402]
I've switched to "focusjs": "0.10.2" and i have now a regression on the Menu item : not all block are displayed.

focusjs: 0.10.2
focusjs-components: 0.6.1-5 and 0.6.1-6

**Comment by pierr** [comment]
Did you update all your icons using material icons?

**Comment by durandx** [comment]
I mean the detail menu. In which is it related to icons ?

![image](https://cloud.githubusercontent.com/assets/9220437/10068150/4be5f8ee-62a2-11e5-8f14-f7d51876274b.png)

![image](https://cloud.githubusercontent.com/assets/9220437/10068186/a0d08bda-62a2-11e5-9cb1-c5630620190e.png)

**Comment by pierr** [comment]
Ok i misunderstand your point. 
Is it on all the pages? I will check with other projects.

**Comment by durandx** [comment]
FI, I append block dynamically after.

**Comment by JulienGard** [comment]
:+1:
