### ISSUE TITLE
[Advancedsearch][Facets & Groups] sort all wrong when more than 6 items (v0.6.1-5)

### ISSUE THREAD

**Issue by sgoretti** [KleeGroup/focus-components#410]
When using the AdvancedSearch as is, I have some order issue with facets and groups.

For example, this is the Json I get (in the response tab of the webservice call)

![image](https://cloud.githubusercontent.com/assets/14293391/10048784/e2b21e58-6214-11e5-8fcd-f4d07252073e.png)

As you can see, the order is fine for both facets.
And this is the page: 

![image](https://cloud.githubusercontent.com/assets/14293391/10048834/0e780eda-6215-11e5-9834-1b0059df348b.png)

As you can see the facet with 6 items is ordered correctly, but the facet with more than 6 items has had its order changed. This is the same for all facets with enough values to need the "view all" link.

Remarkably, this order issue can also be found in the groups, where the exact same wrong (or right if less than 6 groups) order can be found.

**Comment by pierr** [comment]
Maybe there is a missing sort at some point.
Needs to be investigated.

**Comment by sgoretti** [comment]
Partial fix:

``` JavaScript
_sortPropsByKey: function(obj) {
		let sortedProps = [];
		for (var prop in obj) {
			if (obj.hasOwnProperty(prop)) {
				sortedProps.push({
					'key': prop,
					'value': obj[prop]
				});
			}
		}
		sortedProps.sort(function(a, b) { return a.key.toLowerCase().localeCompare(b.key.toLowerCase())});
		for (var i = 0; i < sortedProps.length ; i++) {
			delete obj[sortedProps[i].key]
		}
		for (var i = 0; i < sortedProps.length ; i++) {
			obj[sortedProps[i].key] = sortedProps[i].value; 
		}
	},
	_sortResults: function(result) {
		if (result != undefined) {
			this._sortPropsByKey(result.groups);
			this._sortPropsByKey(result.facets);
			for (var facet in result.facets) {
				this._sortPropsByKey(result.facets[facet]);
			}
		}        	
	},
    unscoped(ajaxConfig) {
        return fetch(URL.search.searchByScope(ajaxConfig))
        	.then((result) => {
        			this._sortResults(result);
        			return result;
        		}, 
        		(result) => {
        			console.log('Search failure, please search another term');
        		});;
    },
    scoped(ajaxConfig) {
        return fetch(URL.search.searchByScope(ajaxConfig))
        	.then((result) => {
    				this._sortResults(result);  			
        			return result;
        		}, 
        		(result) => {
        			console.log('Search failure, please search another term');
        		});
    }
```

Please note:
 - with this, facets are ordered alphabetically (better than an order that changes randomly)
 - facets values are ordered alphabetically
But:
the bug when there's more than 10 items (when the view all link appears) still exists (haven't had the time to look at it).

FYI, I think it's be best to read the facet config of these facets with an order property added rather than an alphabetical sort (but I was quite in a hurry so I didn't do it). Plus a valueOrder property allowing to choose between alphabetical and count.. Might do it if it's not done in more than a week or so, but I don't have the time at the moment.

**Comment by pierr** [comment]
@sgoretti Is it fixed with the new Vertigo Search API ?
cc @NPi2Loup 
Please reopen it if it is not the case.
