### ISSUE TITLE
Autocomplete : selectionHandler get undefined data

### ISSUE THREAD

**Issue by remigrange** [KleeGroup/focus-components#413]
1 - Sometimes, the selectionHandler function get an undefined input parameter insteadof  data
2 - Always show drop down (insteadof show olnly object with matching text)
3 - The search is triggered only after the 4th click instead after the 4th character

**Comment by Bernardstanislas** [comment]
@remigrange Just so that you can confirm, I will add a `alwaysDisplaySuggestions` prop that will enable the behaviour you asked for

Note to myself : use `filter` prop as seen [there](https://leaverou.github.io/awesomplete/)
