### ISSUE TITLE
[definition formatter] Allow disabling of the formatter in edit mode

### ISSUE THREAD

**Issue by JabX** [KleeGroup/focus-components#414]
When a field as a domain that has a formatter (my exemple is a currency field), the formatter is applied in both edit and consult. In particular, it is applied at each change in the input field, resulting in an erratic behavior.

It would be great to at least have access to the current mode in the formatter function.

For reference, I partially solved the problem like this :
```javascript
formatter(montant) {
    if(!(this && this.isEdit)) {
        return numeral(montant).format('0,0[.]00 $');
    }
}
```
(```this``` is defined only on the onChange input event)

**Comment by pierr** [comment]
As seen together, stay with this solution for now, but we will add the mode as second argument in the function or a props on the component to know if the formatter should be applied in `edit mode`.

**Comment by pierr** [comment]
As said in the associated PR, the formatter signature will now be `function(value, options){ /**options = {isEdit: true/false}; and // your code*/ return value;}`, this solution may include more code into the domains, but is is the easiest way to do what you want.
