### ISSUE TITLE
[Facets] add config  options for sorting values

### ISSUE THREAD

**Issue by sgoretti** [KleeGroup/focus-components#415]
I think it would be interesting in the facet configuration (such as openedFacetList) to have the possibility to determine whether the facet values are sorted by count or by alphabetical order.
(Yes, at the moment, the sort is done by count automatically by Elastic Search and I have a running bug on it since the order is scrambled between json reception and display)

While sorting by count seems obvious (showing the more important group first), it starts losing sense as soon as the number of values grow.
For example In Linkit, having facet by countries. It doesn't really make sense to favor countries with more jobs (for example), yet it makes sense to choose the country in an alphabetically-sorted list.

**Comment by pierbrisson** [comment]
:+1:

**Comment by TomGallon** [comment]
This will be possible with http://github.com/get-focus/focus-search lib
