### ISSUE TITLE
[Autocomplete] In edit mode, the value isn't always resolved

### ISSUE THREAD

**Issue by JabX** [KleeGroup/focus-components#420]
And the code is displayed instead.
I think the only case where it works in when I just saved an edit and clicked on edit again.

**Comment by pierr** [comment]
Can you provide some context, what's your key,what's your value and what are your values.
Are you familiar with `valueKey` and `labelKey` props.

**Comment by JabX** [comment]
I'm using the component in the most basic way. It works fine so I suppose my valueKey and labelKey are correct. The context is simple : I have a Block of fields (with a formMixin), the autocompleteFor field is correctly displayed (the value is shown) in consult mode. Then I click edit and the value disappears and all I have is the code.

I had already notified @Bernardstanislas about it and he told me he'd look into it.
