### ISSUE TITLE
[changeBehavior] onChange isn't reliably triggered

### ISSUE THREAD

**Issue by JabX** [KleeGroup/focus-components#421]
Sometimes, when I trigger a save event, the onChange event isn't properly fired.
Probably happens 1 time out of 8-10, and probably never while debugging.
Since it's not reliably triggered, I cannot then also reliably reproduce it.

**Comment by pierr** [comment]
Please provide condext and a specific use case.
How do you trigger this event (manually or on a click somewhere)

**Comment by JabX** [comment]
It happens when I manually trigger a save action in a form (with a custom button).

**Comment by pierr** [comment]
@JabX What is the type of your button in these cases ? Do you pass in onClick or in the form's submit method?

**Comment by JabX** [comment]
It's simply an onClick method.

**Comment by JabX** [comment]
Turns out it doesn't have anything to do with afterChange, it was a setState being applied after the afterChange event that caused my unexpected behaviour.
