### ISSUE TITLE
[Advancedsearch][Group] Group title is not displayed

### ISSUE THREAD

**Issue by pierbrisson** [KleeGroup/focus-components#426]
When grouping results in the advanced search, each group's title/label and amount isn't displayed

![image](https://cloud.githubusercontent.com/assets/8983628/10107925/784b1078-63be-11e5-9e6b-8f8b8909e5b8.png)

**Comment by sgoretti** [comment]
Had it on Linkit as well, turns out that the Title component has had its attributes changed: 'title' is no longer used and you should use 'label' instead.

**Comment by pierr** [comment]
Thanks for the reply , @pierbrisson I close the issue, reopen it if @sebgoretti 'a answer does not solve your issue.
