### ISSUE TITLE
[Form][validation] Domain validation returns the same translationKey whatever the error: domain.validation.string

### ISSUE THREAD

**Issue by JRLK** [KleeGroup/focus-components#433]
Focus-components :  v0.6.2
Tested with minLenght and maxLength

![image](https://cloud.githubusercontent.com/assets/13674778/10136877/17d03026-65f7-11e5-9d2a-271742a7b4da.png)
![image](https://cloud.githubusercontent.com/assets/13674778/10136889/275cecfa-65f7-11e5-8ec7-0c976ff55ac9.png)

**Comment by pierr** [comment]
You can customize the message in your domain with the configuration property: `translationKey`

**Comment by pierr** [comment]
You can even customize the fieldName in yoyur message `{translationKey: 'My awesome message for the property : __fieldName__'}`
