### ISSUE TITLE
[input][date]Improve action on date input events

### ISSUE THREAD

**Issue by ursuandrei42** [KleeGroup/focus-components#434]
I need to implement the possibility that the date input to accept also the format DDMMYYYY.

In file https://github.com/KleeGroup/focus-components/blob/develop/src/common/input/date/index.js
there is the method 
```
 _onInputChange({target: {value: inputDate}}) {
        if (moment(inputDate).isValid()) {
            this.setState({inputDate, rawDate: inputDate});
        } else {
            this.setState({inputDate});
        }
    },
```
I would like that the inputDate to be converted to DD/MM/YYYY if it has DDMMYYYY format in _onInputChange method
or the possibility to pass a prop with my format,
or any other solution that will help me solve this feature.

**Comment by Bernardstanislas** [comment]
That will be fixed in the upcoming release, 0.7.0.
You will need to specify a `locale` in your domain, as seen [here](https://github.com/KleeGroup/focus-components/blob/f59baf17a61aea4d7e0d3ac0e664d58aa851be64/src/common/form/example/index.js#L83)
