### ISSUE TITLE
[autocomplete] No error message

### ISSUE THREAD

**Issue by JRLK** [KleeGroup/focus-components#441]
![image](https://cloud.githubusercontent.com/assets/13674778/10160226/7cd5bb1c-669c-11e5-86ca-afd6cd9a1e30.png)

focus-component : 0.6.2

**Comment by Bernardstanislas** [comment]
Before I look at what's wrong, can you please do a quick check and tel me whether the error is present in the DOM but not displayed, or not present in the DOM at all.
Thank you
