### ISSUE TITLE
[Form][datePicker] Date initialized with today date and value set is lost after validation failure

### ISSUE THREAD

**Issue by JRLK** [KleeGroup/focus-components#442]
![datepicker_initialization](https://cloud.githubusercontent.com/assets/13674778/10160614/f4536336-669e-11e5-95dc-5b70f6a49863.gif)

1. Change something to render the other blocks
2. The dates are already set with today date
3. Set a new date
4. Submit the form
5. It's normal to have errors
6. The value of the date is back to its previous value

focus-components : v0.6.2

**Comment by pierr** [comment]
Try to replace in the date component: 

```
    getInitialState() {
        const {value} = this.props;
        const momentValue = moment(value);
        const isValidAndNotNull = momentValue.isValid && !_.isUndefined(value) && !_.isNull(value);
        const rawDate = isValidAndNotNull ? value : null;
        const inputDate = isValidAndNotNull ? this.getFormattedDate(value) : '';
        return {inputDate, rawDate};
    }
```

**Comment by JRLK** [comment]
It doesn't work because in the props the value is already defined with the current date.
Where can I find the props definition?

**Comment by JRLK** [comment]
I followed the Call Stack up to the function `mountComponent` which is in React part.
```javascript
 var publicProps = this._processProps(this._currentElement.props);
```
`this._currentElement.props.value` is set to the current date.
