### ISSUE TITLE
[Radio] Value is not set when the button are clicked

### ISSUE THREAD

**Issue by JRLK** [KleeGroup/focus-components#443]
![radio_button_no_value](https://cloud.githubusercontent.com/assets/13674778/10162910/1134a1c6-66af-11e5-8992-539ed413ff3c.gif)

focus-components : v0.6.2

The `onChange` is fired but the value isn't updated.

**Comment by Tommass** [comment]
That's normal.

When you define an onChange function, you have to handle the state of the component.

Please refer to the source code: 
https://github.com/KleeGroup/focus-components/blob/develop/src/common/select/checkbox/index.js#L61

```javascript
 /**
     * Handle a change of value.
     * @param  {[type]} key       the key
     * @param  {[type]} newStatus the new status
     */
    _handleCheckboxChange(key, newStatus) {
        if(this.props.onChange) {
            this.props.onChange(key, newStatus);
            return;
        }
        const selectedValues = this.state.selectedValues;
        if(newStatus) {
            selectedValues.push(key);
        } else {
            pull(selectedValues, key);
        }
        this.setState({value: selectedValues});
    },
```

**Comment by JRLK** [comment]
Nothing happen when I remove the `onChange` property

**Comment by JRLK** [comment]
`_handleCheckboxChange(key, newStatus)` is never called
`_onInputChange` is called instead

**Comment by pierr** [comment]
The problem is the `onChange` function  is given by the field for to the select radio
