### ISSUE TITLE
[FocusComponents.common.input.date.component] unformatter method is never called with direct input

### ISSUE THREAD

**Issue by durandx** [KleeGroup/focus-components#452]
The unformatter method of domain is never called when I directly enter a date in the input (without picking a date in the calendar popin).

In consequence in our special setup (french locale) : if I enter the date in the input (01/08/1990), the date is then interpretted in MM/DD/YYYY format (08/01/1990). If I choose the same date in the picker it is correctly set to DD/MM/YYYY (01/08/1990) ...

**Comment by JulienGard** [comment]
:+1:
