### ISSUE TITLE
Can't save modification in a form using Internet Explorer

### ISSUE THREAD

**Issue by staleb** [KleeGroup/focus-components#455]
Tested with IE 10.

Using IE, if I post a form, I get a "save successful" message, but nothing is sent to the server.
Everything works fine on Chrome & FF.

I don't know if it's related, but when viewing the form, the error below occurs in the vendor.js file, on this line of code : 
_this.props.action.updateProperties({
     query: React.findDOMNode(_this.refs.query).value
});
![ref null](https://cloud.githubusercontent.com/assets/1292681/9734915/2a2f4b14-5637-11e5-990b-0ce6b1c25d88.PNG)

Update : Data is actually being saved to database, but the browser is loading the old version of the page.

**Comment by pierr** [comment]
Which version do you use? Other projects don't have this issue. Reopen it if still an issue after updating.
