### ISSUE TITLE
[AdvancedSearch][Question] trigger search from URL

### ISSUE THREAD

**Issue by sgoretti** [KleeGroup/focus-components#456]
Is there a way to define the scope and query to the advanced search component from the url (something like /#search/advancer/scope/query)
I can send the scope and query through the router, but once on my page I have no clue what to do with them.

Would be useful in Linkit since we have 2 apps in parallel and a menu looking the same with a search in it. So the old app should be able to trigger a search in the new app.

**Comment by pierr** [comment]
You need to set the `query` or any parameter you want in the global search store.
See `Focus.store.search...`, in order to see the name of the nodes.

Proceed as follows:
- In the router get the query in the route parameters
- Dispatch the query in the store with the dispatcher
```javascript
 Focus.dispatcher.handleServerAction({
            data: {query: "your awesome query"},
            type: 'update',
            identifier: 'your store identifier'
        });
```
