### ISSUE TITLE
[IE9 compatibilty] The application doesn't work at all on IE9

### ISSUE THREAD

**Issue by JulienGard** [KleeGroup/focus-components#460]
After the login page, we have an error : "Object doesn't support property or method 'setrequestHeader'".

After that, it's a blank page and we can't do anything.

**Comment by durandx** [comment]
:+1:

**Comment by pierr** [comment]
Do you have the `npo.js` in your vendor directory

**Comment by pierr** [comment]
Does it works great on other IE?

**Comment by pierr** [comment]
Could you try to change the the props isCors to `false` in your `focus.js` see https://github.com/KleeGroup/focus-core/blob/develop/src/network/cors.js#L18

**Comment by JulienGard** [comment]
IE10 and IE11 works but with graphical bug

**Comment by durandx** [comment]
Yes in v0.8.1

**Comment by pierr** [comment]
Have you try to change the Boolean value of Cors as I suggest in my comment?
