### ISSUE TITLE
[Validator] Allow a custom validation function to access the isRequired state

### ISSUE THREAD

**Issue by JabX** [KleeGroup/focus-components#461]
I have a custom domain (for an object with 3 fields) with a custom validation function (it checks if one of the 3 fields is not null).

My problem is that the custom validation function should not have the same behavior if the field is required or not (namely, the field that can't be null can be when the field isn't required).

There is no way currently to get this information (the context of the validator function is the validator itself). That would be helpful then if some context info could be passed to the validator : I personnaly only need the isRequired state, but I believe someone else could use something else there.

**Comment by pierr** [comment]
https://github.com/KleeGroup/focus-components/blob/develop/src/common/field/mixin/validation-behaviour.js#L56  

Two options:
- call _validate on the field component
- pass validation as a props (better)
