### ISSUE TITLE
[select] validation test works only once

### ISSUE THREAD

**Issue by Tommass** [KleeGroup/focus-components#471]
![select](https://cloud.githubusercontent.com/assets/5349745/10262883/d7410bce-69da-11e5-9094-246e68a77e0e.gif)

**Comment by pierr** [comment]
Lol

**Comment by pierr** [comment]
Does it occur with the refactored components?

**Comment by Bernardstanislas** [comment]
Might be because we need to do a `downgradeElement` in the `mdlBehavirour` when refreshing in the `componentWillReceiveProps`

**Comment by Tommass** [comment]
yes Mister Stan, i think you have the solution ^^
a pepito would be waiting for you on monday !

**Comment by Bernardstanislas** [comment]
@Tommass Did you try it ? Is it solved this way ?

**Comment by Tommass** [comment]
Won't work ´cause it's not a mdl component

**Comment by Bernardstanislas** [comment]
What do you mean? It is a mdl component, for the animated color bar etc, there is a js behaviour

**Comment by Tommass** [comment]
Not the select component. For now it is just styled.
