### ISSUE TITLE
[Search results] Cannot pass reference store to search results

### ISSUE THREAD

**Issue by JabX** [KleeGroup/focus-components#480]
The component ```Focus.components.page.search.common.component.results```, used to display search results, can't pass along a reference prop to its children to use with reference name resolving.

**Comment by sebez** [comment]
:+1:

**Comment by oussony** [comment]
:+1:

**Comment by sebez** [comment]
:+1:

**Comment by sebez** [comment]
![giphy 1](https://cloud.githubusercontent.com/assets/9380855/10612965/662a8114-7753-11e5-9e24-5bb7052b9b79.gif)

**Comment by Bernardstanislas** [comment]
#lourdeur

**Comment by Bernardstanislas** [comment]
I don't understand where the reference store should come from. As far as there is no `form` involved in the search process, where do you want to get the reference from ?
If you want a reference in a search result line, you should add the `referenceBehaviour` yourself I guess, and manage the store filling too.
Feel free to come by to discuss about this

**Comment by JabX** [comment]
Well it could come from anywhere, that's the point of implementing it with a prop.
I could put the referenceBehaviour on each line but it seems a bit cumbersome to have *n* stores bindings whereas one could suffice.
