### ISSUE TITLE
confirmation popin closes too early

### ISSUE THREAD

**Issue by Jean-MichelForhan-KLEE** [KleeGroup/focus-components#485]
The confirmation popin closes then calls the server if instructed to do so.
This means that the user will thought that everything will be ok even if something goes wrong server side.

This means also that unmount behavior will be done before the action has taken place, which is annoying if the confirmation popin was about a status change on data displayed behind the modal window

**Comment by Bernardstanislas** [comment]
As seen together, this is a case where you  should provide your own component, extending either the `Popin` or the `ConfirmationPopin`, choose what suits you better.
We won't provide a way to defer the popin closing, as it does not fit in our rules of interface simplicity. However, feel free to provide your own that will be used on your project.
