### ISSUE TITLE
[component][reference list] empty list when editing form

### ISSUE THREAD

**Issue by anisgh** [KleeGroup/focus-components#49]
When editing a form with reference list, the list is displayed correctly but with no data. 
The list must display labels from target reference list
![issue_empty_list](https://cloud.githubusercontent.com/assets/5940196/7840367/5bfe3e8a-0497-11e5-8542-4f2740f5a694.jpg)

**Comment by pierr** [comment]
The value sould be defined as the code and the label as the label otherwise you can edit the `valueProperty` and / or the `labelProperty` 
```javascript
//List example
var valuesExample = [
      {code: "A", label: "aaaa"},
      {code: "B", label: "bbbbb"},
      {code: "C", label: "ccccc"}
    ];
```

**Comment by pierr** [comment]
Check the example https://github.com/KleeGroup/focus-components/blob/master/common/select/classic/example/index.html
