### ISSUE TITLE
Ref submission in form has strange behaviours in Checkbox component.

### ISSUE THREAD

**Issue by Hauwkins** [KleeGroup/focus-components#492]
First try : 
![image](https://cloud.githubusercontent.com/assets/2612585/10305284/ac98b48e-6c1f-11e5-9adf-f45397e96a43.png)

Problem encounter : The ref has the same name as the state props. (So it's getted by the web service) But the checkbox returns only a list of long (so the web service throws an error), and not a list of objects.
So we rename it : 
![image](https://cloud.githubusercontent.com/assets/2612585/10305317/df64907c-6c1f-11e5-9e01-afbe937b3923.png)
But : 
![image](https://cloud.githubusercontent.com/assets/2612585/10305396/38fa3ce0-6c20-11e5-9b90-8a2bfad6dc30.png)

Second problem : The service returns Both, classic value and the new value.
Third problem : The new value contains Both the object previous values (even if we untoggle them) AND the Ids of the new values.

So : first we had ommit the classic value and then we had ommit the objects param in the custom values:
![image](https://cloud.githubusercontent.com/assets/2612585/10306136/377c8c7e-6c25-11e5-95ec-2ba22fead69d.png)

Can you fix a simplest way to do so ?

MOREOVER: The entry of the checkbox component needs the list of IDS among the possible values and the list of object (The exactly same that is set in values) doesn't work, we had to filter this list in order to remove everything except the Ids:

![image](https://cloud.githubusercontent.com/assets/2612585/10308706/e86f92ee-6c37-11e5-98e2-1e1722a8ef4f.png)

FINALLY: The state is not updated, and after the save, the object seems not to have been updated. Firstly because the it needs an object list and the checkbox returns a list of KEY, but it update well the classic attribute with these keys (the one we had to remove in order to avoid type mismatch in the server)

Proposition of solution : 
- Give a definition path to the check box component for it to handle everything.
- Extends the ID-list treatment to Generic Object-list treatment.
- Give an option to save the result into the state
- Give an option to precise wich is the attribute to assign in the state

Remark :
Please homogenize your options label : 
Id, code, label, value, valueKey, labelKey, values,... ?
I mean a couple (Key, value) is far more explicit than the (value, label) & (code, label) encoutered.
And is it really pricey to precise 'selectedValue' and 'possibleValue' insteand of 'value' and 'values' ?

Truely yours.

**Comment by pierr** [comment]
Many remarks,
to sum up:
- why can't you try a simple `fieldFor('outilMetier', {valueKey: 'id', value: yourValue, listName:'outilsMetiers'})`, it should be working using your definition path. I think it reads the value from a wrong part of the state. You shoud debug your state / props given to the component Checkbox.
- it is hard to find the good names for select , i agree it's quite the mess between code / value / key.
But value and values are necessary as fields are not specific to select components.

**Comment by pierr** [comment]
@Hauwkins can  you try the first point
