### ISSUE TITLE
[AdvancedSearch][Results][Question] No configuration possible? (0.6.2)

### ISSUE THREAD

**Issue by sgoretti** [KleeGroup/focus-components#497]
Little question:
If I want to configure my search results so that, using groups, I still want all items displayed (being on a short list, for example), is there a way to configure the results component or do we have to create a new AdvancedSearch-like component overloading the renderResults method (import component, and omit said method. A useful but dangerous way of doing that we're doing too much) in order to use another results component ?

**Comment by sgoretti** [comment]
:+1: 
Yes, I'm +1-ing my own question.

The grouping component usesan initialRowcount parameter that could be changed to my desire, but AdvancedSearch doesn't have that prop and so I can't configure the component as I wish.

**Comment by tchappe** [comment]
:+1: 
We need this parameter for Linkit. It seems it exist but is not active.
