### ISSUE TITLE
[input-date]Typing in an input date doesn't work

### ISSUE THREAD

**Issue by ursuandrei42** [KleeGroup/focus-components#499]
For example, if I type 01/02/2003 in an input date field and save, the saved value will be 02/01/2003.
If I type 20/01/2003 and then blur the field the input will have refresh to empty string value.

The methods
```
_onInputBlur({target: {value: inputDate}}) {
        if (moment(inputDate).isValid()) {
            this.setState({
                inputDate,
                rawDate: moment(inputDate)
            });
        } else if ('' === inputDate) {
            this.setState({
                inputDate: null
            });
        } else {
            this.setState({
                inputDate: this.getFormattedDate()
            });
        }
    },

_onInputChange({target: {value: inputDate}}) {
        if (moment(inputDate).isValid()) {
            this.setState({inputDate, rawDate: inputDate});
        } else {
            this.setState({inputDate});
        }
    },
```
doesn't take in account any format when checking if date is valid.

**Comment by Bernardstanislas** [comment]
This has been fixed in [version 0.7.0](https://github.com/KleeGroup/focus-components/releases/tag/v0.7.0).
Please refer to the release note to upgrade, your issue should be fixed with the new date component.
Feel free to reopen if it still doesn't work.
