### ISSUE TITLE
[component][date picker] multiple nodes when edit/cancel action

### ISSUE THREAD

**Issue by anisgh** [KleeGroup/focus-components#50]
When repeating Edit/Cancel actions in a form, multiple nodes are created for the same date picker.
![issue_date_picker_multiple_nodes](https://cloud.githubusercontent.com/assets/5940196/7840358/549a2ab4-0497-11e5-95b4-3774e81364ba.jpg)

**Comment by pierr** [comment]
This could be reolved using the `parentEl` option of the component but it seems bug when it is attached to a too clode node.

**Comment by pierr** [comment]
This pull request solves this issue https://github.com/KleeGroup/focus-components/pull/132 according to me, but the major problem is that the jQuery plugin used isn't clean.
