### ISSUE TITLE
Application message Create vs. Update

### ISSUE THREAD

**Issue by pierbrisson** [KleeGroup/focus-components#500]
Presently, during a save operation in the database, the framework returns the message "detail.saved", regardless of whether the operation is a creation or an update.

It would be useful to disregard the Save operation as it is and have two distinct operations: Creation and Update, and have a distinct message key for each.  Especially considering that the webservice for each operation clearly have to be distinct.

Wouldn't Vertigo be able to identify the object's primary key and determine which kind of operation it is and thus return the appropriate message?

![image](https://cloud.githubusercontent.com/assets/8983628/10311218/203f29d8-6c46-11e5-87a8-6c7ea4786c21.png)

**Comment by pierr** [comment]
https://github.com/KleeGroup/focus-components/blob/develop/src/common/mixin/store-change-behaviour.js
