### ISSUE TITLE
[display][text]Unwanted internationalization

### ISSUE THREAD

**Issue by ursuandrei42** [KleeGroup/focus-components#505]
When used with formMixin, the display text component does i18n for any value
```
renderValue(){
        const {formatter, value} = this.props;
        const translatedValue = value ? this.i18n(value) : value;
        return formatter(translatedValue);
    },
```
If the value I want to display is found in fr-FR.js I get the following value displayed:
```
key 'translation:structure (fr-FR)' returned an object instead of string.
```
where 'structure' is an object in my fr-FR.js file.

**Comment by durandx** [comment]
:+1:

**Comment by pierr** [comment]
Duplicate of https://github.com/KleeGroup/focus-components/issues/367
