### ISSUE TITLE
[date_component] validating a form with a mandatory date set to null filled it with today's date

### ISSUE THREAD

**Issue by JulienGard** [KleeGroup/focus-components#508]
To reproduce : 
1- Open a form with a mandatory date
2- Don't filled the date and validate
3- The date's field is set to current date.

**Comment by durandx** [comment]
:+1:

**Comment by pierr** [comment]
This is due to a new behaviour of `Custom` components. See https://github.com/KleeGroup/focus-components/commit/12924d43f70c13b8077902eeaa27554deede17bb . So the date input should validate required props. @Bernardstanislas this need to written in a doc.
