### ISSUE TITLE
[date_component] z-index regression for the calendar popin

### ISSUE THREAD

**Issue by durandx** [KleeGroup/focus-components#509]
The z-index of the calendar popin provided in focus-components.css is setted improperly when used inside a block.

![image](https://cloud.githubusercontent.com/assets/9220437/10340316/cea9d35a-6d0f-11e5-9cca-030d9d47d5dd.png)

**Comment by JabX** [comment]
Yeah it's a duplicate but don't forget it does it with the autocomplete too.

**Comment by Bernardstanislas** [comment]
Yes, it is induced by the `panel`, which has been fixed and will be release in 0.7.1
