### ISSUE TITLE
[DatePicker] 'Locale' prop is ignored

### ISSUE THREAD

**Issue by JabX** [KleeGroup/focus-components#511]
I just tried for over an hour to set the locale to French for the date picker (newer version) but whatever I do it seems like the component ignores the locale prop I give him through the options of my fieldFor.

And I think it would be better if it simply use the global moment locale, instead of redefining it in the ```componentWillMount()```

**Comment by pierr** [comment]
@JabX  Did you look to the example associated with the component https://github.com/KleeGroup/focus-components/blob/develop/src/components/input/date/example/index.js , you can set it through the domain.

**Comment by JabX** [comment]
Hum.
Ok.
@remigrange just showed me.
But the exemple doesn't show that you simply need a locale property in the domain.
