### ISSUE TITLE
[auto-complete component] Field is set to blank in case of submitting a invalid form

### ISSUE THREAD

**Issue by JulienGard** [KleeGroup/focus-components#513]
How to reproduce : 
1- Open a form with a autocomplete field and a mandatory field
2- set a value to the autocomplete field.
3- submit the form 
==> There is a error display (which is normal) and the autocomplete field is set to blank.

**Comment by ursuandrei42** [comment]
This bug happens if the the value set in the autocomplete field is not part of the autocomplete suggestion list.

**Comment by Bernardstanislas** [comment]
That is because you should set the `allowUnmatchedValue` to `true` if you want to allow values that do not exist in the picklist. 
You can set this value in the options of the field in case you use an `autocompleteFor` in a `form`.
