### ISSUE TITLE
[formMixin?] State updates (probably from reference loading) reset all fields

### ISSUE THREAD

**Issue by JabX** [KleeGroup/focus-components#517]
Since 0.7.1, when I click for the first time on the 'Edit' button, and start right away to edit any field value, it is resetted a few times. It doesn't happen again when i cancel and reclick 'Edit'.

For some reason it was extremely hard to capture this in gif, but I got here a sample:
![test](https://cloud.githubusercontent.com/assets/3266897/10364771/9516c2d8-6dbe-11e5-917c-9bbdfa7e348f.gif)

**Comment by JabX** [comment]
I have a better one :
![yolo](https://cloud.githubusercontent.com/assets/3266897/10605376/29bdb80e-772b-11e5-9203-4dd7d8f132ba.gif)

**Comment by sebez** [comment]
:+1:

**Comment by Bernardstanislas** [comment]
You might be re-rendering the form, which gives new empty props to the fields and clears your inputs. Can you please try to debug and investigate who's responsible for the potential re-render.
Thank you

**Comment by oussony** [comment]
:+1:

**Comment by JabX** [comment]
I think this is the best description I can give:
![referenceee](https://cloud.githubusercontent.com/assets/3266897/10606206/7df685bc-7731-11e5-8809-64edf904a6c0.gif)
('projet' is the form store node, the others are the reference lists)

**Comment by pierr** [comment]
The real problem is the form should be in a loading state until the references are loaded as for other actions.

**Comment by Tommass** [comment]
@JabX @pierr @Bernardstanislas is it still relevant ? 
@pierr or @Bernardstanislas could you please qualify this issue ?

**Comment by JabX** [comment]
Yup.

**Comment by pierr** [comment]
@JabX Is it still an issue ?

**Comment by JabX** [comment]
Probably.

**Comment by Bernardstanislas** [comment]
This is due to the current implementation of the form.
This won't be solved on this version, but with the use of Redux.
