### ISSUE TITLE
[ListPage] React 0.14.0 breaks the ListPage component

### ISSUE THREAD

**Issue by JabX** [KleeGroup/focus-components#531]
Works fine under 0.14.0-rc1, but when I updated to the release version it broke. The headers are displayed correctly but not the rows, and I have a 'not a component error'..

I have a commit that does just the migration and it works well before and not after, so I'm sure the problem is there.

**Comment by pierr** [comment]
@JabX It seems quite strange. Can you provide a stack trace or come in our office to talk about it.

**Comment by pierr** [comment]
@JabX do you still have this issue because other projects don't have it cc @Pandakls

**Comment by pierr** [comment]
@JabX reopen it if still an issue.

**Comment by JabX** [comment]
Okay so to be honest the problem came from something particular that I was doing on my end that worked fine until 0.14. Basically, i was defining the Line component of my List directly in the class definition (using `lineComponent={this.line}` to access it in a mixin), and that broke. Wrapping it in a `getLine()` function did the trick.

I had the exact same problem with the same fix somewhere else a while ago...

**Comment by pierr** [comment]
Thanks for your answer. We will now be able to identify this type of problem, or at least check for it.
