### ISSUE TITLE
Consistency issue between Vertigo and Focus for the component : FocusComponents.page.list.component

### ISSUE THREAD

**Issue by Hauwkins** [KleeGroup/focus-components#532]
When a web service send a list, i have to do a post treatment like this :

```javascript
return fetch(URL.getAllJustificatif({urlData:{id}})).then((data)=>{ return {dataList: data}; });
```

The problem is that all errors a absorbed except if i specify (FOR EACH LIST-SERVICE in the app) the failure of the promis.

For what ? Just so that the component :
```javascript
const SmartList = FocusComponents.page.list.component;
```
Can read the data of the service used like this :
```javascript
let JustificatifLine = require('./justificatifLine');
const storeList = require('stores/justificatifDemande');
const serviceList = require('../../../services').demande.getJustificatif;
_getListPageProps() {
        let listePage = this;
        const {id} = this.props;
        return {
            lineComponent: JustificatifLine,
            store: storeList,
            service: serviceList
        };
    },
    render(){
        return (
        <Block title='demande.justificatifs'>
            <SmartList ref='justificatifList' {...this._getListPageProps()} />
        </Block>
        );
    }
```

I mean, if the list component knows that the list getted from the service has to be name datalist instead of data and while vertigo still send 'data' and not 'datalist' for an array of data, maybe the component can accept something named data or do the cast itself. In order to avoid this useless post tratment after each service with list.

Meanwhile, i've already cover all my let-getters with .then((data)=>{ return {dataList: data}; })
And all my errors are invisible except in the console.

**Comment by pierr** [comment]
you can try to add a `.then(null, (err) => console.error(err)) `

**Comment by pierr** [comment]
Maybe a error handling shoud be done in the list action builder in https://github.com/KleeGroup/focus-core/blob/develop/src/list/load-action/index.js#L58

**Comment by durandx** [comment]
I had the same issue

you can use the following action to correct this inconsistency on the fly

```javascript
getHistorique(jsonData) {
        let urlData = assign({}, jsonData.urlData, {id: jsonData.data.criteria.id});
        let promiseHisto = fetch(URL.contact.historique({urlData: urlData, data: jsonData.data.criteria})).then( (facetResult) => {
            return {
                totalCount: facetResult.totalCount,
                dataList: facetResult.list
            };
        });

        return promiseHisto;
    },
```

**Comment by pierr** [comment]
You both propose the same fix.

**Comment by durandx** [comment]
@pierr Not exactly, I need to transform a faceted result from Vertigo which is {totalCount, list} -> {totalCount, dataList}  

And he has ransformed {totalCount, list} -> {datalist: {totalCount, ilst}}

I don't use the latest version of focusjs-components: 0.6.2 and vertigo 0.8.1. Maybe that's why

**Comment by pierr** [comment]
This will be fixed with the new Search API.
