### ISSUE TITLE
[Autocomplete] Overlay still isn't fixed in 0.7.1 (0.7.2 too)

### ISSUE THREAD

**Issue by JabX** [KleeGroup/focus-components#533]
![capture](https://cloud.githubusercontent.com/assets/3266897/10398833/6a4d41f2-6eaf-11e5-9468-095641cb7762.PNG)

**Comment by Bernardstanislas** [comment]
Please use `FocusComponents.components.Panel` instead of `Block`

**Comment by JabX** [comment]
I use a Panel.

**Comment by Bernardstanislas** [comment]
Don't you still have some bootstrap related file in your `vendor` ? Seems like a conflict of CSS, on your screenshot the input colored underline is not lined up with the grey underline. This happens when there are still some bootstrap CSS remaining in the brunch build.

**Comment by JabX** [comment]
Well I wasn't aware I had to remove it, maybe I missed the memo.
Anyway, the only thing that got fixed is the lines like you mentioned. My global layout is now a mess, and the initial problem isn't fixed.

**Comment by pierr** [comment]
Maybe wait until tomorrow, we will release a new layout version thanks to @Tommass

**Comment by JabX** [comment]
Still there in 0.7.2
