### ISSUE TITLE
[Menu] In 0.7.1, the menu, while always deployed, stays on top of the content (regression)

### ISSUE THREAD

**Issue by JabX** [KleeGroup/focus-components#535]
![capture](https://cloud.githubusercontent.com/assets/3266897/10398937/0f34ff48-6eb0-11e5-8974-1a552208335a.PNG)

**Comment by Tommass** [comment]
probably due to your css.
A new FOCUS layout structure will be delivered in next version. Please wait for it before try to correct it. It may clarify HTML and CSS structure.
