### ISSUE TITLE
[ScrollSpyContainer] 0.7.1 : The previous offsetTop error (while scrolling) has been replaced by a React warning

### ISSUE THREAD

**Issue by JabX** [KleeGroup/focus-components#536]
![capture](https://cloud.githubusercontent.com/assets/3266897/10398999/6ae68b40-6eb0-11e5-80b3-42cc9f288120.PNG)

**Comment by Bernardstanislas** [comment]
This has been fixed, will be delivered in the next release.

**Comment by Tommass** [comment]
delivered in 0.7.2

**Comment by JabX** [comment]
Well, it's still there for me after the update...
