### ISSUE TITLE
[advanced search] [list action bar] actions are not displayed.

### ISSUE THREAD

**Issue by JoanaDalmeida** [KleeGroup/focus-components#541]
list actions are not displayed on action bar.

The advanced search component call ActionBar component with operationList props  but ActionBar reads the lineOperationList Props.

AdvancedSearch:

![image](https://cloud.githubusercontent.com/assets/3300779/10424957/f64a7348-70d3-11e5-8792-269b9eaa0e3a.png)

ActionBar

![image](https://cloud.githubusercontent.com/assets/3300779/10424986/31129708-70d4-11e5-9194-b7493364c429.png)

**Comment by pierbrisson** [comment]
:+1:
