### ISSUE TITLE
[ScrollSpyContainer] Ignore popin Panels for the menu.

### ISSUE THREAD

**Issue by JabX** [KleeGroup/focus-components#548]
(0.7.1)

The ScrollSpyContainer scans for all the panels inside its children to build the left menu. 
I have a Popin inside a Panel that has another Panel inside it. So what happens when I open the Popin is that its Panel gets added in the menu, and it shouldn't.

I think it would be hard to detect automatically which Panels to add and which Panels not to add, so I suggest we find a way to do it manually (a prop ?)

**Comment by oussony** [comment]
+1

**Comment by sebez** [comment]
+1

**Comment by pierr** [comment]
It is not as easy as this.
A popin content could be an existing page.
It shoud be a selector which excludes the  popin.

**Comment by pierr** [comment]
@Tommass

**Comment by JabX** [comment]
Yes, but you manually add the content to the popin, so you could give it a prop in that case that excludes it from the selector.
