### ISSUE TITLE
[focus-components][checkbox] display boolean values as chackbox in view mode

### ISSUE THREAD

**Issue by anisgh** [KleeGroup/focus-components#55]
Boolean values should be displayed as checkbox instead of label "true"/"false" in view mode. 
![image](https://cloud.githubusercontent.com/assets/5940196/7911868/92972a5a-0862-11e5-9360-d3b20b206e39.png)

**Comment by pierr** [comment]
See with @Tommass  the false value is prefered , or any translated label.
The checkbox component using an icon can be done inside your project and then use the domain configuration to specify  the `DisplayComponent` in the configuration see https://github.com/KleeGroup/focus/tree/master/definition#domaine

**Comment by pierr** [comment]
This component is super easy to build

**Comment by pierr** [comment]
Half an hour max
