### ISSUE TITLE
Custom font library

### ISSUE THREAD

**Issue by pierbrisson** [KleeGroup/focus-components#552]
Presently, only material design and fontawesome fonts are taken into account by the framework.

In order to include project-specific icons, a custom font must be created by the project team (with gulp-fontcustom https://www.npmjs.com/package/gulp-fontcustom).  the framework needs to be able to take this custom library into account.

Seen with the Focus team @pierr , the name of the custom library must be "**font-custom**"

**Comment by pierbrisson** [comment]
linked to this issue https://github.com/KleeGroup/focus-components/issues/384

**Comment by pierr** [comment]
@pierr there is a problem with the `gulp` task, it does not work on windows.
You can use [icomoon](https://icomoon.io/app/) in order to generate your custom font from your svg icons.

**Comment by pierr** [comment]
You can upload your icons 
![image](https://cloud.githubusercontent.com/assets/286966/10660356/b347784a-78a6-11e5-912a-7aafac26d8d9.png)

And generate an export with a 
![image](https://cloud.githubusercontent.com/assets/286966/10660393/fc1553ee-78a6-11e5-8289-0119c5d35acf.png)
