### ISSUE TITLE
Allow demo/production mode for Dev bar 

### ISSUE THREAD

**Issue by pierbrisson** [KleeGroup/focus-components#553]
The dev bar is currently can only be hidden through CSS.  It would be useful to have an external parameter allowing for the dev team to have the bar displayed and for the deliveries to have it hidden.

![image](https://cloud.githubusercontent.com/assets/8983628/10480163/e686301e-7268-11e5-9e96-d34d3371b9d2.png)

**Comment by sgoretti** [comment]
:+1:
