### ISSUE TITLE
npm package and webpack aren't compatible because style files

### ISSUE THREAD

**Issue by fconstantin** [KleeGroup/focus-components#564]
When webpack is used, to build an application, the following errors occurs :
```
ERROR in ./~/focus-components/lib/style/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../application/bar/style/bar.scss in xxxxx.SPA\node_modules\focus-components\lib\style
 @ ./~/focus-components/lib/style/index.js 3:0-44

ERROR in ./~/focus-components/lib/style/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../application/cartridge/style/cartridge.scss in xxxxx.SPA\node_modules\focus-components\lib\style
 @ ./~/focus-components/lib/style/index.js 5:0-56
```
And many others.

The following script can be run from the node_modules/focus-components/src/style/ directory to temporarily fix the problem :
 
[focus-component-style.txt](https://github.com/KleeGroup/focus-components/files/14744/focus-component-style.txt)

**Comment by pierr** [comment]
We will fix it soon:
- You can link to css file in dist instead of reading the style file.
- Use `webpack` `alias` option such as in https://github.com/KleeGroup/focus-showcase/blob/develop/webpack.config.builder.js#L18 in order to link to src directory instead of lib directory in the node module

**Comment by Bernardstanislas** [comment]
Made it work [there](https://github.com/KleeGroup/focus-demo-app/blob/develop/config.webpack.js)
