### ISSUE TITLE
Material design package path assumption

### ISSUE THREAD

**Issue by fconstantin** [KleeGroup/focus-components#565]
If material-design-lite package version match between application and focus-components (which is usually true), package is installed in the root node_modules directory.

In this case, webpack give the following error :

ERROR in ./~/css-loader!./~/sass-loader!./~/focus-components/lib/style/mdl.scss
Module build failed:
@import "../../node_modules/material-design-lite/src/material-design-lite";

       ^
      File to import not found or unreadable: ../../node_modules/material-design-lite/src/material-design-lite
      in xxxx.SPA\node_modules\focus-components\lib\style\mdl.scss (line 1, column 9)
 @ ./~/focus-components/lib/style/mdl.scss 4:14-100

In this case, mdl.scss should contains the following line :
@import "../../../../node_modules/material-design-lite/src/material-design-lite";
instead of 
@import "../../node_modules/material-design-lite/src/material-design-lite";

**Comment by pierr** [comment]
`@import 'material-design-lite/src/material-design-lite'`

**Comment by fconstantin** [comment]
It doesn't work

ERROR in ./~/css-loader!./~/sass-loader!./~/focus-components/lib/style/mdl.scss
Module build failed:
@import "material-design-lite/src/material-design-lite";

       ^
      File to import not found or unreadable: material-design-lite/src/material-design-lite
      in xxx.SPA\node_modules\focus-components\lib\style\mdl.scss (line 1, column 9)
 @ ./~/focus-components/lib/style/mdl.scss 4:14-100

**Comment by Bernardstanislas** [comment]
Made it work on the demo app, see [there](https://github.com/KleeGroup/focus-demo-app/blob/develop/config.webpack.js)
