### ISSUE TITLE
[list-action-bar] Styles applied directly on the tag => needto use !important to overload

### ISSUE THREAD

**Issue by sgoretti** [KleeGroup/focus-components#574]
And I don't like to use !important.
![image](https://cloud.githubusercontent.com/assets/14293391/10583360/bf3b2532-768c-11e5-9e95-656e8cc3c146.png)
![image](https://cloud.githubusercontent.com/assets/14293391/10583373/ce741310-768c-11e5-8995-beb168a7715e.png)

**Comment by Tommass** [comment]
style props should not be used in components.

**Comment by Bernardstanislas** [comment]
Fixed [here](https://github.com/KleeGroup/focus-components/commit/0de40090fef4f1b7adc4d831b475bdb491ed0f1e)
