### ISSUE TITLE
[formMixin] It is not possible to load a referenceList without having a load action. 

### ISSUE THREAD

**Issue by durandx** [KleeGroup/focus-components#575]
In our case we need to load a referenceList from the server for our criteria and we don't have data to load.

In result we have to implement a empty loadAction:

```javascript
function load() {
    return new Promise(function(resolve) {
        resolve();
    });
}
```

**Comment by pierr** [comment]
@durandx you can use `Promise.resolve(yourData)`

**Comment by pierr** [comment]
@durandx 
I think you can use the props `hasLoad` on the form in order to disable `load`
https://github.com/KleeGroup/focus-components/blob/develop/src/common/form/index.js#L69
If this does not solve the issue, please reopen it.
