### ISSUE TITLE
[Select] OnChange returns string "UNSELECTED_KEY"

### ISSUE THREAD

**Issue by tadamK** [KleeGroup/focus-components#583]
On a dropdown, when I have a string field which is not mandatory and I choose "      ", the value sent to the server is "UNSELECTED_KEY" instead of null or empty.

**Comment by Bernardstanislas** [comment]
Which version are you using ? If >0.7.0, are you using the new `select` component ? (`FocusComponents.components.input.Select`)
This has been fixed, see [here](https://github.com/KleeGroup/focus-components/blob/develop/src/components/input/select/index.js#L58)
Please be carefull with the style of your issue, next time please try to stick to the [guideline](https://github.com/KleeGroup/focus-docs/blob/master/contribute/DECLARE_ISSUE.md)
