### ISSUE TITLE
[Image upload] Create a thumbnail version of the image

### ISSUE THREAD

**Issue by pierbrisson** [KleeGroup/focus-components#585]
# Actual behaviour
When uploading images, the image itself is saved into the database/file system.
When displayed in consultation as such

![image](https://cloud.githubusercontent.com/assets/8983628/10632505/2fcf6fde-77e5-11e5-83f1-e0b68f9dd8b2.png)

the original uploaded image is loaded. Which means that if the file is for example 20Mo, then that file is loaded and only afterwards resized to fit in the thumbnail.
To avoid having to load the real image, it seems better to create a thumbnail of the image during the upload and load that small thumbnail in the screen.  The original image would only be loaded when the user wants to zoom on the picture.

# Expected behaviour
After discussing it with @Tommass, we wonder if the thumbnail creation on the image upload should be managed by the framework (Vertigo) directly or whether it should be managed on the project level.

# Versions
Focus-core: 0.11.2
Focus-components: 0.7.2
Vertigo: 0.8.3

**Comment by Bernardstanislas** [comment]
Can this be discussed all together ? I'm interested about what will be decided about that

**Comment by Tommass** [comment]
@Bernardstanislas @NPi2Loup @pierr we should discuss about it :)

**Comment by Bernardstanislas** [comment]
As discussed with @NPi2Loup , this is a backend feature you should implement on your project.
