### ISSUE TITLE
maxlength of domain is not set on input field

### ISSUE THREAD

**Issue by Jerom138** [KleeGroup/focus-components#586]

**Comment by Bernardstanislas** [comment]
@Jerom138 as @pierr told you, it should be done with the `options` in the domain.
Closing for now, feel free to reopenin case it doesn't work.

**Comment by Jerom138** [comment]
Je n'aurai pas créé une issue si je n'avais pas essayé sans succès.
J'ai même tenté de forcer le maxlength dans le field-component-behaviour, comme je l'ai fait pour le type, mais rien à faire...
Merci de réouvrir l'issue

**Comment by pierr** [comment]
Can you add your domainin the issue

The `props` shoud be fine here https://github.com/KleeGroup/focus-components/blob/develop/src/common/field/mixin/built-in-components.js#L106 can you check please ?

 Can you check the props value here https://github.com/KleeGroup/focus-components/blob/develop/src/components/input/text/index.js#L66

**Comment by pierr** [comment]
As seen with @Bernardstanislas it was a mistype problem.
All the supported attributes are describe here : https://facebook.github.io/react/docs/tags-and-attributes.html#html-elements .
 @Jerom138 Can you add a copy of your domain here in order to help other project to use it.
