### ISSUE TITLE
Vertigo-made onfield error is not handled by Focus

### ISSUE THREAD

**Issue by Pandakls** [KleeGroup/focus-components#587]
Un test coté serveur, renvoie l'erreur suivante (générée avec vertigo de manière "classique")
{
  "fieldErrors": {
    "telephone": [
      "Le champ telephone est obligatoire."
    ]
  }
}

l'erreur : 
![image](https://cloud.githubusercontent.com/assets/7700690/10632855/28b3c964-77e7-11e5-8ce2-31b69ac31561.png)

est affichée en console mais aucune erreur est relevée sur la page. De plus apres cette erreur, l'action abandonne ne restaure pas les champs du formulaire.

**Comment by pierr** [comment]
It is more a focus-core bug

**Comment by pierr** [comment]
I will add unit test to be sure to handle this case.

**Comment by Jerom138** [comment]
:+1:

**Comment by Pandakls** [comment]
:+1:

**Comment by Bernardstanislas** [comment]
Not fixed, linked to #668

**Comment by Jerom138** [comment]
Non ce n'est pas lié à l'issue 668 en fait.
Il semble que le dispacher tente de dispatch l'erreur de l'applicationStore et non dans le store du composent. Et par conséquent il ne trouve pas le noeud du "fieldErrors" dedans... et ne dispatch donc pas.

**Comment by Jerom138** [comment]
```javascript
  _getErrorStateFromStores: function formGetErrorStateFromStore() {
	    if (this.getErrorStateFromStore) {
	      return this.getErrorStateFromStore();
	    }
	    var newState = {};
	    this.stores.map(function (storeConf) {
	      storeConf.properties.map(function (property) {
	        var errorState = storeConf.store['getError' + capitalize(property)]();
			for(var prop in errorState){
				newState[property + '.' + prop] = errorState[prop];
			}

	      });
	    });
		return newState;
	    //return this._computeEntityFromStoresData(newState);
	  },
```
