### ISSUE TITLE
[AdvancedSearch][Group][InfiniteScroll] Bug when only 1 group with infinite scroll

### ISSUE THREAD

**Issue by sgoretti** [KleeGroup/focus-components#589]
# Actual behaviour
The grouping options contain every possible facet at the moment, regardless of the number of distinct values in it.
I used a profile restricting my access to a single Area.
When I group by Area
![Selecting Area: an example](https://cloud.githubusercontent.com/assets/14293391/10636039/261335d0-77fd-11e5-9c7e-a8df454d81c6.png)
The application loads the list groupes by Areas. Since there's only one, it loads a single group with infinite scroll activated.

2nd part of the problem is that we decided to have line less thick than in most Focus apps.
![this is not thick](https://cloud.githubusercontent.com/assets/14293391/10636100/7dcc7566-77fd-11e5-8086-a9cfd41f6396.png)
So what happens is that all items returned by the queryare displayed on the screen, so we're at the bottom of the scroll. this triggers the infinite scroll and from there, the infinite scroll triggers endlessly. Guilty part is this:
```javascript
_onScrollReachedBottom: function _onScrollReachedBottom() {
                       var _this2 = this;
                       if (!this.state.loading) {
                           this.setState({
                               loading: true
                           }, function () {
                               _this2.props.action.search(true);
                           });
                       }
                   },
```

Ending with
![Rate limit exceeded](https://cloud.githubusercontent.com/assets/14293391/10636196/6a1ecb6c-77fe-11e5-95d1-ae368ec53530.png)

This doesn't occur immediately: at first, you remain on the page with no visible change, but in the back, elasticsearch is being harrassed by the application and reaches its limit. so the screen is locked and when you call another screen using ES, you get this nice error message with no data loaded. 
And ES is stuck for several minutes after this.

/!\ Why does this happen when using a group and not on a normal scoped search: 
the difference is the number of row returned: a normal search returns enough lines to need a scrollbar. The group search returns only 3 items, so if you have a group search with a single group, you will trigger the bug.
Quite possibly, if your lines are thinner than ours, the bug can be triggered from a standard scoped search.

# Expected behaviour
Remove facets with 1 value from grouping options or fix the bug with the infinite scroll auto-starting

# Versions
Focus-core: 0.11
Focus-components: 0.7.2

**Comment by Bernardstanislas** [comment]
Have you checked the Focus Demo to see how this is handled ?
I think you should handle this case on the server side, to tell ES to return more than 3 results in case there is only one group.
Otherwise, as you describe, the infinite scroll will endlessly try to get more results, because you're telling it that there are X results (X > 3) but whatever it asks, you only give it 3 results.
So on that point, this is the expected behaviour.

**Comment by sgoretti** [comment]
What bothers me more is that Focus doesn't stop asking for more lines. That's the core problem: if the page started loading 10 more lines and stopped, that would be perfectly fine. But it keeps loading, that's the bug: it seems that even though it's loading, it's never displaying what it's loading.

Maybe you should see it directly: Christian will be able to show it to you tomorrow.

**Comment by Bernardstanislas** [comment]
I think the problem is that your server answers with : there is a total of X results, here are 3. And the client side, the search component is at the bottom of the page, so it will try to fetch the next results. But since your server only sends the first 3 results, the client will loop trying to fetch the next results.

**Comment by sgoretti** [comment]
You do realize that even if I sent 10 results if my lines were thin it would bug the same. So the problem is: I shouldn't be able to group for groups with a single value. ElasticSearch can't return more than 10 values for a group.

**Comment by pierbrisson** [comment]
:+1:

**Comment by Bernardstanislas** [comment]
As seen with Christian this morning, the problem is that the advanced search shouldn't let you group on a facet which has only one value. This will fix the issue.
