### ISSUE TITLE
[date_component] The calendar icone doesn't do anything when I click on it.

### ISSUE THREAD

**Issue by JulienGard** [KleeGroup/focus-components#590]
# Actual behaviour
Maybe it's the correct behaviour, but the calendar on the right of the date component doesn't do anything when clicking.
It's working when I click on a date field.

# Expected behaviour
clicking on the calendar on the right of a date field must show the date picker.

# Versions
0.7.2

**Comment by Bernardstanislas** [comment]
The calendar is displayed when you click in the field, the icon is here just to show that the field is a date.

**Comment by Bernardstanislas** [comment]
This will be added in the next release
