### ISSUE TITLE
[Left menu] The lasts items on the menu are not correctly selected if they don't take a entire slot

### ISSUE THREAD

**Issue by JulienGard** [KleeGroup/focus-components#591]
![menu gauche](https://cloud.githubusercontent.com/assets/1950825/10637262/d5ef1a6c-7804-11e5-961a-41bb0f2eae56.gif)
# Actual behaviour
If the lasts item of the menu doesn't take a lot of space, when I click on it, the page scroll down at max and the selected item is not correct.
(cf. attached file)

# Expected behaviour
My menu's items must be selected when I click on it. 

# Versions
0.7.2

**Comment by pierr** [comment]
@JulienGard your gif is missing

**Comment by JulienGard** [comment]
Voilà, ça devrait être mieux :)

**Comment by Bernardstanislas** [comment]
Isn't it the expected behaviour ? The active item is the one displayed at the top of the screen, so when you select one of the last items and it is not big enough to fill the whole screen, then the summary on the left won't be able to set the clicked item as active.

**Comment by JulienGard** [comment]
I don't know, I let you select the right behaviour. 
For me, it's a litlle confusing to select an item and another one is mark as 'active'
