### ISSUE TITLE
Cannot scroll when page is too short

### ISSUE THREAD

**Issue by sanfinsm** [KleeGroup/focus-components#593]
# Actual behaviour

On any page that is slightly overflowing, when trying to scroll down, you get blinked back to the top of the page, it is impossible to see the bottom.

![image](https://cloud.githubusercontent.com/assets/9960528/10643008/e4d56696-7820-11e5-9425-626acaf3f67e.png)

I believe this is due to the header becoming sticky and altering the length of the page, making it short enough to fit into the screen.

# Expected behaviour

Page should be scrollable, as are longer pages.

# Versions

Focus-core: 0.11.0
Focus-components: 0.7.2

**Comment by pierr** [comment]
@sanfinsm can you add a screenshot

**Comment by pierr** [comment]
Is it the same as https://github.com/KleeGroup/focus-components/issues/164

**Comment by sanfinsm** [comment]
Yes probably the same issue.

**Comment by Bernardstanislas** [comment]
@pierr the famous **zigwigwi** issue :smile:
