### ISSUE TITLE
[Date - Enhancement] Allow a getValue() customisation from the domain.

### ISSUE THREAD

**Issue by JabX** [KleeGroup/focus-components#599]
I'll be speaking here only about pure dates (with no time).

Currently, all date/time(s) are handled as ISO strings, converted in the user's locale.
That means that when a user selects a date in the date picker, it represents the chosen date at midnight in the user's locale. For instance, if I select 22/10/2015, it is represented as `22/10/2015 00:00:00 GMT+2`, and the ISO string (which will be send to the server) is then `21/10/2015 22:00:00`.

I understand this is a perfectly normal behaviour and that it might be required for some projects, but in my case (and probably others') I'd like to ignore totally the time component and the user's locale and output a nice `22/10/2015 00:00:00` ISO string when I pick a date. That's way easier to reason with for us.

It's probably not Focus's place to handle this kind of behaviour, but it would be nice to have a hook somewhere to implement this ourselves. The right place for it would be in the date component's `getValue()` method, which is called to build the data that will be sent to the server. So if we had a little `formatValue` method in the domain that will apply a transformation to the result of `getValue()`, it would be perfect.
I can see it being useful for other components and domains as well.

**Comment by oussony** [comment]
:+1:

**Comment by pierr** [comment]
As discussed together
- in => ISOSTRING
- out => ISOSTRING
- a props such as transformValue in order to change (depending on the project) the way the date is get before it's sent to the server.
- This will be called in the getValue function
- Then you have to be coherent on the server side, the date won't be transform before it's provided to the component
