### ISSUE TITLE
[form][displayFor] hasLabel haven't effect on displayFor

### ISSUE THREAD

**Issue by JRLK** [KleeGroup/focus-components#602]
The label is still displayed when I use the option `hasLabel: false`.

Focus-components : v 0.7.1-rc2
Focus-core : v 0.11.0

**Comment by pierr** [comment]
@JRLK Do you use `displayFor` or `fieldFor` ?
In your case i don't see why you don't use `textFor`

**Comment by pierr** [comment]
In the showcase when i do 
```jsx
 <Panel actions={this._renderActions} title="Fiche de l'utilisateur">
                {this.fieldFor('firstName')}
                 {this.fieldFor('firstName', {hasLabel: false})}
</Panel>
````

**Comment by pierr** [comment]
@remigrange  @JRLK  I close this issue, don't hesitate if you need help.
