### ISSUE TITLE
[List] Asking for simplicity for overriding edition of a line + bug thrown by server are not handled.

### ISSUE THREAD

**Issue by Pandakls** [KleeGroup/focus-components#604]
Adding a pop-up confirmation or redirecting to a page after a simple "sauvegarder" Or "Annuler" Action is fairly common a should be an easy thing to do. (I mean, there's post-save action in at least 50% of our components)

Meanwhile in Focus i have to Ugly stuff just in order to refresh a parent component like this : 

### Simplicity Issue n°1.1 & n°1.2 : Refresh the page-caller popin and close popin on action
I've a page containing a list, the detail of each item can be seen in a right popup (classical utilisation that is suggested of Focus) :

Here's the content of my pop-up THAT IS SUPPOSED TO CONTAIN ONLY 3 FIELDS. 
```javascript
// Dependencies
const {omit} = _;

// Stores
let store = require('stores/administration');

// Mixins
let formMixin = Focus.components.common.form.mixin;
formMixin.mixins[6] = omit(formMixin.mixins[6], 'buttonCancel');

// Actions
let actions = require('action/administration').messageAccueil;

// Components
let Block = FocusCore.components.common.block.component;
let Button = FocusComponents.common.button.action.component;

module.exports = React.createClass({
    definitionPath: 'messageAccueil',
    displayName: 'messageAccueil',
    mixins: [formMixin],
    stores: [{store: store, properties: ['messageAccueil']}],
    action: {
        load: actions.load,
        save: function(data){
            actions.save.call(this, data);
            this._popinCloser();
        }
    },
    buttonCancel() {
        const handleOnClick = () => {
            this.clearError();
            this.setState({isEdit: !this.state.isEdit}, () => {
                changeMode('consult', 'edit');
            });
            this._popinCloser();
        };
        return (
            <Button
                handleOnClick={handleOnClick}
                icon='undo'
                iconLibrary='font-awesome'
                label='button.cancel'
                shape={null}
                style={{className: 'cancel'}}
                type='button'
                />
        );
    },
    _popinCloser(){
        this.props.popinCloser();
    },
    renderContent() {
        return (
            <Block title='administration.message' actions={this._renderActions}>
                {this.fieldFor('dateDebut')}
                {this.fieldFor('dateFin')}
                {this.fieldFor('texte')}
            </Block>
        );
    }
})
;

```
Really focus ? Have i to do all this overriding by hand ?
Not mentionning the look of my actions : 

```javascript
    messageAccueil: {
        load: actionBuilder({
            service: services.getMessageAccueilById,
            node: 'messageAccueil',
            status: 'loaded'
        }),
        save: function (data) {
            let form = this;
            actionBuilder({
                service: services.saveMessageAccueil,
                node: 'messageAccueil',
                status: 'saved'
            }).call(this, data).then(function(){
                form.props.refresh();
            });
        }
   }
```
Just so that the list gets **refresh** when i save my item and also to **close the pop-up** on save and cancel action -> what 99% of the pop-up component editor should do by default because direct line editing in a list is not allowed in Focus conventions.

### Simplicity Issue n°2 : Just getting some list with error that are shown on the screen
About lists manipulation, Vertigo send a list called *data* and the Focus.page.list componant is asking for something called *dataList*. Ok this is simply handeled lke this :
```javascript
    getAllParametreTechnique(){
        return fetch(URL.getAllParametreTechnique()).then((data)=>{ return {dataList: data}; });
    },
    getAllMessagesAccueil(){
        return fetch(URL.getAllMessagesAccueil()).then((data)=>{ return {dataList: data}; });
    },
```
But we lose all the errors givent by the server triggering 422 errors entity not handled...
(Error that are sent by the getList in most cases)

Maybe the list component should eat what we give to it and rename data to datalist itself !

**Comment by pierr** [comment]
@Pandakls as seen together, I agree there is something missing. 
According to me (maybe i'm wrong) there is two problems,

- The `SmartList` component is too magic with the service props, we shoud remove it and force component's user to provide an action

- The Line actions such as delete, create and the popin action shoud be easier to build.

One of the issue we are facing for this type of page Admin List is that a good example is missing. We will try to work on one in the demo's update in order to see what can be improve to ease development.
The simplicity issue 3 is a bug (you can create an issue for it if there is none.

Thank you for giving back feedback, it is really precious for us in order to improve.

**Comment by Pandakls** [comment]
About Simplicity issue 2 : 
J’ai réussi à faire un truc propre si jamais tu veux t’en inspirer pour la correction : 
Page de liste : 
```javascript
module.exports = React.createClass({
    mixins: [mixinTrad],
    displayName: 'Justificatif',
    _getListPageProps() {
        let listePage = this;
        return {
            onLineClick(line) {
                listePage.setState({
                    currentParamId: line.tyjId
                }, listePage.refs.editPopin.toggleOpen);
            },
            refreshList(){
                listePage.refresh();
            },
            lineComponent: JustificatifLine,
            store: storeList,
            service: serviceList
        };
    },
    refresh() {
        return this.refs.paramRefList._action.load();
    },
    render(){
        const {currentParamId} = this.state;
        let {needToBeLoaded} = this.state;
        if(currentParamId !== null){
            needToBeLoaded = true;
        }
        return (
            <Block title='administration.justificatif'>
                <SmartList ref='paramRefList' {...this._getListPageProps()} />
            </Block>
        );
    }
```

Comme ça j'ai pas a m'embeter avec des action builder dans la page, et coté ligne ça donne ça : 
```javascript
module.exports = React.createClass({
    mixins: [FocusComponents.list.table.line.mixin],
    definitionPath: "typeJustificatif",
    referenceNames: ['actifInactif'],
    _editHandler() {
        this.props.onLineClick(this.props.data);
    },
    _deleteHandler(){
        delServices.delTypeJustificatif(this.props.data.tyjId).then(()=> this.props.refreshList());
    },
    renderLineContent: function(data){
        let libelleActif = this.props.data.actif ? this.i18n('Actif'): this.i18n('Inactif');
        return (
            <tr className='hoverButton'>
                <td>{this.textFor('libelle', {})}</td>
                <td>{this.textFor('description', {})}</td>
                <td>{libelleActif}</td>
                <td>
                    <button className='mdl-button mdl-js-button' onClick={this._editHandler}>
                        <Icon name='create'/>
                    </button>
                    <button className='mdl-button mdl-js-button' onClick={this._deleteHandler}>
                        <Icon name='delete'/>
                    </button>
                </td>
            </tr>
        );
    }
});
```
Sorry for the non-english

**Comment by pierr** [comment]
This need a good example.

**Comment by Pandakls** [comment]
:+1: 
I just wan't to undeline this issue.

We are currently designing a new application, and we have A LOT of list with editable popin (behaviour pushed by FOCUS).

I think a new component EditPopin that acts like a Block in a Form AND includes "refresh of the list" + "close the popin" are included in the save and cancel button (Only if the save is a succes).

Do you intend to implement somthing like that ?

Else i'll need a great help to build it because it's sound more like a "good fist bug" than a "good first bug".

**Comment by Pandakls** [comment]
@Bernardstanislas :smile:

**Comment by Pandakls** [comment]
Seems to be implemented as 'administration list'. Can't find an example, can you help me ?
If this component is the answer you can link it here and close the issue :)

**Comment by pierr** [comment]
The example is in the demo app:

https://github.com/KleeGroup/focus-demo-app/blob/develop/app/views/masterdata/country/index.jsx
