### ISSUE TITLE
[Popin] Change route while popin opened doesn't restore the scroll bar.

### ISSUE THREAD

**Issue by JabX** [KleeGroup/focus-components#612]
The popin removes the scrollbar of the main content when it is opened, and restores it on close.
But when I navigate to another route with the popin still opened, it doesn't restore it and I'm stuck on the new page with no way to scroll down.

I could close the popin before changing my route but it would require the component Inside the popin to have a ref to it, which isn't ideal.

**Comment by JabX** [comment]
Now with a gif:
![yolo](https://cloud.githubusercontent.com/assets/3266897/10725418/382513f6-7bcc-11e5-9693-fb7c2a30a07f.gif)

**Comment by Bernardstanislas** [comment]
I agree this is not ideal. Maybe a lighter fix would be to call the [`_restoreBodyOverflow`](https://github.com/KleeGroup/focus-components/blob/develop/src%2Fapplication%2Fpopin%2Findex.js#L43) from the `overlay` component inside the `Popin` component.
You can access with under the `Popin`'s `'popin-overlay'` ref.
