### ISSUE TITLE
[Search Input Enchancement] Add a spinner when searching

### ISSUE THREAD

**Issue by pierbrisson** [KleeGroup/focus-components#623]
Add a spinner in search inputs (search bar and autocomplete) as a feedback to the user 

![image](https://cloud.githubusercontent.com/assets/8983628/10785253/0f2457bc-7d63-11e5-9b8e-c5a1ba2eadfa.png)

**Comment by pierr** [comment]
Great idea

**Comment by pierr** [comment]
I thought it was already present...

**Comment by pierbrisson** [comment]
:+1:  please
