### ISSUE TITLE
[SelectAction - Header] Pressing the secondary actions button doesn't open the list after a re-render.

### ISSUE THREAD

**Issue by JabX** [KleeGroup/focus-components#624]
It used to work on a previous version of FocusComponents (currently on 0.7.3-3) but for some time it has been broken, perhaps since the Layout update but I can't guarantee it.

I have some secondary actions on my header that are displayed or not according to my component state (from a store). On the first render, I don't have anything to display since I don't have the data from the store yet. I trigger a new render in `afterChange()` with the correct state and the correct secondary actions list. As far as React is concerned, everything is rendered fine. The secondary actions list is mounted in the DOM (but hidden), but clicking on the `...` button does not reveal it.

Secondary actions work otherwise fine on the initial render.

**Comment by Bernardstanislas** [comment]
That might be caused by material design.
Can you try to call the `componentHandler.upgradeElement(theRefToTheSecondaryActions)` in the callback of your `setState` in the `afterChange` ?
This will force mdl to apply the dropdown behaviour to the `...` button, which it had initialy skipped because it had no actions during the first render.

**Comment by pierr** [comment]
try `isJS=false` as props

**Comment by JabX** [comment]
Well I have neither a `setState` neither a ref to do that so I don't know what I can do on my end.

For the record, this is my code:
```javascript
 cartridgeConfiguration() {
        let secondary = [];
        if (this.state.isAbandnProjet) {
            secondary = [{
                label: this.i18n('page.projet.abandonProjet.label'),
                action: this.handleAbandonnerProjet
            }];
        }
        return {
            barLeft: {component: Back},
            cartridge: {component: Cartridge, props: {id: this.props.id}},
            summary: {component: Summary},
            actions: {
                primary: [],
                secondary: secondary
            }
        };
    },

    afterChange(changeOptions) {
        if (changeOptions.status && 'loaded' === changeOptions.status.name) {
            this._registerCartridge();
        }
    },
```

**Comment by JabX** [comment]
In the meantime, giving an initial 'pseudo-empty' list to `secondary` to force Material to 'mount' the Dropdown solves the issue.
Like this
```javascript
        if (this.state.isAbandnProjet) {
            secondary = [{
                label: this.i18n('page.projet.abandonProjet.label'),
                action: this.handleAbandonnerProjet
            }];
        } else if (_.isUndefined(this.state.isAbandnProjet) {
                secondary = [{
                label: '',
                action: () => null
            }];
```

**Comment by pierr** [comment]
Cool even if it is a bit ![image](http://s2.dmcdn.net/KiXzU/1280x720-fJK.jpg) .
We will solve this issue for the next release.

**Comment by JabX** [comment]
Still there.
I have to render the list even if it's empty and it's driving my PM crazy.
Thanks.
