### ISSUE TITLE
[Menu] iconLibrary props is not taken into account.

### ISSUE THREAD

**Issue by JoanaDalmeida** [KleeGroup/focus-components#625]
Impossible to add custom icon or font-awesome icon in Menu Bar.
The icnonLibray props is not taken into account.

**Comment by pierr** [comment]
@JoanaDalmeida  Can you use this format https://github.com/KleeGroup/focus-docs/blob/master/contribute/DECLARE_ISSUE.md to describe your issue

**Comment by pierbrisson** [comment]
:+1:
