### ISSUE TITLE
[Form - possible enhancement] Reset undefined fields in 'save' server response

### ISSUE THREAD

**Issue by JabX** [KleeGroup/focus-components#631]
I realize this is probably really marginal but I have this one expected behaviour that I'd like to be supported... eventually.

When a form is saved, Focus sends the entity to the server, gets the updated one from the server back and updates the form fields. In my case, according to one field value, some other fields may be deleted in the save action, and my server only sends back the actual existing fields.

The form only updates the fields it finds in the response and leaves the other be. That leads to impossible situations on the client side that can lead in server errors if I try to edit and save again.

One possible solution could be to store the form state in a dedicated state node (that would surely help for other things I guess), that can be entirely replaced easily.

(I found an 'acceptable' workaround for this and it's far from critical for my case.)

**Comment by pierr** [comment]
Ok, I agree with you. Thanks for your input.
We are currently working on the form to ease its use and separate references, store related informations (previous and new state), validation.

**Comment by pierr** [comment]
@JabX  Maybe the server should send `null` for a property which is no longer filled .

**Comment by Bernardstanislas** [comment]
Linked to #708
