### ISSUE TITLE
[Header] Changing the route manually (in the browser address bar) doesn't reload the header.

### ISSUE THREAD

**Issue by JabX** [KleeGroup/focus-components#635]
![yolo](https://cloud.githubusercontent.com/assets/3266897/10888076/6cf02e90-818a-11e5-98dd-8a1fe5fd7643.gif)

Only happens when keeping the same page but with a different id. A route change on another page doesn't trigger the problem.

**Comment by pierr** [comment]
@JabX Do you still have this problem?

**Comment by pierr** [comment]
@plepaisant Can you try to reproduce it ?
@JabX Still an issue?

**Comment by JabX** [comment]
Yes.
Sometimes my action list doesn’t load or update too, but I might be involved somewhere along the road and I have not yet taken the time to properly investigate the whole issue. I’ll come back to you when I have more info.

**Comment by pierr** [comment]
I close it as there is no news since January. Reopen it if you want or have feedback...

**Comment by JabX** [comment]
I forgot about that one, I should have closed it since the issue was of my side. 

For future reference : do not load the cartridge/summary store node on the summary or the cartridge, do it on the main component.
