### ISSUE TITLE
combo box with active/inactive master data value

### ISSUE THREAD

**Issue by Jean-MichelForhan-KLEE** [KleeGroup/focus-components#636]
In view mode, one expects to see data as it is in database. This means displaying inactive entries for master data reference lists.

In edit mode, one expects to select only active entries from a master data reference list.

in order to have this behavior, a dedicated selectFor component that can filter the inactive values when rendering the edit mode is needed

**Comment by sgoretti** [comment]
:+1: 
I am Linkit and I approve this message
