### ISSUE TITLE
[form] Save and Cancel buttons hidden when mouse out of panel

### ISSUE THREAD

**Issue by sebez** [KleeGroup/focus-components#641]
## Actual behaviour

In a panel inside a form :
  * The `Edit` button appears only when the mouse is over the panel => OK
  * I click the `Edit` button and switch to edition mode => OK
  * The buttons are now `Save` and `Cancel` => OK
  * The buttons disappears when the mouse it out the panel => KO

![buttonbardisappear](https://cloud.githubusercontent.com/assets/9380855/10937429/0b06bb30-82f3-11e5-9a00-b9ac6cc0d842.gif)

## Expected behaviour

Once in edit mode in a panel, the buttons should not disappear when the mouse is out the panel.

## Versions
  * focus-core : `0.11.0`
  * focus-components : `0.7.3-5`

**Comment by JoanaDalmeida** [comment]
The fix doesn't seem to cover all of the cases:  we have a form with the property "hasForm" set to False and the buttons disappear when the mouse is out of the section.
The fix should also be applied to sections with the property "hasForm" set to false.
Thank you
@pierbrisson
