### ISSUE TITLE
Dynamic translation in Focus success message

### ISSUE THREAD

**Issue by gideruette** [KleeGroup/focus-components#648]
In a `Focus.message.addSuccessMessage`, I'd like to give some dynamic parameter like

`Focus.message.addSuccessMessage('message.delete.success.', { count: '10'});`

where :

`[...] message: {success: {delete: '\__count\__ items has been successfully deleted'}}}`

But my object parameter is not taken in consideration

I have to use I18n mixin instead  : 

  `Focus.message.addSuccessMessage(i18n.t('message.delete.success.', { count: '1'}));`

**Comment by pierr** [comment]
Ok, this could be an enhancement, however being explicit on i18n is also a good thing. 
This bug is related to focus-core

**Comment by pierr** [comment]
@gideruette don't hesitate to create a pull request on focus core. This is quite easy to implement.

**Comment by GuenoleK** [comment]
Bug due to focus-core
