### ISSUE TITLE
[SelectFor] - hasUndefined:false props is ignored.

### ISSUE THREAD

**Issue by Pandakls** [KleeGroup/focus-components#650]
### Actual behaviour
I was trying to make a selectFor without null value. I made my objet not nullable and add the hasUndefined:false props. But The component still has the 'noSelection' value.

### Expected behaviour
No nullable value in the selectFor component when the hasUndefined:false props is given.

### Tips
According to stan, the following line contains a test that seems to doesn't work :

https://github.com/KleeGroup/focus-components/blob/develop/src%2Fcomponents%2Finput%2Fselect%2Findex.js#L72

### Versions
Focus-core : 0.11.0
Focus-component: 0.7.3-3
Focus-File: 0.1.2

**Comment by pierr** [comment]
Could you add a description ?

**Comment by Pandakls** [comment]
:)

**Comment by Bernardstanislas** [comment]
@Pandakls thank you for the description, it will be fixed in the upcoming release
