### ISSUE TITLE
[page.liste] - TotalCount property in storeList don't seem to be updated

### ISSUE THREAD

**Issue by Pandakls** [KleeGroup/focus-components#651]
### Context
I've made a component that has to listen to a storeList defined this way :

```javascrpt
module.exports = new FocusCore.store.ListStore({identifier: 'AGREMENT'});
```
Listening this way :

```javascrpt
    mixins:[storeBehaviour],
    stores: [
        {store: storeList, properties: ['dataList', 'totalCount']}
    ],
```
### Actual behaviour
During the execution, the dataList is updated with all my items but the totalCount remains Undefined.
### Expected behaviour
totalCount = dataList.length

### Versions
Focus-core : 0.11.0
Focus-component: 0.7.3-3
Focus-File: 0.1.2

**Comment by pierr** [comment]
@Pandakls  Are you sure this is a bug? I thik this is due to your service which may looks like:
`svc().then((data)=> {dataList: data})` instead of `svc().then((data)=> {dataList: data , totalCount : data.length})`.
Maybe you need to see with @Jerom138 in order to add a custom `Parser` in the `fetch` method of your service to read `X-Total-Count` from the header of the HTTPRequest.

**Comment by pierr** [comment]
@Pandakls @Jerom138  I close this issue, dont't hesitate to reopen it If I'm wrong.

**Comment by pierr** [comment]
@Jerom138 Maybe you can copy paste the code from the custom parser in this issue. Thanks

**Comment by Jerom138** [comment]
La modification du service .js, ou mieux la réécriture du parser pour obtenir le totalCount dans le header, est à mon sens, une solution de contournement seulement.
Puisque le composant Focus attend ce format et qu'il est bien renvoyé par les recherches ES, j'ai créé une issue Vertigo pour voir si on ne pourrait pas obtenir ce même format de retour sur les webservices de retour de recherche hors ES...

**Comment by Jerom138** [comment]
[Réponse de Vertigo](https://github.com/KleeGroup/vertigo/issues/40) : "a discuter avec Focus."

Peux-tu réouvrir l'issus stp, nous n'avons apparemement pas les droits pour les "reopen"...

**Comment by pierr** [comment]
@Jerom138 We will add the parser into the fetch function or we will provide a `listFetch` with the parser.
But this is concidered low priority for us. If you don't agree please let us know.

**Comment by Jerom138** [comment]
:ok_hand:

**Comment by pierr** [comment]
As told in the comment It is no longer an issue.
