### ISSUE TITLE
[list][table] problem on the link to sort column on the table

### ISSUE THREAD

**Issue by obtl** [KleeGroup/focus-components#663]
# Actual behaviour

the click on column header navigate on sort

# Expected behaviour

no navigation on sort. the link must have data-bypass and no href to call the sort handler
# Versions

Focus-core: 0.11.3
Focus-components: 0.7.4

**Comment by Bernardstanislas** [comment]
@obtl can you please try to stick to the [guideline](https://github.com/KleeGroup/focus-docs/blob/master/contribute/DECLARE_ISSUE.md) @Tommass suggested for the issue template ? thank you !

**Comment by Bernardstanislas** [comment]
@obtl any update on the issue description ?

**Comment by obtl** [comment]
+1

**Comment by garnier-f** [comment]
+1

**Comment by giopn** [comment]
:+1:

**Comment by Bernardstanislas** [comment]
@obtl thanks for the description :+1:

**Comment by durandx** [comment]
:+1: :trollface:

**Comment by pierr** [comment]
@obtl @durandx @garnier-f 
Do ypu pass into https://github.com/KleeGroup/focus-components/blob/develop/src/list/table/list.js#L91 ? 
Maybe the cause is https://github.com/KleeGroup/focus-starter-kit/blob/master/app/initializer/index.js#L10 

Can someone try it and provide more context ?
Thanks.

**Comment by obtl** [comment]
@pierr  yes this is the problem. that's why in the description i gave you a solution "the link must have data-bypass and no href to call the sort handler". we have already tested it.
