### ISSUE TITLE
[page][ListPage] the list page should run the load action on modification of the 'sortBy' and 'sortAsc' store attribute.

### ISSUE THREAD

**Issue by obtl** [KleeGroup/focus-components#664]
# Actual behaviour

load action action is not run.

# Expected behaviour

run the load action on store modification for sortBy and sortAsc attribute

# Versions

Focus-core: 0.11.3
Focus-components: 0.7.4

**Comment by Bernardstanislas** [comment]
@obtl can you please try to stick to the [guideline](https://github.com/KleeGroup/focus-docs/blob/master/contribute/DECLARE_ISSUE.md) @Tommass suggested for the issue template ? thank you !

**Comment by Bernardstanislas** [comment]
@obtl any update on the issue description ?

**Comment by obtl** [comment]
+1

**Comment by Bernardstanislas** [comment]
@obtl is it still valid ?

**Comment by pierr** [comment]
I think this is is already the correct behaviour see https://github.com/KleeGroup/focus-components/blob/develop/src/page/list/index.js#L80


Reopen it if you think it is not the case.
