### ISSUE TITLE
[FormMixin] Cancel action in edit mode won't always restore the state.

### ISSUE THREAD

**Issue by Pandakls** [KleeGroup/focus-components#668]
### Context
There's some case where i need to setState() during edition mode to triggers a refresh of the component to made it dynamic without losing all the input above. (for instance : show a date picker if 'CDD' is selected and hide it if CDI is picked)

### Actual behaviour
But because i set the state, when i cancel my edit mode, the saved value are still visible (gone on f5).

### Expected behaviour
Restore the real values when we cancel the edition.

### Versions
Focus-core : 0.11.0
Focus-component: 0.7.3-3
Focus-File: 0.1.2

### Tips
Save the state on 'edit' button in an alternative place and restore it on 'cancel' :)

**Comment by pierr** [comment]
@Jerom138 @Pandakls  Can you provide other context for this bug ?

**Comment by Pandakls** [comment]
### Context
All form with errors catch by server.

### Actual behaviour
Step 1 : Fill a form with an error that will be catch by server
Step 2 : Save (save button) (All the data (including the wrong ones) will be saved in state)
Step 3 : Eat your error from server
Step 4 : Cancel (Cancel button)
Step 5 : Watch your wrong data in the fields that have NOT been saved ans still appears on screen

### Expected behaviour
Restore the state after "Cancel" action

### Versions
Focus-core : 0.11.3
Focus-component: 0.7.4
Focus-File: 0.1.2

**Comment by pierr** [comment]
@Pandakls For the second case, do you use `shouldComponentDumbStore` in your action ?

**Comment by Jerom138** [comment]
Non corrigé.
_preServiceCall(_ref3, payload) renseigne le store avec les nouvelles valeurs saisies dans le formulaire avant le retour du serveur.
L'ajout du setState de _getStateFromStores sur le retour en erreur ne corrige donc pas le bug.

**Comment by Bernardstanislas** [comment]
Caused by https://github.com/KleeGroup/focus-core/blame/develop/src/application/action-builder.js#L26

**Comment by pierr** [comment]
This issue is quite problematic.

- The problem is the status is corelated to the data it should be separated (short term)
- Maybe Redux will solve this issue (long term)
