### ISSUE TITLE
[Radio Button] Behaviour on load and first click is bugged

### ISSUE THREAD

**Issue by Pandakls** [KleeGroup/focus-components#670]
### Context
I met different bugs with classical uses of the radio-button :
Just a classic use of the radio-button component
1)
```javascript
{this.fieldFor('actif')}
with :
    SelectComponent: FocusComponents.common.select.radio.component,
    refContainer: {actifInactifList: [{code: true, label: 'select.actif'}, {code: false, label: 'select.inactif'}]},
    listName: 'actifInactifList'
```
2)
```javascript
{this.fieldFor('partieLimiteZsar', {onChange: this._partieLimiteZsar})}
with :
    SelectComponent: FocusComponents.common.select.radio.component,
    refContainer: {yesNoList: [{code: true, label: 'select.yes'}, {code: false, label: 'select.no'}]},
    listName: 'yesNoList',
    formatter: i18n.t
```
### Actual behaviour
1) On first load, the component seems to be empty, but the actif is checked because even after click nothing changes.
![image](https://cloud.githubusercontent.com/assets/7700690/11116137/d3a49d8a-8930-11e5-973d-0e562848dc3f.png)

2.1) Just after the load, the first click on the radio-button (both on selected or unselected value) is ignored and the second click works well.

2.2) After changing the value of the radio button and press 'Cancel' button the value isn't restored

2.3) I need to evaluate the value of the radio button during edition, with the onChange(value) function. And the value returned that way is the opposite of the selected value. But after save, the evaluation is correct. 

### Expected behaviour
Fix all that tiny bugs that prevent user a full experience on the application

### Versions
Focus-core : 0.11.3
Focus-component: 0.7.4
Focus-File: 0.1.2

**Comment by pierbrisson** [comment]
:+1:

**Comment by tadamK** [comment]
:+1:

**Comment by pierr** [comment]
I think this is the same issue as 
https://github.com/KleeGroup/focus-components/commit/c0ff2450c501f48e6d159c4870d597ebada5f8f3

see https://github.com/KleeGroup/focus-components/issues/614
