### ISSUE TITLE
[Layout, cartridge] Disable, or force enable the fold of header

### ISSUE THREAD

**Issue by Pandakls** [KleeGroup/focus-components#671]
### Context
We've got 3 view where we don't want the header to fold itself.

### Actual behaviour
It folds when the user scrolls down (the scrolls is available even with a really short page donno why)

### Expected behaviour
Set an option on the header to force it unfolded (or folded maybe, it can be useful).

### Versions
Focus-core : 0.11.3
Focus-component: 0.7.4
Focus-File: 0.1.2

**Comment by Bernardstanislas** [comment]
We discussed with the team, and it would be too hard to implement it as of today.
However, we want to push a good way of achieving it.

# Solution

## You want to force the header folded on given routes

```sass
[data-route='yourRoute'] {
    [data-focus='header-content'] {
        display: none;
    }
}

header[data-route='yourRoute'][data-focus='header-scrolling'] div[data-focus='header-top-row'] div[data-focus='header-top-row-middle'] {
    display: inline-block;
}
```
