### ISSUE TITLE
[Date] onChange event is not working properly

### ISSUE THREAD

**Issue by durandx** [KleeGroup/focus-components#673]
When I use the onChange event with direct keyboard input in the text field the onChange event is called with the new date. When I choose a date with the date picker, the event parameter is pushed with the old value. I have to choose again the same date to have the new value.

**Comment by Bernardstanislas** [comment]
Which version are you using ?
For your issue description, please follow [the guidelines](https://github.com/KleeGroup/focus-docs/blob/master/contribute/DECLARE_ISSUE.md) pushed by @Tommass to make it easier for us to treat it.

**Comment by Bernardstanislas** [comment]
I think your issue is a duplicate, and has been fixed [here](https://github.com/KleeGroup/focus-components/pull/628) and delivered [there](https://github.com/KleeGroup/focus-components/releases/tag/v0.7.4).
I'm waiting for you confirmation before closing it.

**Comment by durandx** [comment]
Yep you're right :metal:
