### ISSUE TITLE
[Autocomplete] Results return by WS are filtered by the Autocomplete field

### ISSUE THREAD

**Issue by sebez** [KleeGroup/focus-components#674]
## Actual behaviour

It seems that the autocomplete field filters the results returned by the autocomplete web service.

In a form, I use an field with autocomplete :

``` javascript
{this.fieldFor('codeApeCode', {
    codeResolver: structureServiceRead.loadCodeApe,
    searcher: structureServiceSearch.searchCodeApe,
    allowUnmatchedValue: false,
})}
```

Server side, an ElasticSearch handles full text searches : the result should contain words that begins with the word of the input.

I have a record `culture du tabac`

`culture`, `tabac`, `culture tabac`, `tabac culture`, `cult tab`, etc., should return the result.

In my example :
  * `culture` => OK
  * `tabac` => OK
  * `culture tabac` => KO

![autocompleteerror](https://cloud.githubusercontent.com/assets/9380855/11124079/5848d6e6-8963-11e5-971b-c1777c76439c.gif)

When I look at network, the web service did return the record `culture du tabac`.

![networkautocomplete](https://cloud.githubusercontent.com/assets/9380855/11124177/05553bcc-8964-11e5-8441-f87dce7576e9.gif)

So I conclude that the SPA filters the results itself (without ElasticSearch full text features) and removes results => KO

## Hack

In this file : 

https://github.com/KleeGroup/focus-components/blob/master/src/common/autocomplete/awesomplete.js

We can hack the the `componentDidMount` function by giving a filter to the Awesomplete API :

``` javascript
this._awesomeplete = new Awesomplete(ReactDOM.findDOMNode(input), {
    list: this._extractListFromData(pickList)
});
```

``` javascript
this._awesomeplete = new Awesomplete(ReactDOM.findDOMNode(input), {
    list: this._extractListFromData(pickList),
    filter: () => true
});
```

Then the result is not filtered => OK.
Nevertheless, the highlight is not displayed => KO.

![autocompletehack](https://cloud.githubusercontent.com/assets/9380855/11124412/265271d6-8965-11e5-8ac1-633fa09fbf3f.gif)

## Expected behaviour

  * the results returned by the WS should not be filtered again by the SPA.
  * the highlight should work in every case (perhaps another issue is needed for this)

## Versions 

  * Browser : Chrome
  * `focus` : 0.11.0
  * `focus-components` :  0.7.3-5

**Comment by sebez** [comment]
:+1:

**Comment by oussony** [comment]
:+1:

**Comment by JabX** [comment]
:+1:

**Comment by pierbrisson** [comment]
:+1:

**Comment by Ephrame** [comment]
:+1:
