### ISSUE TITLE
[Services] rename body properties

### ISSUE THREAD

**Issue by TomGallon** [KleeGroup/focus-components#678]
# Actual behaviour

Properties given to services are not clearely named.

![image](https://cloud.githubusercontent.com/assets/5349745/11150791/0a22b406-8a2a-11e5-8371-642cc812b630.png)

# Expected behaviour

Give clear names to properties like : urlData / bodyUrl...

# Versions

Focus-core: 0.11.2
Focus-components: 0.7.4

**Comment by pierr** [comment]
in fact as we did on extensions( notifications and comments) maybe it is easier to use fetch api in most of the cases. See https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API . The only problem with it is that there is no event for partial callback and it is not cancellable. But in most case it will be better to use it.

**Comment by Bernardstanislas** [comment]
@pierr fully agree with you
