### ISSUE TITLE
[Cartridge - suggestion] Extend the cartridge configuration mixin.

### ISSUE THREAD

**Issue by JabX** [KleeGroup/focus-components#686]
Right now, as of Core 0.11 / Components 0.7.4, the cartridgeConfiguration mixin only supports a subset of the possible configuration updates of the cartridge. There are a few parts of the header/cartridge that can only be set and update through a direct `handleViewAction()` call, such as the `BarRight` component for instance (`BarLeft` can be updated though).

My first suggestion would be then to update the cartridgeConfiguration mixin to full support the whole range of supported header/cartridge updates.

In addition, by default, the header has two (or three?) sizes: small, medium (and large?). There is currently no way to remove this behaviour, like #671 would want. There is a `sizeMap` that is supposed to control how the switching between the sizes should work, but I'm not sure it works as it should as I didn't (and others didn't either) manage to achieve the #671 wanted behavioue with it.

My second suggestion would be to rework the way the sizeMap works (and add it to the cartridgeConfiguration of course) to be a list of desired sizes with their attributes, like this for instance:

```javascript
sizeMap = [
    {
        name: 'small',
        height: '100px',
        displayWhenScrollInRange: [300, 1000]
    },
    {
        name: 'medium',
        height: '300px',
        displayWhenScrollInRange: [0, 300]
    }
]
```

That could also be used to solve the 'zigwigwi' issue since changing the `sizeList` could prevent the behaviour from happening.

Third suggestion: it would be awesome if we could define a default cartridge/header in the layout initialization, and that for each parameter that isn't provided in the cartridgeConfiguration the default value is taken instead of nothing/the previous value.

.

**Comment by Tommass** [comment]
@JabX please respect the CONTRIBUTING guidelines https://github.com/KleeGroup/focus-components/blob/develop/CONTRIBUTING.md

**Comment by Tommass** [comment]
Feel free to push a pull request :)
