### ISSUE TITLE
Autocomplete refactor

### ISSUE THREAD

**Issue by Bernardstanislas** [KleeGroup/focus-components#688]
# Autocomplete specification

As discussed with @remigrange @JoanaDalmeida @durandx @JabX @Pandakls @pierr @Tommass, here is what has been agreed.

There will be **two components** for the autocomplete :
 - One is the equivalent of a **select**, with a dynamic list of selectable *options* fetched from a server.
 - The second is an inproved **text input** with a dynamic list of *suggestions* fetched from a server.

### Dynamic select

```jsx
<AutocompleteSelect
    querySearcher={querySearcher}
    keyResolver={keyResolver}
    value={value} keyName='key'
    labelName='label'
    onChange={onChange}
    {...otherProps}
/>
```

 - `querySearcher` : a function that will be called by the component with a `query` argument (the user input), and which must return a `Promise` giving the object
```javascript
{
    data: [{key: 'key', label: 'label'}, {...}],
    totalCount: XXX
}
```
 - `keyResolver`: a function that will be called by the component with a `key` argument (the currently selected key), and which must return a `Promise` giving the resolved `label` associated to the provided `key`

#### Requirements

- If the `value` prop is set, it is resolved by calling the `keyResolver` prop (the 'value' work is used everywhere in forms, it might lead to confusion here since it is in fact a key)

### Input suggestion

```jsx
<AutocompleteText
    querySearcher={querySearcher}
    value={value}
    onChange={onChange}
    {...otherProps}
/>
```
 - `querySearcher` : a function that will be called by the component with a `query` argument (the user input), and which must return a `Promise` giving the object
```javascript
{
    data: ['suggestion1', 'suggestion2', ...],
    totalCount: XXX
}
```

## Common requirements

- the components should handle the `isRequired` prop
- the components should raise errors in case of validation failure, controled by the `domain`'s `validator`
- the server calls should be throttled, to avoid overwhelming it when the user is typing in the field

## Inspiration

![img_0138](https://cloud.githubusercontent.com/assets/4435377/11242718/c4e287b2-8e03-11e5-83c9-e1c133ae6e71.JPG)

## Future evolutions

- highlight handling with ElasticSearch backends
- scrolling in the suggestions/options list, with partial loading from server

**Comment by sebez** [comment]
:+1:

**Comment by pierr** [comment]
:100:

**Comment by pierbrisson** [comment]
:+1:

**Comment by pierr** [comment]
@remigrange asks for two other behaviours:

## What's wanted

- Add infinite scroll on autocomplete results (ie pagination)
- Be able to customize the auto complete rendering 

## Proposition 1

- According to me there are not so many cases where the user will have too many suggestions in its autocomplete. The only case is when he starts typing in the input, what he has to to is be more precise in its query. What you can do (in this specific case) is send from the server  a large number of result  `200` and add a scroll in the component using CSS.(it does not change the specification of the component). In the too many result case, the component should display a too many results, please complete your query. I think this will solve alomost all comlex cases

- The second demand, is a little more touchy. I think it is a really specific case (maybe a special autocomplete). We intend to have a really simple component for the auto complete. What you can do is customize the text of the suggestion on the server side when you build the response or on the client side.  You can do a custom list component for this case (a simple `<ul><li></li></ul>` where you put all what you need in the rendering. If I am wrong please don't hesitate to detail your demand. We can help you to build the suggestion for this case.

## Proposition 2 (not the easiest)

I think you demand came from the use of [select2](https://select2.github.io/), you can build a simple wrapper around it. But as it is a jQuery plugin the integration may be a pain. I wouldn't do it. I think the `AwesomePlete` autocomplete will work in most of your cases.
