### ISSUE TITLE
[Components] Check function unmount presence and name, such as  "componentWillUnmount"

### ISSUE THREAD

**Issue by Jerom138** [KleeGroup/focus-components#701]
Je pense qu'il faut vérifier tous les composants : je trouve 26 fois "UnMount" dans les sources et 32 fois "Unmount" (en respectant la casse).
En fait, j'imagine qu'il faut en profiter pour repasser sur tous les composants pour checker si il n'y a pas eu d'autres oublis de "componentWillUnmount"...

**Comment by Jerom138** [comment]
Au dela du replaceAll ou du nommage correct (éventuelle règle eslint), je pense qu'il faudra faire une passe sur les composants pour vérifier si n'y aurait d'autres oublis.

**Comment by Jerom138** [comment]
Désolé mais je ne peux pas prendre le sujet Thomas. Il s'agit de repasser sur les composants, et pour chacun non seulement de vérifier si la méthode "componentWillUnmount" est présente (et orthographier correctement !) mais surtout de vérifier son contenu, pour que chaque composant soit correctement libéré lorsqu'il nest plus utilisé (j'ai mis le doigt sur ce problème suite à l'absence sur le composant List qui du coup reste en zombie avec un listener qui déclenche des appels serveur dès que le store est modifié).
Je pense qu'il faut parfaitement connaître tous les composants pour savoir ce qui doit être fait dans chaque méthode componentWillUnMount, pour chaque composant.
C'est un boulot pour @pierr (sorry Pierre)

Et au dela de ça, étant donné les conséquences sur le comportement et sur les perf des applis, je me demande si l'on ne pourrait pas imaginer une façon de vérifier qu'on ne laisse pas trainer ce genre de zombies...

**Comment by Tommass** [comment]
Ok. on va en discuter. Et voir quel outils ou règle on peut mettre en place pour vérifier ce genre de choses.

**Comment by pierr** [comment]
Cette issue fait suite à la PR #700 voir la discussion sur cette PR.

**Comment by pierr** [comment]
@Jerom138 pas de problème, c'est juste que comme tu l'avais identifié je te proposais de le faire. Mais tes arguments pour le faire sont complètement justifié. Merci.
