### ISSUE TITLE
[Menu] If header is in full size, clicking on an item in the left menu doesn't display the right bloc.

### ISSUE THREAD

**Issue by JulienGard** [KleeGroup/focus-components#740]
Actual behaviour
-----------------------------------------------
 If header is in full size, clicking on an item in the left menu doesn't display the right bloc(the scroll is too low). 
This error doesn't exist when the header is in the "scroll state".
(see the file in attachement)

Expected behaviour
-----------------------------------------------
An item in the left menu must display the right bloc everytime.

Versions
-----------------------------------------------
Focus : 0.7.5
![error left menu](https://cloud.githubusercontent.com/assets/1950825/11472753/09e8212c-976f-11e5-9bf1-e7809ca86ad0.gif)

**Comment by pierbrisson** [comment]
:+1:
