### ISSUE TITLE
[Button] Have the label displayed on hover when an icon is set

### ISSUE THREAD

**Issue by sgoretti** [KleeGroup/focus-components#741]
### Current behaviour
When an icon is set, the icon is displayed and the label ignored.

### Expected behaviour
When an icon is set AND the label has been defined by a good-willing developer, have the icon displayed, and have the label displayed in a tooltip on hover (by preference not a standard browser tooltip, but a nice-looking one (Qtip2-like))

**Comment by TomGallon** [comment]
done here https://github.com/KleeGroup/focus-components/blob/v2.x.x/src/components/button/index.js
