### ISSUE TITLE
[Responsive] Scroll spy in low resolution

### ISSUE THREAD

**Issue by pierbrisson** [KleeGroup/focus-components#743]
# Current behaviour

When in a small resolution (e.g. 1366px in width), the scrollspy is too far away from the left border and is thus covered by the page's main content

![image](https://cloud.githubusercontent.com/assets/8983628/11496655/a4be7ec2-9813-11e5-8ef0-a4e0a3c75ffb.png)

# Expected behaviour

have it displayed so that the left side of the page is a column which the center column cannot cover over

# Versions
Focus Components : 0.7.5
Focus Core:  0.11.4

**Comment by Tommass** [comment]
Will be corrected with https://github.com/KleeGroup/focus-components/pull/736 in v0.7.8

Please refer to this pull request.
