### ISSUE TITLE
[Placeholder] The placeholder should not be shown by default

### ISSUE THREAD

**Issue by durandx** [KleeGroup/focus-components#744]
# Actual behaviour
The placeholder is shown by default

![image](https://cloud.githubusercontent.com/assets/9220437/11503992/6863d0fa-9843-11e5-8561-eac6126bfcbb.png)
![image](https://cloud.githubusercontent.com/assets/9220437/11504169/432c41fe-9844-11e5-816b-4c26e4756d0f.png)

# Expected behaviour

No placeholder by default please (like before).

# Versions

Focus-core: 0.11.4
Focus-components: 0.7.7

**Comment by durandx** [comment]
We stil have the bug on the SearchBar
![image](https://cloud.githubusercontent.com/assets/9220437/11625578/2f3405e6-9cdc-11e5-8896-99227b85317e.png)

Please, can you reopen this issue ?

**Comment by Bernardstanislas** [comment]
@durandx sorry we missed this one, it was only fixed in the fields

**Comment by Bernardstanislas** [comment]
I've checked and I would like to clarify it. Why don't you set the `placeholder` prop to `''` in the searchBar ?
