### ISSUE TITLE
[Calendar] Hide the calendar popin on blur (and not only on click)

### ISSUE THREAD

**Issue by durandx** [KleeGroup/focus-components#745]
# Actual behaviour
The calendar popin is hidden when a click event is sent, but not when a blur event is sent. 
![popin_calendar](https://cloud.githubusercontent.com/assets/9220437/11504421/8e134a54-9845-11e5-8ec2-2fa71ab8a72e.gif)

# Expected behaviour
Hide the calendar when the user go to another field with the TAB key (blur or focusout event).

# Versions

Focus-core: 0.11.4
Focus-components: 0.7.7

**Comment by sebez** [comment]
:+1:

**Comment by Bernardstanislas** [comment]
It won't be possible to listen to the blur event since a click in the calendar (changing the month for example) will trigger the blur.
However we will add a listener on the `tab` key.

**Comment by durandx** [comment]
The calendar is working this the 'tab' key. But it is not working when I hit the  'enter' key (the calendar is still opened).

Can you please reopen this issue ?

**Comment by Bernardstanislas** [comment]
I don't think it's the same issue, since you asked for a calendar closing on the input blur. By default, an input field is not blurred when we you hit enter. 
If you want this behavior on the date input, please open an issue accordingly.
