### ISSUE TITLE
[Header Action], className props not handled correctly

### ISSUE THREAD

**Issue by Pandakls** [KleeGroup/focus-components#751]
### Context
I just want to put some style on one of my action button bu not the others

### Actual behaviour
I can send to the component a props "className" but it's handled strangely : 
![image](https://cloud.githubusercontent.com/assets/7700690/11508538/9ef2c9b2-9859-11e5-9d75-f680e55d7020.png)

### Expected behaviour
Update the class attribute with the parameter that is given by 'className' props

### Versions
Focus-core : 0.11.3
Focus-component: 0.7.4
Focus-File: 0.1.2

### Tips
Change "style: ..." by "className: ..."
https://github.com/KleeGroup/focus-components/blob/111c752913f7c953984d65f290129a63c2ebec87/src/components/layout/header-actions.js#L61

**Comment by Tommass** [comment]
@Pandakls 
I made the correction : className is now set in <button>.
Use className to set the color of the button is not recommand by focus. Please define attribute data-stich='button-green' for example to override the color of your button.
