### ISSUE TITLE
Modularité du résultat de quicksearch

### ISSUE THREAD

**Issue by Ephrame** [KleeGroup/focus-components#771]
Bonjour,

Serait-il possible de rendre modulaire le composant result du quicksearch (I.E. qu'il soit possible de lui donner un result custom en props.) ?

Merci =).

**Comment by Tsj-** [comment]
+1

**Comment by Bernardstanislas** [comment]
:gb: :gb: :gb:

**Comment by Tsj-** [comment]
Here's the english version:

Would it be possible to customize the quicksearch component by giving a custom result using props?

**Comment by Bernardstanislas** [comment]
Tu peux récupérer `quickSearch` en tant que mixin, et override la méthode `_renderResults`, ça te laissera le loisir de faire ce que tu veux

**Comment by pierr** [comment]
Propose a PR
https://github.com/KleeGroup/focus-components/blob/develop/src/page/search/quick-search/index.js#L156

**Comment by pierr** [comment]
@Ephrame , any chance to have a Pull Request?

**Comment by Tommass** [comment]
@Ephrame : Any PR ?

**Comment by Ephrame** [comment]
I know, but the delivery have taken all my time.

**Comment by TomGallon** [comment]
it has be done
