### ISSUE TITLE
[cartridgeBehaviour] Allow the cartridgeConfiguration to be updated

### ISSUE THREAD

**Issue by durandx** [KleeGroup/focus-components#776]
# Actual behaviour

The actual mixin cartridgeBehaviour does not allow a change in the cartridge configuration once read.

# Expected behaviour

Please add a way to latter change the configuration of the cartridge (maybe with a store...).
The use case is the following : The primary and secondary actions displayed are linked to the state of an object. When we change the state of this object (in a popin for example), there is no way to update those actions in the detail page.

# Versions

Focus-core: 0.12.0
Focus-components: 0.7.9-rc2

**Comment by Bernardstanislas** [comment]
Actually it does, just call `this._registerCartridge()`
