### ISSUE TITLE
[SelectionLine] Render the line selectable dynamically

### ISSUE THREAD

**Issue by remigrange** [KleeGroup/focus-components#777]
Add a  ```isSelection``` attribute in the state on le line component
Do not initalize it with ```this.props.isSelection``` property in the the ```getInitalState``` because this value will be defined if necessary in the ```getInitalState``` methode of the p^roject line component.

**Comment by sgoretti** [comment]
:+1:

**Comment by Pandakls** [comment]
:+1:
