### ISSUE TITLE
[ConfirmPopin] Add a simple confirm popin component

### ISSUE THREAD

**Issue by remigrange** [KleeGroup/focus-components#778]
Can you add a simple confirm popin component

**Comment by pierr** [comment]
`confirm('y message').then(_onSuccess, _onFailure)` or `confirm(<MyComponent />).then(_onSuccess, _onFailure)`

**Comment by pierr** [comment]
@remigrange @Hauwkins the last link is an example

**Comment by pierr** [comment]
`npm i focus-core@0.12.1-rc3 focus-components@0.7.10-rc4 -S`
