### ISSUE TITLE
[Spinner] Spinner do not display

### ISSUE THREAD

**Issue by remigrange** [KleeGroup/focus-components#779]
The spinner do not display whgen load/save...

**Comment by pierbrisson** [comment]
:+1:

**Comment by sebez** [comment]
:+1:

**Comment by pierr** [comment]
Breakpoint here https://github.com/KleeGroup/focus-components/blob/develop/src/common/mixin/store-behaviour.js#L48

**Comment by Tommass** [comment]
Linked to #618
