### ISSUE TITLE
[IE compatibility] My application doesn't run on IE10

### ISSUE THREAD

**Issue by xuaveneg** [KleeGroup/focus-components#789]
Hi,
When I try to load the application on IE10, I have an error message : "Promise is undefined".
Then, the home page is displayed correctly, without any material icons ... And when I click on a button, nothing happens.

**Comment by pierr** [comment]
I think the problem is because you don't require `native-promise-only` which is installed with the starter kit. It has to be called in the index.js of your application.

Do you use webpack or brunch to build the sources?

**Comment by xuaveneg** [comment]
I use webpack.

**Comment by pierr** [comment]
check the index of your application you need to have an `import 'native-promise-only'` at the top of it in order to trigger the polyfill for `Promise` on IE.

**Comment by xuaveneg** [comment]
Now it loads correctly, but my material icons still aren't displayed, and I can't type in any textareas in IE

**Comment by pierr** [comment]
Search in github issues there is the answer to your question

**Comment by xuaveneg** [comment]
Hi, once again my application doesn't work at all on IE10.

The home page is well displayed, but I can't click on any buttons either in my header or in my left menu.

It works well on Firefox and Chrome.

**Comment by xuaveneg** [comment]
I passed the NODE_ENV to "production", and it works again.
