### ISSUE TITLE
[Layout] Add "data-route" attribute on the layout.

### ISSUE THREAD

**Issue by JoanaDalmeida** [KleeGroup/focus-components#793]
# Actual behaviour

I would like to add background image on the layout in some pages of the application.
To do this I use the data-route attribute. 
Right now, the data-route attribute is defined on the header. 
```html
<header data-focus="header-scrolling" data-mode="consult" data-size="medium" data-reactid=".0.3" data-route="equipment-detail">
```
Can you add this attribute on the Layout?

# Expected behaviour

data-route attribute on Layout

# Versions 

Focus-core : 0.12.0
Focus-components : 0.7.9-1

**Comment by Tommass** [comment]
@pierr

**Comment by Tommass** [comment]
i agree with Joana. This demand make sense.

**Comment by Bernardstanislas** [comment]
Actually you can do it with a [CSS sibling selector](https://developer.mozilla.org/fr/docs/Web/CSS/Adjacent_sibling_selectors) since the route is at the root of the header. This way you can achieve what you describe in the issue

**Comment by Tommass** [comment]
Not possible with siblings as layout is a Parent.

**Comment by Bernardstanislas** [comment]
I think it's just that the background image should be applied to the page itself rather than the Layout which consists in the page, the menu and the header. If I understand correctly the aim is to put a background image in the page here, I think you can do it with siblings

**Comment by pierr** [comment]
If siblings works, I think it is a better option because adding data-route on the layout will cause a complete app rerender instead of just the header. The main problem is that the page content is rendered using a ReacDOM targeting the page content DOM node in the router. I agree with the use of this but if CSSworks here it is an easier option. I think there is an example in a menu issue with code targeting the current active menu using data-route.

**Comment by Tommass** [comment]
Ok i was wrong. It should work with siblings. But It is quite weird that the data-route attribute which represente a theme page is defined on the header. Re-rendering the entire page is a good argument.

**Comment by Bernardstanislas** [comment]
That's right, the good semantic would be to have the route also on the page content as you said.

**Comment by pierr** [comment]
I think we all agree on what would be the best, we will be able to do so when moving from backbone router to react redux router. The whole app state will be in a single store it will be much easier to to so. Morover using siblings is the easiest thing to do now.
