### ISSUE TITLE
[Search] Highlight search input in results

### ISSUE THREAD

**Issue by pierbrisson** [KleeGroup/focus-components#794]
# Current behavior

The search results are displayed plainly 

# Expected behavior

Within the search results, highlight the text which the user entered as a search

![image](https://cloud.githubusercontent.com/assets/8983628/11777335/20ee8836-a24e-11e5-9620-ba3deb88ef6b.png)

**Comment by sgoretti** [comment]
:+1:

**Comment by TomGallon** [comment]
@pierbrisson it will be implemented in v3.x.x on focus, in focus-search lib.
it should be possible to use this lib in your project.

https://github.com/get-focus/focus-search/issues/31

**Comment by TomGallon** [comment]
This issue was moved to get-focus/focus-search#45

**Comment by TomGallon** [comment]
will be done in v3 http://github.com/get-focus/focus-search
