### ISSUE TITLE
[StickyMenu] Give better information to your users.

### ISSUE THREAD

**Issue by Pandakls** [KleeGroup/focus-components#802]
### Context
The sticky menu is used in all our Detailpage. Handy and cool stuff thanks to Focus. 

### Actual behaviour
The sticky menu sets the active label on the div on top of screen. Here the visualisation :
![image](https://cloud.githubusercontent.com/assets/7700690/11808089/9aa8a3e8-a31e-11e5-91b5-c0c679ba64c4.png)

Here some screens that tickles me a bit : 
![image](https://cloud.githubusercontent.com/assets/7700690/11808136/e7cc0192-a31e-11e5-9a88-5761355fccb4.png)
I think that in this configuration the user is watching the Agrément block, and the one above is highlighted.

![image](https://cloud.githubusercontent.com/assets/7700690/11808246/8568fe5a-a31f-11e5-9314-4facdafa1061.png)
In this configuration, the user just clicked on the LAST item in the sticky navigation, so he's watching the last block. And the one highlighted is 3 block above !! First he's deconcerted because the buttons doesn't highlight on click. Secondly, the block highlighted is bearly visible and can create confusion. (We have several mantis from the client that really don't find this behaviour natural : 
"Mauvais lien hypertexte sur les onglets "Lien avec l'entreprise" et  "Justificatifs" dans le menu de navigation DHSB"
"Mauvais lien hypertexte sur l'onglet  "Justificatifs" dans le menu de navigation de création d'une demande de TCA"
"Absence des liens actifs suite aux clics sur les champs "Agréments" et "Correspondant Sureté"  dans le menu de navigation.")

### Expected behaviour

1 - First of all, set the detection level in the middle of the screen ! Really small blocks are rare so it won't disturb the actual behaviour (highlight on click). And when the user click on a link, if the detection level is in the middle of the screen, the right link will be highlighted so that the good one when scrolling.
2 - On click, FORCE the active label on the one clicked, even if the scroll doesn't fit. And when the user will scroll, he doesn't gives a shit anymore of his previous selection ! (This case is only to handle too small blocks at the end of the screen, but regarding the actual conception of the component, EACH page got small section at the end and NO ONE of our detail page ever gets it's latests block highlighted.)

### Versions
"focus-components": "^0.7.10-rc4",
"focus-core": "^0.12.1-rc3",
"focus-file": "^0.1.2",

### Tips
Level detection should be at level of eyes on a screen : 2/5 without navigation on top : 
![image](https://cloud.githubusercontent.com/assets/7700690/11808403/adc4feb6-a320-11e5-84b6-9e16c6303f5f.png)
You set your detection around this limit where the user never watchs !
Here you wan't to place your detection : 
![image](https://cloud.githubusercontent.com/assets/7700690/11808575/973f1bee-a321-11e5-97c0-114d5d52b6e0.png)

**Comment by Bernardstanislas** [comment]
Impressive description :+1:

**Comment by sgoretti** [comment]
Would it be possible to have a class added to the block when clicking on the link, with a fading effect (for example, when I click on the last item, the screen scrolls to the bottom, and the last block's border turns blue, and fades slowly back to its original color)
This can be done easily (each block has its selector), just need to add/remove some css class with some 5s timer, and it will improve usability since the user has a clue to indicate the content he/she was looking for.

I think we need to have this idea checked with the UI experts to make sure I'm not saying anything stupid :)
(other request : motion design to slide to the block instead of using the anchor which teleports the page down)
