### ISSUE TITLE
[MessageCenter] Display application messages in a more snackbar-like way

### ISSUE THREAD

**Issue by pierbrisson** [KleeGroup/focus-components#804]
# Current behavior

Currently, application messages are displayed in the upper right hand of the user's screen.
however that space will be used by notification messages too.

![image](https://cloud.githubusercontent.com/assets/8983628/11810201/a9a34a66-a32c-11e5-8b51-7a9e4d9e5505.png)

# Expected behavior

Display application messages in a more snackbar-like way, at the bottom of the screen 
http://www.material-ui.com/#/components/snackbar

**Comment by pierr** [comment]
:+1:

**Comment by pierr** [comment]
Fixed in https://github.com/KleeGroup/focus-components/pull/986
