### ISSUE TITLE
[SelectionLine][checked] Unchecked line impossible in infiniteScroll popin

### ISSUE THREAD

**Issue by JRLK** [KleeGroup/focus-components#820]
![bug_selectionline_check](https://cloud.githubusercontent.com/assets/13674778/11931895/87a876a6-a7f1-11e5-93ae-efda506b6052.gif)

Focus-Core v0.12.1
Focus-Components v0.8.0-rc1

I use a selectionList in a infiniteScroll List.
If I check a line before rendering all the list, I cannot unchecked this line.

**Comment by pierr** [comment]
@JRLK Can you put a break point in https://github.com/KleeGroup/focus-components/blob/develop/src/list/selection/list.js#L100 and tell me what is inside `newSelectedItems` and `selectedItems`

**Comment by JRLK** [comment]
With version 0.12.4 of FocusComponents we have the folliwing behaviour :

- Before restarting the search with "Afficher tous" button:
 - selectedItems => Map(object as key, bool as value) with the lines previously selected or unselected
 - newSelectedItemps => Map(object as key, bool as value) updated
- After restarting the search with "Afficher tous" button:
 - selectedItems => Map(object as key, bool as value) reset with the list returned by server
 - newSelectedItemps => Map(object as key, bool as value) updated

The map `selectedItems` isn't preserve when the list is updated

**Comment by JRLK** [comment]
![image](https://cloud.githubusercontent.com/assets/13674778/14111376/bc6a39ca-f5ca-11e5-8f0f-767ff7da5a77.png)

`selectedIems` was cleared by our code in order to have only on _instance_ of each line.

The problem is :
- the `Map` `key` is the data and even if the two objects are equal the reference is not the same and the `===` operator is `false`

**Comment by pierr** [comment]
![image](https://cloud.githubusercontent.com/assets/286966/14112491/2b85a8e0-f5cf-11e5-80f0-d0e91075a15d.png)

**Comment by Bernardstanislas** [comment]
@pierr maybe not using a `Map` would help... wondering who did this :disappointed_relieved:
