### ISSUE TITLE
[Block] Prevent multiple actions call

### ISSUE THREAD

**Issue by durandx** [KleeGroup/focus-components#823]
# Actual behaviour

Action bar is not blocked when a request is sent to the server.
So, when a user double click on confirm in the block bar, data is sent multiple times to the server.

# Expected behaviour
Prevent the block to sent another request until completion of the first request.

# Versions

Focus-core: 0.12.0
Focus-components: 0.7.9-rc2

**Comment by pierr** [comment]
A block is blocked with data loading attribute and prevents click to other button. You action should set loading to true.

**Comment by Tommass** [comment]
@durandx does @pierr 's answers solved your issue ?

**Comment by durandx** [comment]
We use a standard action (build with actionBuilder), standard block, and standard service call...

**Comment by Tommass** [comment]
linked to #618 and #779
