### ISSUE TITLE
buttons without icons are now messed up

### ISSUE THREAD

**Issue by pierbrisson** [KleeGroup/focus-components#828]
# Current behavior

Following the Focus version 0.8.3 update, buttons' content is now off by several pixels (1 em = 24px)
Seems like the CSS class material-icons' width has been modified

![image](https://cloud.githubusercontent.com/assets/8983628/11978425/dae399ae-a98b-11e5-8774-eb691c37c23b.png)

# Expected behavior

![image](https://cloud.githubusercontent.com/assets/8983628/11978515/6c4f356a-a98c-11e5-860b-ff7f4943c702.png)

Add a property allowing to determine whether an icon is present or not on the button.

# Version
FocusComponents: 0.8.3
FocusCore : 0.12.1

**Comment by pierbrisson** [comment]
This is critical please

:+1:

**Comment by Tommass** [comment]
ok, i do it now.
