### ISSUE TITLE
[Autocomplete fields] Domain validator 

### ISSUE THREAD

**Issue by FabG11** [KleeGroup/focus-components#829]
## Current behaviour
Domain validation operation on autocomplete fields isn't complete.

## Expected behaviour
Domain validation operation on autocomplete fields display :
- Red label
- Red message

## Versions
Focus-core: ^0.12.0
Focus-components: 0.7.9-rc2

**Comment by Bernardstanislas** [comment]
This has been fixed with the [refactored autocomplete component](https://github.com/KleeGroup/focus-components/tree/develop/src/components/input/autocomplete-select).
Feel free to comment if it's not solved with this one.
