### ISSUE TITLE
[Advanced Search][Enhancement] Make the advanced search header sticky when scrolling

### ISSUE THREAD

**Issue by pierbrisson** [KleeGroup/focus-components#830]
# Current behavior

When scrolling in the advanced search, the header containing the filter tags and action buttons (sort, group, select) and project action buttons (add to cart and export in below GIF) disappear when scrolling through the results.

![focus_advanced_search_sticky_header](https://cloud.githubusercontent.com/assets/8983628/12017936/1ddaeb52-ad5d-11e5-8239-92973f43d57a.gif)

# Expected behavior

Have the header be present at all times when scrolling through the advanced search results

**Comment by TomGallon** [comment]
This issue was moved to get-focus/focus-search#44
