### ISSUE TITLE
[Sorting List] Mark the sorting criteria

### ISSUE THREAD

**Issue by mouffakb** [KleeGroup/focus-components#858]
# Actual behaviour

After sorting the results of a search, there is no way to identify the sorting criteria.

# Expected behaviour

For instance, add a marker in the list of sorting criteria.

# Versions

Focus-core: 0.12.1 
Focus-components:  0.8.4

**Comment by TomGallon** [comment]
https://github.com/get-focus/focus-search/issues/30
