### ISSUE TITLE
[Select All] Simplify Select All

### ISSUE THREAD

**Issue by mouffakb** [KleeGroup/focus-components#860]
# Actual behaviour

![image](https://cloud.githubusercontent.com/assets/16595663/12199623/cd208ac6-b619-11e5-9665-716045345b08.png)

# Expected behaviour

Directly <B><I>Select All </I> / <I>Deselect All </I></B>on click.

# Versions

Focus-core: 0.12.1 
Focus-components:  0.8.4

**Comment by TomGallon** [comment]
https://github.com/get-focus/focus-search/issues/28
