### ISSUE TITLE
[Advanced search][Facet] Error while server response does not contain selected facets

### ISSUE THREAD

**Issue by JoanaDalmeida** [KleeGroup/focus-components#866]
# Actual behaviour
From advanced search, if user selects some facets, and if he changes the search query and in the server response,  there is not one of facets that he previously selected, the application raise an error.

![image](https://cloud.githubusercontent.com/assets/3300779/12234552/1c73021a-b86e-11e5-8890-b9f3a71efcd8.png)

# Expected behaviour
Handle the case which the server response does not contain the selected facets.

# Versions 

Focus-core : 0.12.1
Focus-components : 0.8.4-beta5

**Comment by pierbrisson** [comment]
:+1:

**Comment by sebez** [comment]
:+1:

**Comment by sgoretti** [comment]
:+1:

**Comment by pierr** [comment]
@JoanaDalmeida Can you do a Pull Request ?

**Comment by pierr** [comment]
@sgoretti @JoanaDalmeida can you do a PR for this?

**Comment by Tommass** [comment]
The problem comes from the way you update your advanced-store. It keeps some old values in it... Some old value are gives to the components.

To correct it, you have to dispatch the good value in you advanced store, like this : 

```javascript
Focus.dispatcher.handleViewAction({
            data: {
                facets: [],
                groupingKey: null,
                results: [],
                totalCount: 0
            },
            type: 'update',
            identifier: 'ADVANCED_SEARCH'
        });
```

**Comment by Tommass** [comment]
This is not an issue for us, but a wrong dispatch of you data.
