### ISSUE TITLE
[Quick search] search with scope ALL, wrong result count is displayed if the server response contains one group with results

### ISSUE THREAD

**Issue by JoanaDalmeida** [KleeGroup/focus-components#867]
# Actual behaviour
From quick search, if user searches with scope "ALL"  and if the server response contains only one group with results, the component does not display the right result count. 

![image](https://cloud.githubusercontent.com/assets/3300779/12234923/801cc48e-b870-11e5-9c7f-8df104a526c2.png)

# Expected behaviour
Display the right "result count".

# Versions 

Focus-core : 0.12.1
Focus-components : 0.8.4-beta5

**Comment by pierbrisson** [comment]
:+1:

**Comment by Bernardstanislas** [comment]
I think this has been solved in version 0.13.1, can you please check and notify us if it's still an issue ?
I tried to reproduce but alaways had the correct count.

**Comment by TomGallon** [comment]
fixed in PR #1141
