### ISSUE TITLE
[search] Remove scopeConfig since it should only rely on the scopes ref

### ISSUE THREAD

**Issue by TomGallon** [KleeGroup/focus-components#877]

**Comment by sebez** [comment]
@Tommass Can you follow the [contribting guide for issues](https://github.com/KleeGroup/focus-docs/blob/master/contribute/DECLARE_ISSUE.md). Thanks.

**Comment by pierr** [comment]
@Tommass

**Comment by TomGallon** [comment]
@Ephrame do you confirm we can close it now ?
