### ISSUE TITLE
[Header] Gives up when edition mode changes

### ISSUE THREAD

**Issue by Pandakls** [KleeGroup/focus-components#901]
### Context
A long page (so that you can scroll) with Editable block (so that you can edit stuff).

### Actual behaviour
After scrolling, a simple click on the 'edit' button will set the data-deployed value to false. So the header juste fold as if we were on top of the page (but we're not) hiding itself from our view. 

Rq : after scrolling the header come back.
Rq2: The cancel button acts like the edit button. (to test : scroll during edition then cancel -> no more header!)

### Expected behaviour
The data-deployed shouldn't be changed on neither of the edit or cancel button.

### Versions
    "focus-components": "^0.8.4",
    "focus-core": "^0.12.3",
    "focus-file": "^0.1.2"

**Comment by pierbrisson** [comment]
:+1:
