### ISSUE TITLE
[Internet Explorer]

### ISSUE THREAD

**Issue by pierr** [KleeGroup/focus-components#902]
Copy of @durandx issue on focus core 
https://github.com/KleeGroup/focus-core/issues/297

# Actual behaviour
Fields and grid are not working in IE10 :
IE10 :
![image](https://cloud.githubusercontent.com/assets/9220437/12395018/86ed10e0-bdff-11e5-85b1-56a479209620.png)

In chrome:
![image](https://cloud.githubusercontent.com/assets/9220437/12395046/a023dabc-bdff-11e5-949f-e41ed1118ee3.png)

In a Popin:
IE10:
![image](https://cloud.githubusercontent.com/assets/9220437/12395088/f913be30-bdff-11e5-9a10-5125b31eefaa.png)

Chrome:
![image](https://cloud.githubusercontent.com/assets/9220437/12395113/1e02298e-be00-11e5-9410-d113fcf2bb76.png)

FYI, GMDL should be fully supported in IE 10 (and with graphical bugs in IE 9) :
https://github.com/google/material-design-lite/#browser-support

# Expected behaviour
Please add support to IE10.

# Versions
Focus-core: 0.12.1
Focus-components: 0.8.3

**Comment by pierr** [comment]
Shoud be resolved with `autoprefixer`

**Comment by pierr** [comment]
https://phabricator.babeljs.io/T3041

**Comment by Tommass** [comment]
correction in 0.13.0
