### ISSUE TITLE
[Fields] class is-upgraded/isInvalid is not properly updated

### ISSUE THREAD

**Issue by durandx** [KleeGroup/focus-components#908]
# Actual behaviour

On fields : the classes 'is-upgraded' 'isInvalid' are not properly computed

# Expected behaviour
Please push isInvalid only when the validation failed. And remove it when the validation is valid

# Versions

Focus-core: 0.12.1
Focus-components: 0.8.3

**Comment by pierr** [comment]
@durandx  It seem related to `mdl` behaviour
Do you have this problem on each validation or only in specific cases ?


@JabX @JoanaDalmeida @sgoretti @remigrange Do you also have this problem ?

cc @Tommass @Bernardstanislas
