### ISSUE TITLE
[AdvancedSearch] Regression - Scope should be optionnal in ListSummary

### ISSUE THREAD

**Issue by durandx** [KleeGroup/focus-components#914]
# Current behaviour
When the scope is not define we got an exception in _getScopeLabel of ListSummary
```javascript
return selectedScope.label || this.props.scope;
```
In the previous version, it was working so it's a regression.

# Expected behaviour
Please correct this component to have an optionnal scope or tell us how to fix that.

# Versions

Focus-core: 0.12.3
Focus-components: 0.8.5

**Comment by pierr** [comment]
@durandx can you copy paste your stack trace ?

**Comment by durandx** [comment]
vendor.js:119511 Uncaught TypeError: Cannot read property 'label' of undefined_getScopeLabel @ vendor.js:119511render @ vendor.js:119524y._renderValidatedComponentWithoutOwnerOrContext @ vendor.js:18964y._renderValidatedComponent @ vendor.js:18964y._updateRenderedComponent @ vendor.js:18964y._performComponentUpdate @ vendor.js:18964y.updateComponent @ vendor.js:18964y.performUpdateIfNecessary @ vendor.js:18964a.performUpdateIfNecessary @ vendor.js:18966u @ vendor.js:18966o.perform @ vendor.js:18966o.perform @ vendor.js:18966v.perform @ vendor.js:18966D @ vendor.js:18966o.closeAll @ vendor.js:18966o.perform @ vendor.js:18966d.batchedUpdates @ vendor.js:18965s @ vendor.js:18966r @ vendor.js:18966c.enqueueSetState @ vendor.js:18966r.setState @ vendor.js:18964onFormStoreChangeHandler @ vendor.js:113463EventEmitter.emit @ vendor.js:51257(anonymous function) @ vendor.js:50928emitPendingEvents @ vendor.js:50924(anonymous function) @ vendor.js:51083(anonymous function) @ vendor.js:55920setTimeout (async)baseDelay @ vendor.js:55920(anonymous function) @ vendor.js:55893(anonymous function) @ vendor.js:55255delayPendingEvents @ vendor.js:51082(anonymous function) @ vendor.js:51136_invokeCallback @ vendor.js:49878dispatch @ vendor.js:49854handleViewAction @ vendor.js:49655updateProperties @ vendor.js:71834(anonymous function) @ vendor.js:118364(anonymous function) @ vendor.js:118487setTimeout (async)(anonymous function) @ vendor.js:118486_broadcastQueryChange @ vendor.js:118370_onInputChange @ vendor.js:118382InputText._this._handleInputChange @ vendor.js:85496f.executeOnChange @ vendor.js:18963o @ vendor.js:18964r @ vendor.js:18965i @ vendor.js:18963u @ vendor.js:18963p @ vendor.js:18963f @ vendor.js:18963r @ vendor.js:18966v.processEventQueue @ vendor.js:18963r @ vendor.js:18965a.handleTopLevel @ vendor.js:18965i @ vendor.js:18965a @ vendor.js:18965o.perform @ vendor.js:18966d.batchedUpdates @ vendor.js:18965a @ vendor.js:18966g.dispatchEvent @ vendor.js:18965

**Comment by durandx** [comment]
Pouvez-vous ajouter le label Critical sur cette issue ?

**Comment by Tommass** [comment]
fixed in this PR : https://github.com/KleeGroup/focus-components/pull/943
