### ISSUE TITLE
[AdvancedSearch][Internet Explorer]search screen not displaying due to "find" in store

### ISSUE THREAD

**Issue by sgoretti** [KleeGroup/focus-components#916]
### Current behaviour

In IE the search screen can't be reached

![image](https://cloud.githubusercontent.com/assets/14293391/12611610/e8e28c5e-c4ed-11e5-9926-243fdca3efcc.png)

### Expected behaviour

Being able to use the search just as in other browsers.

### Guilty party

https://github.com/KleeGroup/focus-core/blob/develop/src/store/search/advanced-search/index.js
line 28 : it appears find isn't supported by IE.

/!\ can also be found in the quick-search store

### Versions

Focus-core: 0.12.3
Focus-components: 0.8.5

**Comment by pierr** [comment]
@sgoretti Do you use the `babel-polyfill` ? https://babeljs.io/docs/usage/polyfill/

**Comment by pierr** [comment]
Its putpose is to have all the non existing `ES6` methods on older browser.
The best way to add it is with a conditional comment.

**Comment by pierr** [comment]
Can you tell me if it works when you will have use it?

**Comment by sgoretti** [comment]
Ok, it works. But IE11 don't take conditional imports (< if IE >) so it means adding polyfill for all browsers and have lower performance. 
Do you have an idea how to import it only for IE ?

**Comment by pierr** [comment]
I think it may not apply in our case but here are some links (just to investigate):
- https://addyosmani.com/blog/writing-polyfills/
- use [modernizr](https://modernizr.com)

**Comment by pierr** [comment]
@sgoretti I will create a special isse on polyfill with all these questions to **centralize** the problem and give only one way to solve it.

**Comment by pierr** [comment]
See #922
