### ISSUE TITLE
[AdvancedSearch][Enhancement] Multi-valued facets

### ISSUE THREAD

**Issue by sgoretti** [KleeGroup/focus-components#917]
### Current behaviour

Currently you can only select one value for each facet in a search.

### Expected behaviour

It should be as in all major commercial sites, i.e. being able to select several values for a given facet.
See:
http://distinctplace.com/2014/07/29/build-zappos-like-products-facets-with-elasticsearch/
(change also concerns Vertigo)

### Versions

Focus-core: 0.12.3
Focus-components: 0.8.5

**Comment by pierr** [comment]
It was discussed, we choose to not implement it in order to be able to have a simple behaviour and to deliver it fast.

This was discussed again a few weeks ago, it will exists but I cannot tell you when.
This need to be planned with @NPi2Loup @phlppchrtn 
cc @Tommass @Bernardstanislas

**Comment by sgoretti** [comment]
I'm fine with it not being immediate, it's just that I couldn't find any issue asking for it. And I thought there should be one. And my client asked for it.

**Comment by pierr** [comment]
We will let people comment on this issue to ask for this feature.
Thanks

**Comment by pierbrisson** [comment]
this is me asking for this feature

:+1:

**Comment by TomGallon** [comment]
@sgoretti it will be possible to have multi valued facet in v3.x.x.
It now depends on vertigo. @NPi2Loup

**Comment by TomGallon** [comment]
This issue was moved to get-focus/focus-search#43
