### ISSUE TITLE
[AdvancedSearch][Firefox]search screen not displaying due to "includes" in store

### ISSUE THREAD

**Issue by sgoretti** [KleeGroup/focus-components#919]
### Current behaviour

In Firefox the search screen can't be reached.

![image](https://cloud.githubusercontent.com/assets/14293391/12618905/3dcdfc94-c516-11e5-9123-bda6d6e7b076.png)
(yeah, it looks ugly and big, but zoom is 100%, thanks Firefox and layout.css.devPixelsPerPx)

### Expected behaviour

Being able to use the search just as in other browsers.

### Guilty party

https://github.com/KleeGroup/focus-core/blob/develop/src/store/search/advanced-search/index.js
line 28 : it appears includes isn't supported by Firefox.

/!\ can also be found in the quick-search store

### Versions

Focus-core: 0.12.3
Focus-components: 0.8.5

Yes I copy/pasted #916

**Comment by sgoretti** [comment]
Not tested with polyfill yet.

**Comment by pierr** [comment]
Ok i was going to ask if you use the polyfill or not.
Many methods we use on array are the same as the one in `lodash` but as they are part of `ES6/2015` spec, the may not be in the `Array.prototype`.
Can you try with the polyfill ?

**Comment by pierr** [comment]
@sgoretti I add you to the `focus-contributors` team. Can you accept it ?

**Comment by pierr** [comment]
See https://github.com/KleeGroup/focus-components/issues/922

**Comment by pierr** [comment]
`Array.includes` is in `ES2016` aka `ES7`
https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Array/includes

**Comment by Tommass** [comment]
@Bernardstanislas : do you reproduce it today ? i think it is corrected.
