### ISSUE TITLE
[export] button

### ISSUE THREAD

**Issue by pierr** [KleeGroup/focus-components#92]
https://gist.github.com/Tsj-/e7e050f3a5e27c5cc4c7

**Comment by pierr** [comment]
@Tsj-

**Comment by Tommass** [comment]
get a default button to export in excel the data from the list.

**Comment by pierr** [comment]
@Tommass , it will not be in the next to release, we can let it open until we deal with it.

**Comment by pierbrisson** [comment]
:1:

**Comment by sgoretti** [comment]
:+1:

**Comment by Tommass** [comment]
implemented in projects.
