### ISSUE TITLE
[Scrollspy][Internet Explorer][Firefox] scrollspy errors under both browsers.

### ISSUE THREAD

**Issue by sgoretti** [KleeGroup/focus-components#920]
# Current behaviour

In chrome
![image](https://cloud.githubusercontent.com/assets/14293391/12620131/3f5db158-c51b-11e5-9157-58e5670dcd1e.png)
:+1:

In Firefox:
![image](https://cloud.githubusercontent.com/assets/14293391/12620143/4f021bb2-c51b-11e5-94fa-6e056751510c.png)
:(

In IE:
![image](https://cloud.githubusercontent.com/assets/14293391/12620162/5eb7f84c-c51b-11e5-8643-62902bf24ff9.png)

# Expected behaviour

Chrome behaviour :+1:
(yes I misuse +1)

srollHeight crashes IE, scrollingElement crashes Firefox.

Not tested with polyfill (it's not my project, I can't add it)

# Versions

Focus-core: 0.12.3
Focus-components: 0.8.5

**Comment by sgoretti** [comment]
Crashes even with polyfill on Firefox.

**Comment by pierr** [comment]
Yes we have seen this happens with https://github.com/KleeGroup/focus-components/pull/822

It still works but throw errors.

**Comment by pierr** [comment]
The problem is https://github.com/Pandakls/focus-components/blob/04c381d51cc71dd34eaf41597aaa282b101770ec/src/behaviours/scroll/index.js#L27

`scrollingElement` don't exists on FF and IE 

```
function getScrollingElement(){
if(document.scrollingElement){
return document.scrollingElement
} else(document.scrollingElement) {
    return document.documentElement
  }
  return document.querySelector("body");
}
```
