### ISSUE TITLE
[Browsers] Polyfill and feature detection

### ISSUE THREAD

**Issue by pierr** [KleeGroup/focus-components#922]
## The problem

- Some methods uses [ES6/ES2015](https://babeljs.io/docs/learn-es2015/).

## What can we do to solve this problem

- ES6 :  A **polyfill** is provided by [Babel](https://babeljs.io/docs/usage/polyfill/), we advise to use it in your app using a simple `import 'babel-polyfill/dist/polyfill.js'` or a `require('babel-polyfill/dist/polyfill')`

- Use [Modernizer](https://modernizr.com) in order to do feature detection

**Comment by durandx** [comment]
the babel polyfill ('babel-polyfill/dist/polyfill') is necessary but not sufficient: you will need to add the browser polyfill (browser-polyfill.min.js) in order to fix all IE 10 issues...

**Comment by pierr** [comment]
@durandx Thanks.

**Comment by pierr** [comment]
We answer to these problems with `babel-preset-focus` https://github.com/KleeGroup/babel-preset-focus

**Comment by pierr** [comment]
See https://github.com/KleeGroup/focus-components/releases/tag/v0.13.0
