### ISSUE TITLE
Field Value : Default behaviour (trimming, and empty values)

### ISSUE THREAD

**Issue by Hartorn** [KleeGroup/focus-components#924]
By default, no action is applied to the value of a field (without formatter or anything), when you get.
In case of a string value, shouldn't it be trimmed at least ?

Also, if empty after trim, shoudn't the value be change to null, so it does trigger the validation in case of `required: true` ?

**Comment by pierr** [comment]
@Hartorn 
We use to do something like that but the problem is to be able to turn it off.
Please make a PR with:
It should be a function such as `transform`
  - trim
  - escape
  -..
cc @Tommass @Bernardstanislas

**Comment by Hartorn** [comment]
From what I found, the `_getEntity` in `action-behaviour` does not do any actions on the data, only reading them, so only the 'input'-type components should be targetted no ?

So maybe changing the default formatter and unformatter in the default props would do the job.
And to turn it off, just put `identity` back as formatter and unformatter. 

It depends if you want to disable it globally, or punctually ?

Punctually, you can by giving another formatter/unformatter.
Globally, it would it more difficult : either adding an option to parametrize the behaviour, or creating a custom component extending the default, overloading the formatter.

**Comment by pierr** [comment]
I would have seen something else than a `formatter` maybe a `transform` function which will be called before the formatter`.

**Comment by pierr** [comment]
@Hartorn  PR?

**Comment by tadamK** [comment]
Hello, I revive this topic after this morning meeting.

For the moment, I use a validator which makes the user change its input :

```
export default {
    type: 'function',
    value: data => {
        return data.length === data.replace(/\s\s+/g, ' ').replace(/^\s+|\s+$/g, '').length;
    },
    options: {
        translationKey: 'domain.validation.trimIt'
    }
}
```
It handles the multiple spaces.

It would be great to have them automatically removed.

**Comment by TomGallon** [comment]
@pierr @Hartorn  what do we do with this issue ?

**Comment by JohnnP** [comment]
@Hartorn I think you propably know better than me, if this issue is closed.
