### ISSUE TITLE
[Cartridge,Header, Scroll] Console Log pollution

### ISSUE THREAD

**Issue by Pandakls** [KleeGroup/focus-components#934]
![image](https://cloud.githubusercontent.com/assets/7700690/12720387/e8a26992-c8fa-11e5-9dc8-1a7fabed9153.png)

Can you remove this for the next iteration ? :)

**Comment by Tommass** [comment]
Hello @Pandakls.
Yes, it has to be removed.

Github blames you :)

![image](https://cloud.githubusercontent.com/assets/5349745/12724492/87b6c4f2-c90e-11e5-850f-2efca822883b.png)

Can you please submit a pull request yourself to remove it ?

Thanks a lot.

**Comment by Tommass** [comment]
fixed in this commit : https://github.com/KleeGroup/focus-components/commit/b7a3491dd4f041180d7a07308f89545ac966b78a#diff-47ea64765ca80da6ab8a881e5b6b395d
