### ISSUE TITLE
[search-bar] service props is useless

### ISSUE THREAD

**Issue by Tommass** [KleeGroup/focus-components#942]
## Issue description

In the components ```focus-components/page/search/search-header/cartridge``` and ```focus-components/page/search/search-header/summary```, the ```service``` props is useless.

Talk together and see if it is needed to remove it.

```javascript
// web components
import {cartridgeBehaviour} from 'focus-components/page/mixin';

//cartridge configuration
import CartridgePageSearch from 'focus-components/page/search/search-header/cartridge';
import SummaryPageSearch from 'focus-components/page/search/search-header/summary';
import searchService from '../../services/search';


export default React.createClass({
    displayName: 'HomeView',
    mixins: [cartridgeBehaviour],
    /** @inheritDoc */
    _navigateAdvancedSearch() {
        history.navigate('#search/advanced', true);
    },

    /**
    * Related to the CartridgeBehaviour.
    * Define the cartridge configuration.
    * @return {[type]} [description]
    */
    cartridgeConfiguration() {
        return {
            summary: {
                component: SummaryPageSearch,
                props: { onSearchCriteriaChange: this._navigateAdvancedSearch, service: searchService }
            },
            cartridge: {
                component: CartridgePageSearch,
                props: { onSearchCriteriaChange: this._navigateAdvancedSearch, service: searchService }
            },
            actions: {
                primary: [],
                secondary: []
            }
        };
    },
```

**Comment by pierr** [comment]
@Tommass I think the service is necessary:
See 
https://github.com/KleeGroup/focus-core/blob/30811ee3170a06a6305659920256cf2d7d8e10ca/src/search/search-action/index.js#L59

It could be useless in the case where the user specifies the `searchAction`

**Comment by pierr** [comment]
The service is used here https://github.com/KleeGroup/focus-core/blob/30811ee3170a06a6305659920256cf2d7d8e10ca/src/search/action-builder.js#L26

**Comment by pierr** [comment]
The service props is used here https://github.com/KleeGroup/focus-components/blob/2a0f51a693f94ddab13b93d06c78d490053f4e65/src/page/search/search-header/mixin/index.js#L32 , as mentionned before when the user specifies the search action, the service is useless but there is no warning associated to this information.

**Comment by pierr** [comment]
@Tommass I close this issue if you disagree, reopen it.

**Comment by Tommass** [comment]
treat it here : https://github.com/KleeGroup/focus-demo-app/issues/96
