### ISSUE TITLE
[Form Block] - All errors sent by server triggers a bug

### ISSUE THREAD

**Issue by Pandakls** [KleeGroup/focus-components#966]
### Context
Any form thatv on save, can recieve errors from server

### Current behaviour
Each time we press a 'Save' button on a form that contains errors that is catched and resent by the server, the Block component freezes with the grey "loading" style behaviour. Here some screenshot :
![image](https://cloud.githubusercontent.com/assets/7700690/12921250/9d67d8d8-cf4c-11e5-9316-d687bad41948.png)
![image](https://cloud.githubusercontent.com/assets/7700690/12921264/a7e68a48-cf4c-11e5-922c-3043ecc35574.png)
![image](https://cloud.githubusercontent.com/assets/7700690/12921268/afbbf5e6-cf4c-11e5-8f4d-9e2acade61e5.png)
![image](https://cloud.githubusercontent.com/assets/7700690/12921274/b7778d22-cf4c-11e5-942d-c7369739b907.png)
![image](https://cloud.githubusercontent.com/assets/7700690/12921282/c6c3c908-cf4c-11e5-83cb-1363b816a6f4.png)

As you can see, the bug is produced both with errors on field and global errors. 

### Expected behaviour
No freez when the server send some errors. 

### Versions
    "focus-components": "^0.8.5",
    "focus-core": "^0.12.3",
    "focus-file": "^0.1.2",

**Comment by Bernardstanislas** [comment]
This has been solved in KleeGroup/focus-core#293 and #896 by @gideruette 
Please update your project

**Comment by Pandakls** [comment]
:+1:
