### ISSUE TITLE
[Form] Add a prop in order to clean the store in create mode

### ISSUE THREAD

**Issue by durandx** [KleeGroup/focus-components#969]
# Current behaviour
When a store is loaded with values (ex: a block in consult mode), when we display a block in creation linked to the same store, the old values (values from the consult mode) are still displayed in the block even if we override the initial state.
The only offical way to do it is to clean the store by hand, by dispatching a empty objet in the initial state.

# Expected behaviour
Please add a 'isCreate' props (like the 'isEdit' one) managed by the framework, which will clean the store in this case.

# Versions

Focus-core: 0.12.3
Focus-components: 0.8.5

**Comment by pierr** [comment]
@durandx  you can use the `status` information on the store node and in your action builder in order to achieve this, then you can read the information in your store .

**Comment by pierr** [comment]
There is also a property inside the action builder which is called  `shouldDumpStoreOnActionCall`

https://github.com/KleeGroup/focus-core/blob/30811ee3170a06a6305659920256cf2d7d8e10ca/src/application/action-builder.js#L102
