### ISSUE TITLE
[AdvancedSearch] crash when typing a too restrictive criterion while a facet is selected

### ISSUE THREAD

**Issue by sgoretti** [KleeGroup/focus-components#972]
### Current behaviour
When I filter my search results by selecting a facet, if I want to refine the results using this facet by modifying the search query and end up with no results, an error appears.

![image](https://cloud.githubusercontent.com/assets/14293391/12982726/5252b598-d0e6-11e5-8c11-a464585c42f6.png)
Above is the list of rigs for the type "cementing Fleet".

If I search specifically for a rig with the word "cacahuete" in it while still using this facet value, here's what happens:
![image](https://cloud.githubusercontent.com/assets/14293391/12982761/857d8db2-d0e6-11e5-95dc-2ca41be08cab.png)

Basically, the screens tries to display the selected facet, but it is not returned by the query
![image](https://cloud.githubusercontent.com/assets/14293391/12982783/a442e526-d0e6-11e5-9484-b6fdd2aa1b0b.png)

### Expected behaviour

The selected facets should still be displayed and a message indicating that no results were found should appear.

One could argue that selected facets could be removed in order to match the result set, but I disagree: a user doing a typo would lose all his/her selected facets.

Another point in debate is if this could be done in Vertigo : since the query is both a selected facet and a search, one could argue that the result could contain the selected facet, albeit with a result of 0 hit.

However Focus should be protected against this error and display the selected facet even if they're not in the result of the query.

### Versions

Focus-core: 0.12.1
Focus-components: 0.8.3
(yes, I know these are old versions, but the same happens on the latest version of Trackit)

**Comment by sgoretti** [comment]
yes I take great care in the naming of my issues :)

**Comment by Bernardstanislas** [comment]
Thanks for all the details !
I agree that we _might_ be protected against this, but still this is highly unrelevant to get empty facets from the backend, so maybe the solution would be not to send inconsistent search result.

**Comment by sgoretti** [comment]
What do you mean by inconsistent?
At the moment, the search result is coherent: it return no results and empty facets (since there are no results). If you mean that it should return no facets at all,  I think it would still clash with Focus. (Focus tries to search for the facet value in the search result, so nofacets would crash all the same)

**Comment by pierbrisson** [comment]
is this the same issue as #866 ? 
We still need a resolution for this asap

**Comment by Bernardstanislas** [comment]
@pierbrisson yes I do believe it's the same

**Comment by sgoretti** [comment]
Sorry for the duplicate bug

**Comment by pierr** [comment]
@pierbrisson As suggested in the #866 If somebody (@sgoretti or @JoanaDalmeida ) wants to do a Pull Request, it would be  a `good first bug`

**Comment by pierr** [comment]
I close this bug as it is linked in #866
