### ISSUE TITLE
[Textarea] getValue() return null

### ISSUE THREAD

**Issue by durandx** [KleeGroup/focus-components#973]
# Current behaviour

getValue() returns null when used by the following manner : 

```javascript
this.fieldFor('fieldWithATextareaDomain');
```

# Expected behaviour

Please correct the getValue method.

# Versions

Focus-core: 0.12.3
Focus-components: 0.8.5

**Comment by pierr** [comment]
@durandx Can youn add your domain in the issue, thanks.

**Comment by pierr** [comment]
@durandx  Do you use this component in your domain, can you check the `getValue` inside a breakpoint

https://github.com/KleeGroup/focus-components/blob/develop/src/components/input/textarea/index.js#L52

**Comment by durandx** [comment]
We were using the component under common.input.Textarea instead of component.input.textarea

**Comment by pierr** [comment]
Thanks for the feedback
