### ISSUE TITLE
[Date] Need to be able to deactivate the automatic time zone conversion

### ISSUE THREAD

**Issue by sgoretti** [KleeGroup/focus-components#983]
### Current behaviour
Automatic time zone change : a date is supposedly saved as GMT in the database and converted to all users time zones.

### Expected behaviour
I want to be able to deactivate this behaviour.

The Trackit database dates from long before Focus, and all dates are Paris time in the database without any info enabling us to know what time zone the user who entered the date was in.
Users know that dates are Paris time.

So it's kind of a big problem that these dates are converted : it actually makes no sense since the system had been created with fixed dates for Paris time zone.
This change will just puzzle users.

### Versions

Focus-core: 0.12.3
Focus-components: 0.8.6

**Comment by pierbrisson** [comment]
:+1:

**Comment by pierr** [comment]
@sgoretti https://github.com/KleeGroup/focus-components/blob/develop/src/components/input/date/index.js#L16

**Comment by pierr** [comment]
Isn't it enough https://github.com/KleeGroup/focus-components/blob/develop/src/components/input/date/index.js#L88

**Comment by pierr** [comment]
Or this props https://github.com/KleeGroup/focus-components/blob/develop/src/components/input/date/index.js#L19

**Comment by sgoretti** [comment]
If any of this works, I'll buy you some cheesecake (or rather, the Trackit team will, since this is not yet a Linkit problem)

**Comment by pierr** [comment]
@sgoretti Is it working ?

**Comment by pierr** [comment]
@sgoretti I close it if you disagree don't hesitate to comment this issue.
