### ISSUE TITLE
[list-action-bar] Regression : Selected facets improperly displayed

### ISSUE THREAD

**Issue by durandx** [KleeGroup/focus-components#995]
# Current behaviour

The selected facet are not correctly displayed.

Before framework update :
![image](https://cloud.githubusercontent.com/assets/9220437/13286217/096ebef2-db00-11e5-80b1-3520439d9e59.png)

After framework update:
![image](https://cloud.githubusercontent.com/assets/9220437/13286232/2a1d123e-db00-11e5-8b3e-6b5865362317.png)

# Expected behaviour
Fix the css for the list-action-bar

## Versions

Focus-core: 0.12.4
Focus-components: 0.8.6

**Comment by Tommass** [comment]
the css part of this component was re-written to fix default css rendering.
If you have problem, it is probably that you have old fixing css in your projet.
To correct it in your project, please try to remove your css.

**Comment by pierr** [comment]
@durandx I close the issue, If you have any question, please come see us.

**Comment by durandx** [comment]
Ok, now the selected facet(s) is(are) correctly diplayed with the last version (0.13.0)
